package com.ctfo.yppt.baseservice.dao.bill;

import com.ctfo.yppt.baseservice.bill.beans.SysAnalysisLog;
import com.ctfo.yppt.baseservice.bill.beans.SysAnalysisLogExample;
import com.ctfo.yppt.baseservice.bill.beans.SysAnalysisLogExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SysAnalysisLogDAOImpl extends SqlMapClientDaoSupport implements SysAnalysisLogDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SYS_ANALYSIS_LOG
     *
     * @abatorgenerated Tue Mar 24 15:20:56 CST 2015
     */
    public SysAnalysisLogDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SYS_ANALYSIS_LOG
     *
     * @abatorgenerated Tue Mar 24 15:20:56 CST 2015
     */
    public void insert(SysAnalysisLog record) {
        getSqlMapClientTemplate().insert("TB_SYS_ANALYSIS_LOG.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SYS_ANALYSIS_LOG
     *
     * @abatorgenerated Tue Mar 24 15:20:56 CST 2015
     */
    public int updateByPrimaryKey(SysAnalysisLog record) {
        int rows = getSqlMapClientTemplate().update("TB_SYS_ANALYSIS_LOG.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SYS_ANALYSIS_LOG
     *
     * @abatorgenerated Tue Mar 24 15:20:56 CST 2015
     */
    public int updateByPrimaryKeySelective(SysAnalysisLog record) {
        int rows = getSqlMapClientTemplate().update("TB_SYS_ANALYSIS_LOG.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SYS_ANALYSIS_LOG
     *
     * @abatorgenerated Tue Mar 24 15:20:56 CST 2015
     */
    public List selectByExample(SysAnalysisLogExample example) {
        List list = getSqlMapClientTemplate().queryForList("TB_SYS_ANALYSIS_LOG.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SYS_ANALYSIS_LOG
     *
     * @abatorgenerated Tue Mar 24 15:20:56 CST 2015
     */
    public SysAnalysisLog selectByPrimaryKey(String id) {
        SysAnalysisLog key = new SysAnalysisLog(){};
        key.setId(id);
        SysAnalysisLog record = (SysAnalysisLog) getSqlMapClientTemplate().queryForObject("TB_SYS_ANALYSIS_LOG.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SYS_ANALYSIS_LOG
     *
     * @abatorgenerated Tue Mar 24 15:20:56 CST 2015
     */
    public int deleteByExample(SysAnalysisLogExample example) {
        int rows = getSqlMapClientTemplate().delete("TB_SYS_ANALYSIS_LOG.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SYS_ANALYSIS_LOG
     *
     * @abatorgenerated Tue Mar 24 15:20:56 CST 2015
     */
    public int deleteByPrimaryKey(String id) {
        SysAnalysisLog key = new SysAnalysisLog(){};
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("TB_SYS_ANALYSIS_LOG.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SYS_ANALYSIS_LOG
     *
     * @abatorgenerated Tue Mar 24 15:20:56 CST 2015
     */
    public int countByExample(SysAnalysisLogExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("TB_SYS_ANALYSIS_LOG.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SYS_ANALYSIS_LOG
     *
     * @abatorgenerated Tue Mar 24 15:20:56 CST 2015
     */
    public int updateByExampleSelective(SysAnalysisLog record, SysAnalysisLogExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TB_SYS_ANALYSIS_LOG.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SYS_ANALYSIS_LOG
     *
     * @abatorgenerated Tue Mar 24 15:20:56 CST 2015
     */
    public int updateByExample(SysAnalysisLog record, SysAnalysisLogExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TB_SYS_ANALYSIS_LOG.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SYS_ANALYSIS_LOG
     *
     * @abatorgenerated Tue Mar 24 15:20:56 CST 2015
     */
    public List selectByExampleWithPage(SysAnalysisLogExample example) {
        List list = getSqlMapClientTemplate().queryForList("TB_SYS_ANALYSIS_LOG.abatorgenerated_selectByExamplePage", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SYS_ANALYSIS_LOG
     *
     * @abatorgenerated Tue Mar 24 15:20:56 CST 2015
     */
    public List selectByExampleWithPage(SysAnalysisLogExampleExtended exampleExtended) {
        List list = getSqlMapClientTemplate().queryForList("TB_SYS_ANALYSIS_LOG.abatorgenerated_selectByExampleExtendedPage", exampleExtended);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SYS_ANALYSIS_LOG
     *
     * @abatorgenerated Tue Mar 24 15:20:56 CST 2015
     */
    public List getKeyBy(SysAnalysisLogExample example) {
        List list = getSqlMapClientTemplate().queryForList("TB_SYS_ANALYSIS_LOG.abatorgenerated_selectKeyBy", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SYS_ANALYSIS_LOG
     *
     * @abatorgenerated Tue Mar 24 15:20:56 CST 2015
     */
    public String getNameSpace() {
         return "TB_SYS_ANALYSIS_LOG";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SYS_ANALYSIS_LOG
     *
     * @abatorgenerated Tue Mar 24 15:20:56 CST 2015
     */
    public List getKeyBy(SysAnalysisLogExampleExtended example) {
        List list = getSqlMapClientTemplate().queryForList("TB_SYS_ANALYSIS_LOG.abatorgenerated_selectKeyByExtended", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SYS_ANALYSIS_LOG
     *
     * @abatorgenerated Tue Mar 24 15:20:56 CST 2015
     */
    public int countByExample(SysAnalysisLogExampleExtended example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("TB_SYS_ANALYSIS_LOG.abatorgenerated_countByExampleExtended", example);
        return count.intValue();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table TB_SYS_ANALYSIS_LOG
     *
     * @abatorgenerated Tue Mar 24 15:20:56 CST 2015
     */
    private static class UpdateByExampleParms extends SysAnalysisLogExample {
        private Object record;

        public UpdateByExampleParms(Object record, SysAnalysisLogExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}