package com.ctfo.yppt.baseservice.dao.bill;

import com.ctfo.yppt.baseservice.bill.beans.SysAnalysisLog;
import com.ctfo.yppt.baseservice.bill.beans.SysAnalysisLogExample;
import com.ctfo.yppt.baseservice.bill.beans.SysAnalysisLogExampleExtended;
import java.util.List;

public interface SysAnalysisLogDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SYS_ANALYSIS_LOG
     *
     * @abatorgenerated Tue Mar 24 15:20:56 CST 2015
     */
    void insert(SysAnalysisLog record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SYS_ANALYSIS_LOG
     *
     * @abatorgenerated Tue Mar 24 15:20:56 CST 2015
     */
    int updateByPrimaryKey(SysAnalysisLog record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SYS_ANALYSIS_LOG
     *
     * @abatorgenerated Tue Mar 24 15:20:56 CST 2015
     */
    int updateByPrimaryKeySelective(SysAnalysisLog record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SYS_ANALYSIS_LOG
     *
     * @abatorgenerated Tue Mar 24 15:20:56 CST 2015
     */
    List selectByExample(SysAnalysisLogExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SYS_ANALYSIS_LOG
     *
     * @abatorgenerated Tue Mar 24 15:20:56 CST 2015
     */
    SysAnalysisLog selectByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SYS_ANALYSIS_LOG
     *
     * @abatorgenerated Tue Mar 24 15:20:56 CST 2015
     */
    int deleteByExample(SysAnalysisLogExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SYS_ANALYSIS_LOG
     *
     * @abatorgenerated Tue Mar 24 15:20:56 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SYS_ANALYSIS_LOG
     *
     * @abatorgenerated Tue Mar 24 15:20:56 CST 2015
     */
    int countByExample(SysAnalysisLogExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SYS_ANALYSIS_LOG
     *
     * @abatorgenerated Tue Mar 24 15:20:56 CST 2015
     */
    int updateByExampleSelective(SysAnalysisLog record, SysAnalysisLogExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SYS_ANALYSIS_LOG
     *
     * @abatorgenerated Tue Mar 24 15:20:56 CST 2015
     */
    int updateByExample(SysAnalysisLog record, SysAnalysisLogExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SYS_ANALYSIS_LOG
     *
     * @abatorgenerated Tue Mar 24 15:20:56 CST 2015
     */
    List selectByExampleWithPage(SysAnalysisLogExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SYS_ANALYSIS_LOG
     *
     * @abatorgenerated Tue Mar 24 15:20:56 CST 2015
     */
    List selectByExampleWithPage(SysAnalysisLogExampleExtended exampleExtended);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SYS_ANALYSIS_LOG
     *
     * @abatorgenerated Tue Mar 24 15:20:56 CST 2015
     */
    List getKeyBy(SysAnalysisLogExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SYS_ANALYSIS_LOG
     *
     * @abatorgenerated Tue Mar 24 15:20:56 CST 2015
     */
    String getNameSpace();

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SYS_ANALYSIS_LOG
     *
     * @abatorgenerated Tue Mar 24 15:20:56 CST 2015
     */
    List getKeyBy(SysAnalysisLogExampleExtended example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SYS_ANALYSIS_LOG
     *
     * @abatorgenerated Tue Mar 24 15:20:56 CST 2015
     */
    int countByExample(SysAnalysisLogExampleExtended example);
}