package com.ctfo.yppt.baseservice.dao.bill;

import com.ctfo.yppt.baseservice.bill.beans.TradeCardArea;
import com.ctfo.yppt.baseservice.bill.beans.TradeCardAreaExample;
import com.ctfo.yppt.baseservice.bill.beans.TradeCardAreaExampleExtended;
import java.util.List;

public interface TradeCardAreaDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD_AREA
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    void insert(TradeCardArea record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD_AREA
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    int updateByPrimaryKey(TradeCardArea record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD_AREA
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    int updateByPrimaryKeySelective(TradeCardArea record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD_AREA
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    List selectByExample(TradeCardAreaExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD_AREA
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    TradeCardArea selectByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD_AREA
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    int deleteByExample(TradeCardAreaExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD_AREA
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD_AREA
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    int countByExample(TradeCardAreaExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD_AREA
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    int updateByExampleSelective(TradeCardArea record, TradeCardAreaExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD_AREA
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    int updateByExample(TradeCardArea record, TradeCardAreaExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD_AREA
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    List selectByExampleWithPage(TradeCardAreaExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD_AREA
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    List selectByExampleWithPage(TradeCardAreaExampleExtended exampleExtended);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD_AREA
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    List getKeyBy(TradeCardAreaExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD_AREA
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    String getNameSpace();

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD_AREA
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    List getKeyBy(TradeCardAreaExampleExtended example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD_AREA
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    int countByExample(TradeCardAreaExampleExtended example);
}