package com.ctfo.yppt.baseservice.dao.bill;

import com.ctfo.yppt.baseservice.bill.beans.TradeUserForRebate;
import com.ctfo.yppt.baseservice.bill.beans.TradeUserForRebateExample;
import com.ctfo.yppt.baseservice.bill.beans.TradeUserForRebateExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TradeUserForRebateDAOImpl extends SqlMapClientDaoSupport implements TradeUserForRebateDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public TradeUserForRebateDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public void insert(TradeUserForRebate record) {
        getSqlMapClientTemplate().insert("TS_TRADE_USER_FOR_REBATE.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public int updateByPrimaryKey(TradeUserForRebate record) {
        int rows = getSqlMapClientTemplate().update("TS_TRADE_USER_FOR_REBATE.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public int updateByPrimaryKeySelective(TradeUserForRebate record) {
        int rows = getSqlMapClientTemplate().update("TS_TRADE_USER_FOR_REBATE.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public List selectByExample(TradeUserForRebateExample example) {
        List list = getSqlMapClientTemplate().queryForList("TS_TRADE_USER_FOR_REBATE.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public TradeUserForRebate selectByPrimaryKey(String id) {
        TradeUserForRebate key = new TradeUserForRebate(){};
        key.setId(id);
        TradeUserForRebate record = (TradeUserForRebate) getSqlMapClientTemplate().queryForObject("TS_TRADE_USER_FOR_REBATE.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public int deleteByExample(TradeUserForRebateExample example) {
        int rows = getSqlMapClientTemplate().delete("TS_TRADE_USER_FOR_REBATE.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public int deleteByPrimaryKey(String id) {
        TradeUserForRebate key = new TradeUserForRebate(){};
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("TS_TRADE_USER_FOR_REBATE.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public int countByExample(TradeUserForRebateExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("TS_TRADE_USER_FOR_REBATE.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public int updateByExampleSelective(TradeUserForRebate record, TradeUserForRebateExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TS_TRADE_USER_FOR_REBATE.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public int updateByExample(TradeUserForRebate record, TradeUserForRebateExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TS_TRADE_USER_FOR_REBATE.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public List selectByExampleWithPage(TradeUserForRebateExample example) {
        List list = getSqlMapClientTemplate().queryForList("TS_TRADE_USER_FOR_REBATE.abatorgenerated_selectByExamplePage", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public List selectByExampleWithPage(TradeUserForRebateExampleExtended exampleExtended) {
        List list = getSqlMapClientTemplate().queryForList("TS_TRADE_USER_FOR_REBATE.abatorgenerated_selectByExampleExtendedPage", exampleExtended);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public List getKeyBy(TradeUserForRebateExample example) {
        List list = getSqlMapClientTemplate().queryForList("TS_TRADE_USER_FOR_REBATE.abatorgenerated_selectKeyBy", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public String getNameSpace() {
         return "TS_TRADE_USER_FOR_REBATE";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public List getKeyBy(TradeUserForRebateExampleExtended example) {
        List list = getSqlMapClientTemplate().queryForList("TS_TRADE_USER_FOR_REBATE.abatorgenerated_selectKeyByExtended", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public int countByExample(TradeUserForRebateExampleExtended example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("TS_TRADE_USER_FOR_REBATE.abatorgenerated_countByExampleExtended", example);
        return count.intValue();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    private static class UpdateByExampleParms extends TradeUserForRebateExample {
        private Object record;

        public UpdateByExampleParms(Object record, TradeUserForRebateExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}