package com.ctfo.yppt.baseservice.dao.bill;

import com.ctfo.yppt.baseservice.bill.beans.TradeCardArea;
import com.ctfo.yppt.baseservice.bill.beans.TradeCardAreaExample;
import com.ctfo.yppt.baseservice.bill.beans.TradeCardAreaExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TradeCardAreaDAOImpl extends SqlMapClientDaoSupport implements TradeCardAreaDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD_AREA
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public TradeCardAreaDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD_AREA
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public void insert(TradeCardArea record) {
        getSqlMapClientTemplate().insert("TS_TRADE_CARD_AREA.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD_AREA
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public int updateByPrimaryKey(TradeCardArea record) {
        int rows = getSqlMapClientTemplate().update("TS_TRADE_CARD_AREA.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD_AREA
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public int updateByPrimaryKeySelective(TradeCardArea record) {
        int rows = getSqlMapClientTemplate().update("TS_TRADE_CARD_AREA.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD_AREA
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public List selectByExample(TradeCardAreaExample example) {
        List list = getSqlMapClientTemplate().queryForList("TS_TRADE_CARD_AREA.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD_AREA
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public TradeCardArea selectByPrimaryKey(String id) {
        TradeCardArea key = new TradeCardArea(){};
        key.setId(id);
        TradeCardArea record = (TradeCardArea) getSqlMapClientTemplate().queryForObject("TS_TRADE_CARD_AREA.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD_AREA
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public int deleteByExample(TradeCardAreaExample example) {
        int rows = getSqlMapClientTemplate().delete("TS_TRADE_CARD_AREA.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD_AREA
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public int deleteByPrimaryKey(String id) {
        TradeCardArea key = new TradeCardArea(){};
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("TS_TRADE_CARD_AREA.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD_AREA
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public int countByExample(TradeCardAreaExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("TS_TRADE_CARD_AREA.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD_AREA
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public int updateByExampleSelective(TradeCardArea record, TradeCardAreaExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TS_TRADE_CARD_AREA.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD_AREA
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public int updateByExample(TradeCardArea record, TradeCardAreaExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TS_TRADE_CARD_AREA.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD_AREA
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public List selectByExampleWithPage(TradeCardAreaExample example) {
        List list = getSqlMapClientTemplate().queryForList("TS_TRADE_CARD_AREA.abatorgenerated_selectByExamplePage", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD_AREA
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public List selectByExampleWithPage(TradeCardAreaExampleExtended exampleExtended) {
        List list = getSqlMapClientTemplate().queryForList("TS_TRADE_CARD_AREA.abatorgenerated_selectByExampleExtendedPage", exampleExtended);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD_AREA
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public List getKeyBy(TradeCardAreaExample example) {
        List list = getSqlMapClientTemplate().queryForList("TS_TRADE_CARD_AREA.abatorgenerated_selectKeyBy", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD_AREA
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public String getNameSpace() {
         return "TS_TRADE_CARD_AREA";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD_AREA
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public List getKeyBy(TradeCardAreaExampleExtended example) {
        List list = getSqlMapClientTemplate().queryForList("TS_TRADE_CARD_AREA.abatorgenerated_selectKeyByExtended", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD_AREA
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public int countByExample(TradeCardAreaExampleExtended example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("TS_TRADE_CARD_AREA.abatorgenerated_countByExampleExtended", example);
        return count.intValue();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table TS_TRADE_CARD_AREA
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    private static class UpdateByExampleParms extends TradeCardAreaExample {
        private Object record;

        public UpdateByExampleParms(Object record, TradeCardAreaExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}