package com.ctfo.yppt.baseservice.dao.bill;

import com.ctfo.yppt.baseservice.bill.beans.TradeCard;
import com.ctfo.yppt.baseservice.bill.beans.TradeCardExample;
import com.ctfo.yppt.baseservice.bill.beans.TradeCardExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TradeCardDAOImpl extends SqlMapClientDaoSupport implements TradeCardDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD
     *
     * @abatorgenerated Tue Mar 24 15:20:54 CST 2015
     */
    public TradeCardDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD
     *
     * @abatorgenerated Tue Mar 24 15:20:54 CST 2015
     */
    public void insert(TradeCard record) {
        getSqlMapClientTemplate().insert("TS_TRADE_CARD.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public int updateByPrimaryKey(TradeCard record) {
        int rows = getSqlMapClientTemplate().update("TS_TRADE_CARD.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public int updateByPrimaryKeySelective(TradeCard record) {
        int rows = getSqlMapClientTemplate().update("TS_TRADE_CARD.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public List selectByExample(TradeCardExample example) {
        List list = getSqlMapClientTemplate().queryForList("TS_TRADE_CARD.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public TradeCard selectByPrimaryKey(String id) {
        TradeCard key = new TradeCard(){};
        key.setId(id);
        TradeCard record = (TradeCard) getSqlMapClientTemplate().queryForObject("TS_TRADE_CARD.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public int deleteByExample(TradeCardExample example) {
        int rows = getSqlMapClientTemplate().delete("TS_TRADE_CARD.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public int deleteByPrimaryKey(String id) {
        TradeCard key = new TradeCard(){};
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("TS_TRADE_CARD.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public int countByExample(TradeCardExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("TS_TRADE_CARD.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public int updateByExampleSelective(TradeCard record, TradeCardExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TS_TRADE_CARD.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public int updateByExample(TradeCard record, TradeCardExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TS_TRADE_CARD.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public List selectByExampleWithPage(TradeCardExample example) {
        List list = getSqlMapClientTemplate().queryForList("TS_TRADE_CARD.abatorgenerated_selectByExamplePage", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public List selectByExampleWithPage(TradeCardExampleExtended exampleExtended) {
        List list = getSqlMapClientTemplate().queryForList("TS_TRADE_CARD.abatorgenerated_selectByExampleExtendedPage", exampleExtended);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public List getKeyBy(TradeCardExample example) {
        List list = getSqlMapClientTemplate().queryForList("TS_TRADE_CARD.abatorgenerated_selectKeyBy", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public String getNameSpace() {
         return "TS_TRADE_CARD";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public List getKeyBy(TradeCardExampleExtended example) {
        List list = getSqlMapClientTemplate().queryForList("TS_TRADE_CARD.abatorgenerated_selectKeyByExtended", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_CARD
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public int countByExample(TradeCardExampleExtended example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("TS_TRADE_CARD.abatorgenerated_countByExampleExtended", example);
        return count.intValue();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table TS_TRADE_CARD
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    private static class UpdateByExampleParms extends TradeCardExample {
        private Object record;

        public UpdateByExampleParms(Object record, TradeCardExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}