package com.ctfo.yppt.baseservice.dao.bill;

import com.ctfo.yppt.baseservice.bill.beans.TradeUserForRebate;
import com.ctfo.yppt.baseservice.bill.beans.TradeUserForRebateExample;
import com.ctfo.yppt.baseservice.bill.beans.TradeUserForRebateExampleExtended;
import java.util.List;

public interface TradeUserForRebateDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    void insert(TradeUserForRebate record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    int updateByPrimaryKey(TradeUserForRebate record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    int updateByPrimaryKeySelective(TradeUserForRebate record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    List selectByExample(TradeUserForRebateExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    TradeUserForRebate selectByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    int deleteByExample(TradeUserForRebateExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    int countByExample(TradeUserForRebateExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    int updateByExampleSelective(TradeUserForRebate record, TradeUserForRebateExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    int updateByExample(TradeUserForRebate record, TradeUserForRebateExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    List selectByExampleWithPage(TradeUserForRebateExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    List selectByExampleWithPage(TradeUserForRebateExampleExtended exampleExtended);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    List getKeyBy(TradeUserForRebateExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    String getNameSpace();

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    List getKeyBy(TradeUserForRebateExampleExtended example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    int countByExample(TradeUserForRebateExampleExtended example);
}