package com.ctfo.yppt.bean;

import java.math.BigDecimal;

import com.ctfo.common.models.BaseSerializable;
import com.google.code.morphia.annotations.Entity;
import com.google.code.morphia.annotations.Id;

import javax.xml.bind.annotation.XmlElement;

@Entity(value="IC_Card_Credit_Order_MongoDB_Bean", noClassnameStored=true)
public class ICCardCreditOrderMongoDBBean extends BaseSerializable {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_CREDIT_ORDER.ID DB Comment: 
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	@XmlElement(name = "", required = false)
	@Id
	private String id;
	
	
	//金额
	private BigDecimal totalMoney;
	
	
	
	@XmlElement(name = "本地业务订单号(充值申请时,放入申请订单号)", required = false)
	private String localOrderNo;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_CREDIT_ORDER.PAY_ORDER_NO DB Comment: 支付订单号
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	@XmlElement(name = "支付订单号", required = false)
	private String payOrderNo;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_CREDIT_ORDER.STATUS DB Comment: (支付状态)
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	@XmlElement(name = "(支付状态)", required = false)
	private String status;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_CREDIT_ORDER.REMARK DB Comment: 描述
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	@XmlElement(name = "描述", required = false)
	private String remark;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_CREDIT_ORDER.PAY_TYPE DB Comment: 订单类型（冻结、扣款）
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	@XmlElement(name = "订单类型（冻结、扣款）", required = false)
	private String payType;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_CREDIT_ORDER.PAY_CONFIRM_DATE DB Comment: 支付确认时间
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	@XmlElement(name = "支付确认时间", required = false)
	private Long payConfirmDate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_CREDIT_ORDER.CREDIT_TIME DB Comment: 记录创建时间
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	@XmlElement(name = "记录创建时间", required = false)
	private Long creditTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_CREDIT_ORDER.RECEIVE_PAY_RESULT_TIME DB Comment: 收到支付结果时间
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	@XmlElement(name = "收到支付结果时间", required = false)
	private Long receivePayResultTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_CREDIT_ORDER.ACCOUNT_CHECK_STATUS DB Comment: 对账状态(0:未对账,1:已对账)
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	@XmlElement(name = "对账状态(0:未对账,1:已对账)", required = false)
	private String accountCheckStatus;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_CREDIT_ORDER.ID
	 * @return  the value of TB_IC_CARD_CREDIT_ORDER.ID
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_CREDIT_ORDER.ID
	 * @param id  the value for TB_IC_CARD_CREDIT_ORDER.ID
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public static String fieldId() {
		return "ID";
	}

	

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public static String fieldTbaleName() {
		return "TBALE_NAME";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_CREDIT_ORDER.LOCAL_ORDER_NO
	 * @return  the value of TB_IC_CARD_CREDIT_ORDER.LOCAL_ORDER_NO
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public String getLocalOrderNo() {
		return localOrderNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_CREDIT_ORDER.LOCAL_ORDER_NO
	 * @param localOrderNo  the value for TB_IC_CARD_CREDIT_ORDER.LOCAL_ORDER_NO
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public void setLocalOrderNo(String localOrderNo) {
		this.localOrderNo = localOrderNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public static String fieldLocalOrderNo() {
		return "LOCAL_ORDER_NO";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_CREDIT_ORDER.PAY_ORDER_NO
	 * @return  the value of TB_IC_CARD_CREDIT_ORDER.PAY_ORDER_NO
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public String getPayOrderNo() {
		return payOrderNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_CREDIT_ORDER.PAY_ORDER_NO
	 * @param payOrderNo  the value for TB_IC_CARD_CREDIT_ORDER.PAY_ORDER_NO
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public void setPayOrderNo(String payOrderNo) {
		this.payOrderNo = payOrderNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public static String fieldPayOrderNo() {
		return "PAY_ORDER_NO";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_CREDIT_ORDER.STATUS
	 * @return  the value of TB_IC_CARD_CREDIT_ORDER.STATUS
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_CREDIT_ORDER.STATUS
	 * @param status  the value for TB_IC_CARD_CREDIT_ORDER.STATUS
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public static String fieldStatus() {
		return "STATUS";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_CREDIT_ORDER.REMARK
	 * @return  the value of TB_IC_CARD_CREDIT_ORDER.REMARK
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_CREDIT_ORDER.REMARK
	 * @param remark  the value for TB_IC_CARD_CREDIT_ORDER.REMARK
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public static String fieldRemark() {
		return "REMARK";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_CREDIT_ORDER.PAY_TYPE
	 * @return  the value of TB_IC_CARD_CREDIT_ORDER.PAY_TYPE
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public String getPayType() {
		return payType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_CREDIT_ORDER.PAY_TYPE
	 * @param payType  the value for TB_IC_CARD_CREDIT_ORDER.PAY_TYPE
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public void setPayType(String payType) {
		this.payType = payType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public static String fieldPayType() {
		return "PAY_TYPE";
	}

	public BigDecimal getTotalMoney() {
		return totalMoney;
	}

	public void setTotalMoney(BigDecimal totalMoney) {
		this.totalMoney = totalMoney;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_CREDIT_ORDER.PAY_CONFIRM_DATE
	 * @return  the value of TB_IC_CARD_CREDIT_ORDER.PAY_CONFIRM_DATE
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public Long getPayConfirmDate() {
		return payConfirmDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_CREDIT_ORDER.PAY_CONFIRM_DATE
	 * @param payConfirmDate  the value for TB_IC_CARD_CREDIT_ORDER.PAY_CONFIRM_DATE
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public void setPayConfirmDate(Long payConfirmDate) {
		this.payConfirmDate = payConfirmDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public static String fieldPayConfirmDate() {
		return "PAY_CONFIRM_DATE";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_CREDIT_ORDER.CREDIT_TIME
	 * @return  the value of TB_IC_CARD_CREDIT_ORDER.CREDIT_TIME
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public Long getCreditTime() {
		return creditTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_CREDIT_ORDER.CREDIT_TIME
	 * @param creditTime  the value for TB_IC_CARD_CREDIT_ORDER.CREDIT_TIME
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public void setCreditTime(Long creditTime) {
		this.creditTime = creditTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public static String fieldCreditTime() {
		return "CREDIT_TIME";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_CREDIT_ORDER.RECEIVE_PAY_RESULT_TIME
	 * @return  the value of TB_IC_CARD_CREDIT_ORDER.RECEIVE_PAY_RESULT_TIME
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public Long getReceivePayResultTime() {
		return receivePayResultTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_CREDIT_ORDER.RECEIVE_PAY_RESULT_TIME
	 * @param receivePayResultTime  the value for TB_IC_CARD_CREDIT_ORDER.RECEIVE_PAY_RESULT_TIME
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public void setReceivePayResultTime(Long receivePayResultTime) {
		this.receivePayResultTime = receivePayResultTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public static String fieldReceivePayResultTime() {
		return "RECEIVE_PAY_RESULT_TIME";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_CREDIT_ORDER.ACCOUNT_CHECK_STATUS
	 * @return  the value of TB_IC_CARD_CREDIT_ORDER.ACCOUNT_CHECK_STATUS
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public String getAccountCheckStatus() {
		return accountCheckStatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_CREDIT_ORDER.ACCOUNT_CHECK_STATUS
	 * @param accountCheckStatus  the value for TB_IC_CARD_CREDIT_ORDER.ACCOUNT_CHECK_STATUS
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public void setAccountCheckStatus(String accountCheckStatus) {
		this.accountCheckStatus = accountCheckStatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public static String fieldAccountCheckStatus() {
		return "ACCOUNT_CHECK_STATUS";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public ICCardCreditOrderMongoDBBean() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public static String tableName() {
		return "TB_IC_CARD_CREDIT_ORDER";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public static String daoInterface() {
		return "com.ctfo.yppt.baseservice.dao.recharge.ICCardCreditOrderDAO";
	}
}