package com.ctfo.yppt.bean;

import com.ctfo.yppt.baseservice.recharge.beans.ICCardPaymentOrder;
import com.google.code.morphia.annotations.Entity;
import com.google.code.morphia.annotations.Id;

@Entity(value="IC_Payment_Order_MongoDB_Bean", noClassnameStored=true)
public class ICPaymentOrderMongoDBBean extends ICCardPaymentOrder{

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_CREDIT_ORDER.ID DB Comment: 
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	
	@Id
	private String mid;
	
}