package com.ctfo.yppt.baseservice.dao.card;

import com.ctfo.yppt.baseservice.card.beans.ICCardApplyProcessLog;
import com.ctfo.yppt.baseservice.card.beans.ICCardApplyProcessLogExample;
import com.ctfo.yppt.baseservice.card.beans.ICCardApplyProcessLogExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ICCardApplyProcessLogDAOImpl extends SqlMapClientDaoSupport implements ICCardApplyProcessLogDAO {

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_PROCESS
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    public ICCardApplyProcessLogDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_PROCESS
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    public void insert(ICCardApplyProcessLog record) {
        getSqlMapClientTemplate().insert(
                "TB_IC_CARD_APPLY_PROCESS.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_PROCESS
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    public int updateByPrimaryKey(ICCardApplyProcessLog record) {
        int rows = getSqlMapClientTemplate().update(
                "TB_IC_CARD_APPLY_PROCESS.abatorgenerated_updateByPrimaryKey",
                record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_PROCESS
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    public int updateByPrimaryKeySelective(ICCardApplyProcessLog record) {
        int rows = getSqlMapClientTemplate()
                .update("TB_IC_CARD_APPLY_PROCESS.abatorgenerated_updateByPrimaryKeySelective",
                        record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_PROCESS
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    public List selectByExample(ICCardApplyProcessLogExample example) {
        List list = getSqlMapClientTemplate().queryForList(
                "TB_IC_CARD_APPLY_PROCESS.abatorgenerated_selectByExample",
                example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_PROCESS
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    public ICCardApplyProcessLog selectByPrimaryKey(String id) {
        ICCardApplyProcessLog key = new ICCardApplyProcessLog() {
        };
        key.setId(id);
        ICCardApplyProcessLog record = (ICCardApplyProcessLog) getSqlMapClientTemplate()
                .queryForObject(
                        "TB_IC_CARD_APPLY_PROCESS.abatorgenerated_selectByPrimaryKey",
                        key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_PROCESS
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    public int deleteByExample(ICCardApplyProcessLogExample example) {
        int rows = getSqlMapClientTemplate().delete(
                "TB_IC_CARD_APPLY_PROCESS.abatorgenerated_deleteByExample",
                example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_PROCESS
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    public int deleteByPrimaryKey(String id) {
        ICCardApplyProcessLog key = new ICCardApplyProcessLog() {
        };
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete(
                "TB_IC_CARD_APPLY_PROCESS.abatorgenerated_deleteByPrimaryKey",
                key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_PROCESS
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    public int countByExample(ICCardApplyProcessLogExample example) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
                "TB_IC_CARD_APPLY_PROCESS.abatorgenerated_countByExample",
                example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_PROCESS
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    public int updateByExampleSelective(ICCardApplyProcessLog record,
            ICCardApplyProcessLogExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate()
                .update("TB_IC_CARD_APPLY_PROCESS.abatorgenerated_updateByExampleSelective",
                        parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_PROCESS
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    public int updateByExample(ICCardApplyProcessLog record,
            ICCardApplyProcessLogExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update(
                "TB_IC_CARD_APPLY_PROCESS.abatorgenerated_updateByExample",
                parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_PROCESS
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    public List selectByExampleWithPage(ICCardApplyProcessLogExample example) {
        List list = getSqlMapClientTemplate().queryForList(
                "TB_IC_CARD_APPLY_PROCESS.abatorgenerated_selectByExamplePage",
                example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_PROCESS
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    public List selectByExampleWithPage(
            ICCardApplyProcessLogExampleExtended exampleExtended) {
        List list = getSqlMapClientTemplate()
                .queryForList(
                        "TB_IC_CARD_APPLY_PROCESS.abatorgenerated_selectByExampleExtendedPage",
                        exampleExtended);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_PROCESS
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    public List getKeyBy(ICCardApplyProcessLogExample example) {
        List list = getSqlMapClientTemplate()
                .queryForList(
                        "TB_IC_CARD_APPLY_PROCESS.abatorgenerated_selectKeyBy",
                        example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_PROCESS
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    public String getNameSpace() {
        return "TB_IC_CARD_APPLY_PROCESS";
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_PROCESS
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    public List getKeyBy(ICCardApplyProcessLogExampleExtended example) {
        List list = getSqlMapClientTemplate().queryForList(
                "TB_IC_CARD_APPLY_PROCESS.abatorgenerated_selectKeyByExtended",
                example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_PROCESS
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    public int countByExample(ICCardApplyProcessLogExampleExtended example) {
        Integer count = (Integer) getSqlMapClientTemplate()
                .queryForObject(
                        "TB_IC_CARD_APPLY_PROCESS.abatorgenerated_countByExampleExtended",
                        example);
        return count.intValue();
    }

    /**
     * This class was generated by Abator for iBATIS. This class corresponds to the database table TB_IC_CARD_APPLY_PROCESS
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    private static class UpdateByExampleParms extends
            ICCardApplyProcessLogExample {
        private Object record;

        public UpdateByExampleParms(Object record,
                ICCardApplyProcessLogExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}