package com.ctfo.yppt.baseservice.dao.card;

import com.ctfo.yppt.baseservice.card.beans.ICCardApplyDetail;
import com.ctfo.yppt.baseservice.card.beans.ICCardApplyDetailExample;
import com.ctfo.yppt.baseservice.card.beans.ICCardApplyDetailExampleExtended;
import java.util.List;

public interface ICCardApplyDetailDAO {

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_DETAIL
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    void insert(ICCardApplyDetail record);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_DETAIL
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    int updateByPrimaryKey(ICCardApplyDetail record);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_DETAIL
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    int updateByPrimaryKeySelective(ICCardApplyDetail record);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_DETAIL
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    List selectByExample(ICCardApplyDetailExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_DETAIL
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    ICCardApplyDetail selectByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_DETAIL
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    int deleteByExample(ICCardApplyDetailExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_DETAIL
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_DETAIL
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    int countByExample(ICCardApplyDetailExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_DETAIL
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    int updateByExampleSelective(ICCardApplyDetail record,
            ICCardApplyDetailExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_DETAIL
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    int updateByExample(ICCardApplyDetail record,
            ICCardApplyDetailExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_DETAIL
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    List selectByExampleWithPage(ICCardApplyDetailExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_DETAIL
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    List selectByExampleWithPage(
            ICCardApplyDetailExampleExtended exampleExtended);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_DETAIL
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    List getKeyBy(ICCardApplyDetailExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_DETAIL
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    String getNameSpace();

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_DETAIL
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    List getKeyBy(ICCardApplyDetailExampleExtended example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_DETAIL
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    int countByExample(ICCardApplyDetailExampleExtended example);
}