package com.ctfo.yppt.baseservice.dao.card;

import com.ctfo.yppt.baseservice.card.beans.ICCard;
import com.ctfo.yppt.baseservice.card.beans.ICCardExample;
import com.ctfo.yppt.baseservice.card.beans.ICCardExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ICCardDAOImpl extends SqlMapClientDaoSupport implements ICCardDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD
	 * @abatorgenerated  Tue Feb 03 19:07:43 CST 2015
	 */
	public ICCardDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD
	 * @abatorgenerated  Tue Feb 03 19:07:43 CST 2015
	 */
	public void insert(ICCard record) {
		getSqlMapClientTemplate().insert("TB_IC_CARD.abatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD
	 * @abatorgenerated  Tue Feb 03 19:07:43 CST 2015
	 */
	public int updateByPrimaryKey(ICCard record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_IC_CARD.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD
	 * @abatorgenerated  Tue Feb 03 19:07:43 CST 2015
	 */
	public int updateByPrimaryKeySelective(ICCard record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_IC_CARD.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD
	 * @abatorgenerated  Tue Feb 03 19:07:43 CST 2015
	 */
	public List selectByExample(ICCardExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_CARD.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD
	 * @abatorgenerated  Tue Feb 03 19:07:43 CST 2015
	 */
	public ICCard selectByPrimaryKey(String id) {
		ICCard key = new ICCard() {
		};
		key.setId(id);
		ICCard record = (ICCard) getSqlMapClientTemplate().queryForObject(
				"TB_IC_CARD.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD
	 * @abatorgenerated  Tue Feb 03 19:07:43 CST 2015
	 */
	public int deleteByExample(ICCardExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_IC_CARD.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD
	 * @abatorgenerated  Tue Feb 03 19:07:43 CST 2015
	 */
	public int deleteByPrimaryKey(String id) {
		ICCard key = new ICCard() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"TB_IC_CARD.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD
	 * @abatorgenerated  Tue Feb 03 19:07:43 CST 2015
	 */
	public int countByExample(ICCardExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_IC_CARD.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD
	 * @abatorgenerated  Tue Feb 03 19:07:43 CST 2015
	 */
	public int updateByExampleSelective(ICCard record, ICCardExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_IC_CARD.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD
	 * @abatorgenerated  Tue Feb 03 19:07:43 CST 2015
	 */
	public int updateByExample(ICCard record, ICCardExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_IC_CARD.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD
	 * @abatorgenerated  Tue Feb 03 19:07:43 CST 2015
	 */
	public List selectByExampleWithPage(ICCardExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_CARD.abatorgenerated_selectByExamplePage", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD
	 * @abatorgenerated  Tue Feb 03 19:07:43 CST 2015
	 */
	public List selectByExampleWithPage(ICCardExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_CARD.abatorgenerated_selectByExampleExtendedPage",
				exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD
	 * @abatorgenerated  Tue Feb 03 19:07:43 CST 2015
	 */
	public List getKeyBy(ICCardExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_CARD.abatorgenerated_selectKeyBy", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD
	 * @abatorgenerated  Tue Feb 03 19:07:43 CST 2015
	 */
	public String getNameSpace() {
		return "TB_IC_CARD";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD
	 * @abatorgenerated  Tue Feb 03 19:07:43 CST 2015
	 */
	public List getKeyBy(ICCardExampleExtended example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_CARD.abatorgenerated_selectKeyByExtended", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD
	 * @abatorgenerated  Tue Feb 03 19:07:43 CST 2015
	 */
	public int countByExample(ICCardExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_IC_CARD.abatorgenerated_countByExampleExtended", example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table TB_IC_CARD
	 * @abatorgenerated  Tue Feb 03 19:07:43 CST 2015
	 */
	private static class UpdateByExampleParms extends ICCardExample {
		private Object record;

		public UpdateByExampleParms(Object record, ICCardExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}