package com.ctfo.yppt.baseservice.dao.card;

import com.ctfo.yppt.baseservice.card.beans.ICCardApply;
import com.ctfo.yppt.baseservice.card.beans.ICCardApplyExample;
import com.ctfo.yppt.baseservice.card.beans.ICCardApplyExampleExtended;
import java.util.List;

public interface ICCardApplyDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	void insert(ICCardApply record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	int updateByPrimaryKey(ICCardApply record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	int updateByPrimaryKeySelective(ICCardApply record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	List selectByExample(ICCardApplyExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	ICCardApply selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	int deleteByExample(ICCardApplyExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	int countByExample(ICCardApplyExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	int updateByExampleSelective(ICCardApply record, ICCardApplyExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	int updateByExample(ICCardApply record, ICCardApplyExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	List selectByExampleWithPage(ICCardApplyExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	List selectByExampleWithPage(ICCardApplyExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	List getKeyBy(ICCardApplyExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	List getKeyBy(ICCardApplyExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	int countByExample(ICCardApplyExampleExtended example);
}