package com.ctfo.yppt.baseservice.dao.card;

import com.ctfo.yppt.baseservice.card.beans.ICCardApply;
import com.ctfo.yppt.baseservice.card.beans.ICCardApplyExample;
import com.ctfo.yppt.baseservice.card.beans.ICCardApplyExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ICCardApplyDAOImpl extends SqlMapClientDaoSupport implements ICCardApplyDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	public ICCardApplyDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	public void insert(ICCardApply record) {
		getSqlMapClientTemplate().insert(
				"TB_IC_CARD_APPLY.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	public int updateByPrimaryKey(ICCardApply record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_IC_CARD_APPLY.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	public int updateByPrimaryKeySelective(ICCardApply record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_IC_CARD_APPLY.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	public List selectByExample(ICCardApplyExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_CARD_APPLY.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	public ICCardApply selectByPrimaryKey(String id) {
		ICCardApply key = new ICCardApply() {
		};
		key.setId(id);
		ICCardApply record = (ICCardApply) getSqlMapClientTemplate()
				.queryForObject(
						"TB_IC_CARD_APPLY.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	public int deleteByExample(ICCardApplyExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_IC_CARD_APPLY.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	public int deleteByPrimaryKey(String id) {
		ICCardApply key = new ICCardApply() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"TB_IC_CARD_APPLY.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	public int countByExample(ICCardApplyExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_IC_CARD_APPLY.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	public int updateByExampleSelective(ICCardApply record,
			ICCardApplyExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_IC_CARD_APPLY.abatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	public int updateByExample(ICCardApply record, ICCardApplyExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_IC_CARD_APPLY.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	public List selectByExampleWithPage(ICCardApplyExample example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_IC_CARD_APPLY.abatorgenerated_selectByExamplePage",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	public List selectByExampleWithPage(
			ICCardApplyExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_CARD_APPLY.abatorgenerated_selectByExampleExtendedPage",
				exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	public List getKeyBy(ICCardApplyExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_CARD_APPLY.abatorgenerated_selectKeyBy", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	public String getNameSpace() {
		return "TB_IC_CARD_APPLY";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	public List getKeyBy(ICCardApplyExampleExtended example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_IC_CARD_APPLY.abatorgenerated_selectKeyByExtended",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	public int countByExample(ICCardApplyExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_IC_CARD_APPLY.abatorgenerated_countByExampleExtended",
				example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	private static class UpdateByExampleParms extends ICCardApplyExample {
		private Object record;

		public UpdateByExampleParms(Object record, ICCardApplyExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}