package com.ctfo.yppt.baseservice.dao.card;

import com.ctfo.yppt.baseservice.card.beans.ICCardCreditAccountIO;
import com.ctfo.yppt.baseservice.card.beans.ICCardCreditAccountIOExample;
import com.ctfo.yppt.baseservice.card.beans.ICCardCreditAccountIOExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ICCardCreditAccountIODAOImpl extends SqlMapClientDaoSupport implements ICCardCreditAccountIODAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ACCOUNT_IO
	 * @abatorgenerated  Sat Feb 07 14:56:31 CST 2015
	 */
	public ICCardCreditAccountIODAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ACCOUNT_IO
	 * @abatorgenerated  Sat Feb 07 14:56:31 CST 2015
	 */
	public void insert(ICCardCreditAccountIO record) {
		getSqlMapClientTemplate().insert(
				"TB_IC_CARD_CREDIT_ACCOUNT_IO.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ACCOUNT_IO
	 * @abatorgenerated  Sat Feb 07 14:56:31 CST 2015
	 */
	public int updateByPrimaryKey(ICCardCreditAccountIO record) {
		int rows = getSqlMapClientTemplate()
				.update("TB_IC_CARD_CREDIT_ACCOUNT_IO.abatorgenerated_updateByPrimaryKey",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ACCOUNT_IO
	 * @abatorgenerated  Sat Feb 07 14:56:31 CST 2015
	 */
	public int updateByPrimaryKeySelective(ICCardCreditAccountIO record) {
		int rows = getSqlMapClientTemplate()
				.update("TB_IC_CARD_CREDIT_ACCOUNT_IO.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ACCOUNT_IO
	 * @abatorgenerated  Sat Feb 07 14:56:31 CST 2015
	 */
	public List selectByExample(ICCardCreditAccountIOExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_CARD_CREDIT_ACCOUNT_IO.abatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ACCOUNT_IO
	 * @abatorgenerated  Sat Feb 07 14:56:31 CST 2015
	 */
	public ICCardCreditAccountIO selectByPrimaryKey(String id) {
		ICCardCreditAccountIO key = new ICCardCreditAccountIO() {
		};
		key.setId(id);
		ICCardCreditAccountIO record = (ICCardCreditAccountIO) getSqlMapClientTemplate()
				.queryForObject(
						"TB_IC_CARD_CREDIT_ACCOUNT_IO.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ACCOUNT_IO
	 * @abatorgenerated  Sat Feb 07 14:56:31 CST 2015
	 */
	public int deleteByExample(ICCardCreditAccountIOExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_IC_CARD_CREDIT_ACCOUNT_IO.abatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ACCOUNT_IO
	 * @abatorgenerated  Sat Feb 07 14:56:31 CST 2015
	 */
	public int deleteByPrimaryKey(String id) {
		ICCardCreditAccountIO key = new ICCardCreditAccountIO() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate()
				.delete("TB_IC_CARD_CREDIT_ACCOUNT_IO.abatorgenerated_deleteByPrimaryKey",
						key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ACCOUNT_IO
	 * @abatorgenerated  Sat Feb 07 14:56:31 CST 2015
	 */
	public int countByExample(ICCardCreditAccountIOExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_IC_CARD_CREDIT_ACCOUNT_IO.abatorgenerated_countByExample",
				example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ACCOUNT_IO
	 * @abatorgenerated  Sat Feb 07 14:56:31 CST 2015
	 */
	public int updateByExampleSelective(ICCardCreditAccountIO record,
			ICCardCreditAccountIOExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("TB_IC_CARD_CREDIT_ACCOUNT_IO.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ACCOUNT_IO
	 * @abatorgenerated  Sat Feb 07 14:56:31 CST 2015
	 */
	public int updateByExample(ICCardCreditAccountIO record,
			ICCardCreditAccountIOExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_IC_CARD_CREDIT_ACCOUNT_IO.abatorgenerated_updateByExample",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ACCOUNT_IO
	 * @abatorgenerated  Sat Feb 07 14:56:31 CST 2015
	 */
	public List selectByExampleWithPage(ICCardCreditAccountIOExample example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_IC_CARD_CREDIT_ACCOUNT_IO.abatorgenerated_selectByExamplePage",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ACCOUNT_IO
	 * @abatorgenerated  Sat Feb 07 14:56:31 CST 2015
	 */
	public List selectByExampleWithPage(
			ICCardCreditAccountIOExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_IC_CARD_CREDIT_ACCOUNT_IO.abatorgenerated_selectByExampleExtendedPage",
						exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ACCOUNT_IO
	 * @abatorgenerated  Sat Feb 07 14:56:31 CST 2015
	 */
	public List getKeyBy(ICCardCreditAccountIOExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_CARD_CREDIT_ACCOUNT_IO.abatorgenerated_selectKeyBy",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ACCOUNT_IO
	 * @abatorgenerated  Sat Feb 07 14:56:31 CST 2015
	 */
	public String getNameSpace() {
		return "TB_IC_CARD_CREDIT_ACCOUNT_IO";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ACCOUNT_IO
	 * @abatorgenerated  Sat Feb 07 14:56:31 CST 2015
	 */
	public List getKeyBy(ICCardCreditAccountIOExampleExtended example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_IC_CARD_CREDIT_ACCOUNT_IO.abatorgenerated_selectKeyByExtended",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ACCOUNT_IO
	 * @abatorgenerated  Sat Feb 07 14:56:31 CST 2015
	 */
	public int countByExample(ICCardCreditAccountIOExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject(
						"TB_IC_CARD_CREDIT_ACCOUNT_IO.abatorgenerated_countByExampleExtended",
						example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table TB_IC_CARD_CREDIT_ACCOUNT_IO
	 * @abatorgenerated  Sat Feb 07 14:56:31 CST 2015
	 */
	private static class UpdateByExampleParms extends
			ICCardCreditAccountIOExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				ICCardCreditAccountIOExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}