package com.ctfo.yppt.baseservice.dao.card;

import com.ctfo.yppt.baseservice.card.beans.ICCard;
import com.ctfo.yppt.baseservice.card.beans.ICCardExample;
import com.ctfo.yppt.baseservice.card.beans.ICCardExampleExtended;
import java.util.List;

public interface ICCardDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD
	 * @abatorgenerated  Tue Feb 03 19:07:43 CST 2015
	 */
	void insert(ICCard record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD
	 * @abatorgenerated  Tue Feb 03 19:07:43 CST 2015
	 */
	int updateByPrimaryKey(ICCard record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD
	 * @abatorgenerated  Tue Feb 03 19:07:43 CST 2015
	 */
	int updateByPrimaryKeySelective(ICCard record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD
	 * @abatorgenerated  Tue Feb 03 19:07:43 CST 2015
	 */
	List selectByExample(ICCardExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD
	 * @abatorgenerated  Tue Feb 03 19:07:43 CST 2015
	 */
	ICCard selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD
	 * @abatorgenerated  Tue Feb 03 19:07:43 CST 2015
	 */
	int deleteByExample(ICCardExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD
	 * @abatorgenerated  Tue Feb 03 19:07:43 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD
	 * @abatorgenerated  Tue Feb 03 19:07:43 CST 2015
	 */
	int countByExample(ICCardExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD
	 * @abatorgenerated  Tue Feb 03 19:07:43 CST 2015
	 */
	int updateByExampleSelective(ICCard record, ICCardExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD
	 * @abatorgenerated  Tue Feb 03 19:07:43 CST 2015
	 */
	int updateByExample(ICCard record, ICCardExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD
	 * @abatorgenerated  Tue Feb 03 19:07:43 CST 2015
	 */
	List selectByExampleWithPage(ICCardExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD
	 * @abatorgenerated  Tue Feb 03 19:07:43 CST 2015
	 */
	List selectByExampleWithPage(ICCardExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD
	 * @abatorgenerated  Tue Feb 03 19:07:43 CST 2015
	 */
	List getKeyBy(ICCardExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD
	 * @abatorgenerated  Tue Feb 03 19:07:43 CST 2015
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD
	 * @abatorgenerated  Tue Feb 03 19:07:43 CST 2015
	 */
	List getKeyBy(ICCardExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD
	 * @abatorgenerated  Tue Feb 03 19:07:43 CST 2015
	 */
	int countByExample(ICCardExampleExtended example);
}