package com.ctfo.yppt.baseservice.dao.card;

import com.ctfo.yppt.baseservice.card.beans.ICCardMain;
import com.ctfo.yppt.baseservice.card.beans.ICCardMainExample;
import com.ctfo.yppt.baseservice.card.beans.ICCardMainExampleExtended;
import java.util.List;

public interface ICCardMainDAO {

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    void insert(ICCardMain record);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    int updateByPrimaryKey(ICCardMain record);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    int updateByPrimaryKeySelective(ICCardMain record);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    List selectByExample(ICCardMainExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    ICCardMain selectByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    int deleteByExample(ICCardMainExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    int countByExample(ICCardMainExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    int updateByExampleSelective(ICCardMain record, ICCardMainExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    int updateByExample(ICCardMain record, ICCardMainExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    List selectByExampleWithPage(ICCardMainExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    List selectByExampleWithPage(ICCardMainExampleExtended exampleExtended);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    List getKeyBy(ICCardMainExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    String getNameSpace();

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    List getKeyBy(ICCardMainExampleExtended example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    int countByExample(ICCardMainExampleExtended example);
}