package com.ctfo.yppt.baseservice.dao.card;

import com.ctfo.yppt.baseservice.card.beans.ICCardApplyDetail;
import com.ctfo.yppt.baseservice.card.beans.ICCardApplyDetailExample;
import com.ctfo.yppt.baseservice.card.beans.ICCardApplyDetailExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ICCardApplyDetailDAOImpl extends SqlMapClientDaoSupport implements ICCardApplyDetailDAO {

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_DETAIL
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    public ICCardApplyDetailDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_DETAIL
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    public void insert(ICCardApplyDetail record) {
        getSqlMapClientTemplate().insert(
                "TB_IC_CARD_APPLY_DETAIL.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_DETAIL
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    public int updateByPrimaryKey(ICCardApplyDetail record) {
        int rows = getSqlMapClientTemplate().update(
                "TB_IC_CARD_APPLY_DETAIL.abatorgenerated_updateByPrimaryKey",
                record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_DETAIL
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    public int updateByPrimaryKeySelective(ICCardApplyDetail record) {
        int rows = getSqlMapClientTemplate()
                .update("TB_IC_CARD_APPLY_DETAIL.abatorgenerated_updateByPrimaryKeySelective",
                        record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_DETAIL
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    public List selectByExample(ICCardApplyDetailExample example) {
        List list = getSqlMapClientTemplate().queryForList(
                "TB_IC_CARD_APPLY_DETAIL.abatorgenerated_selectByExample",
                example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_DETAIL
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    public ICCardApplyDetail selectByPrimaryKey(String id) {
        ICCardApplyDetail key = new ICCardApplyDetail() {
        };
        key.setId(id);
        ICCardApplyDetail record = (ICCardApplyDetail) getSqlMapClientTemplate()
                .queryForObject(
                        "TB_IC_CARD_APPLY_DETAIL.abatorgenerated_selectByPrimaryKey",
                        key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_DETAIL
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    public int deleteByExample(ICCardApplyDetailExample example) {
        int rows = getSqlMapClientTemplate().delete(
                "TB_IC_CARD_APPLY_DETAIL.abatorgenerated_deleteByExample",
                example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_DETAIL
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    public int deleteByPrimaryKey(String id) {
        ICCardApplyDetail key = new ICCardApplyDetail() {
        };
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete(
                "TB_IC_CARD_APPLY_DETAIL.abatorgenerated_deleteByPrimaryKey",
                key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_DETAIL
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    public int countByExample(ICCardApplyDetailExample example) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
                "TB_IC_CARD_APPLY_DETAIL.abatorgenerated_countByExample",
                example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_DETAIL
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    public int updateByExampleSelective(ICCardApplyDetail record,
            ICCardApplyDetailExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate()
                .update("TB_IC_CARD_APPLY_DETAIL.abatorgenerated_updateByExampleSelective",
                        parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_DETAIL
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    public int updateByExample(ICCardApplyDetail record,
            ICCardApplyDetailExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update(
                "TB_IC_CARD_APPLY_DETAIL.abatorgenerated_updateByExample",
                parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_DETAIL
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    public List selectByExampleWithPage(ICCardApplyDetailExample example) {
        List list = getSqlMapClientTemplate().queryForList(
                "TB_IC_CARD_APPLY_DETAIL.abatorgenerated_selectByExamplePage",
                example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_DETAIL
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    public List selectByExampleWithPage(
            ICCardApplyDetailExampleExtended exampleExtended) {
        List list = getSqlMapClientTemplate()
                .queryForList(
                        "TB_IC_CARD_APPLY_DETAIL.abatorgenerated_selectByExampleExtendedPage",
                        exampleExtended);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_DETAIL
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    public List getKeyBy(ICCardApplyDetailExample example) {
        List list = getSqlMapClientTemplate().queryForList(
                "TB_IC_CARD_APPLY_DETAIL.abatorgenerated_selectKeyBy", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_DETAIL
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    public String getNameSpace() {
        return "TB_IC_CARD_APPLY_DETAIL";
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_DETAIL
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    public List getKeyBy(ICCardApplyDetailExampleExtended example) {
        List list = getSqlMapClientTemplate().queryForList(
                "TB_IC_CARD_APPLY_DETAIL.abatorgenerated_selectKeyByExtended",
                example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY_DETAIL
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    public int countByExample(ICCardApplyDetailExampleExtended example) {
        Integer count = (Integer) getSqlMapClientTemplate()
                .queryForObject(
                        "TB_IC_CARD_APPLY_DETAIL.abatorgenerated_countByExampleExtended",
                        example);
        return count.intValue();
    }

    /**
     * This class was generated by Abator for iBATIS. This class corresponds to the database table TB_IC_CARD_APPLY_DETAIL
     * @abatorgenerated  Sun Jan 25 16:48:53 CST 2015
     */
    private static class UpdateByExampleParms extends ICCardApplyDetailExample {
        private Object record;

        public UpdateByExampleParms(Object record,
                ICCardApplyDetailExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}