package com.ctfo.yppt.baseservice.bill.beans;

import com.ctfo.common.models.BaseSerializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlElement;

public class TradeUserForRebate extends BaseSerializable {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TS_TRADE_USER_FOR_REBATE.ID
     * DB Comment: 主键
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    @XmlElement(name="主键", required=false )
    private String id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TS_TRADE_USER_FOR_REBATE.USER_ID
     * DB Comment: 会员ID
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    @XmlElement(name="会员ID", required=false )
    private String userId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TS_TRADE_USER_FOR_REBATE.SUM_MONEY_CY_SY
     * DB Comment: 中石油柴油消费总额
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    @XmlElement(name="中石油柴油消费总额", required=false )
    private Long sumMoneyCySy;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TS_TRADE_USER_FOR_REBATE.SUM_MONEY_QY_SY
     * DB Comment: 中石油汽油消费总额
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    @XmlElement(name="中石油汽油消费总额", required=false )
    private Long sumMoneyQySy;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TS_TRADE_USER_FOR_REBATE.SUM_MONEY_CY_SH
     * DB Comment: 中石化柴油总额
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    @XmlElement(name="中石化柴油总额", required=false )
    private Long sumMoneyCySh;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TS_TRADE_USER_FOR_REBATE.SUM_MONEY_QY_SH
     * DB Comment: 中石化汽油消费总额
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    @XmlElement(name="中石化汽油消费总额", required=false )
    private BigDecimal sumMoneyQySh;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TS_TRADE_USER_FOR_REBATE.TS_YEAR_MONTH
     * DB Comment: 统计月份，例如2012-10
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    @XmlElement(name="统计月份，例如2012-10", required=false )
    private String tsYearMonth;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TS_TRADE_USER_FOR_REBATE.CREATE_TIME
     * DB Comment: 统计时间
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    @XmlElement(name="统计时间", required=false )
    private Long createTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TS_TRADE_USER_FOR_REBATE.TS_START_TIME
     * DB Comment: 统计开始时间
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    @XmlElement(name="统计开始时间", required=false )
    private Long tsStartTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TS_TRADE_USER_FOR_REBATE.TS_END_TIME
     * DB Comment: 统计结算时间
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    @XmlElement(name="统计结算时间", required=false )
    private Long tsEndTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TS_TRADE_USER_FOR_REBATE.ID
     *
     * @return the value of TS_TRADE_USER_FOR_REBATE.ID
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TS_TRADE_USER_FOR_REBATE.ID
     *
     * @param id the value for TS_TRADE_USER_FOR_REBATE.ID
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public static String fieldId() {
        return "ID";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TS_TRADE_USER_FOR_REBATE.USER_ID
     *
     * @return the value of TS_TRADE_USER_FOR_REBATE.USER_ID
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TS_TRADE_USER_FOR_REBATE.USER_ID
     *
     * @param userId the value for TS_TRADE_USER_FOR_REBATE.USER_ID
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public static String fieldUserId() {
        return "USER_ID";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TS_TRADE_USER_FOR_REBATE.SUM_MONEY_CY_SY
     *
     * @return the value of TS_TRADE_USER_FOR_REBATE.SUM_MONEY_CY_SY
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public Long getSumMoneyCySy() {
        return sumMoneyCySy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TS_TRADE_USER_FOR_REBATE.SUM_MONEY_CY_SY
     *
     * @param sumMoneyCySy the value for TS_TRADE_USER_FOR_REBATE.SUM_MONEY_CY_SY
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public void setSumMoneyCySy(Long sumMoneyCySy) {
        this.sumMoneyCySy = sumMoneyCySy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public static String fieldSumMoneyCySy() {
        return "SUM_MONEY_CY_SY";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TS_TRADE_USER_FOR_REBATE.SUM_MONEY_QY_SY
     *
     * @return the value of TS_TRADE_USER_FOR_REBATE.SUM_MONEY_QY_SY
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public Long getSumMoneyQySy() {
        return sumMoneyQySy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TS_TRADE_USER_FOR_REBATE.SUM_MONEY_QY_SY
     *
     * @param sumMoneyQySy the value for TS_TRADE_USER_FOR_REBATE.SUM_MONEY_QY_SY
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public void setSumMoneyQySy(Long sumMoneyQySy) {
        this.sumMoneyQySy = sumMoneyQySy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public static String fieldSumMoneyQySy() {
        return "SUM_MONEY_QY_SY";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TS_TRADE_USER_FOR_REBATE.SUM_MONEY_CY_SH
     *
     * @return the value of TS_TRADE_USER_FOR_REBATE.SUM_MONEY_CY_SH
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public Long getSumMoneyCySh() {
        return sumMoneyCySh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TS_TRADE_USER_FOR_REBATE.SUM_MONEY_CY_SH
     *
     * @param sumMoneyCySh the value for TS_TRADE_USER_FOR_REBATE.SUM_MONEY_CY_SH
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public void setSumMoneyCySh(Long sumMoneyCySh) {
        this.sumMoneyCySh = sumMoneyCySh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public static String fieldSumMoneyCySh() {
        return "SUM_MONEY_CY_SH";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TS_TRADE_USER_FOR_REBATE.SUM_MONEY_QY_SH
     *
     * @return the value of TS_TRADE_USER_FOR_REBATE.SUM_MONEY_QY_SH
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public BigDecimal getSumMoneyQySh() {
        return sumMoneyQySh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TS_TRADE_USER_FOR_REBATE.SUM_MONEY_QY_SH
     *
     * @param sumMoneyQySh the value for TS_TRADE_USER_FOR_REBATE.SUM_MONEY_QY_SH
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public void setSumMoneyQySh(BigDecimal sumMoneyQySh) {
        this.sumMoneyQySh = sumMoneyQySh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public static String fieldSumMoneyQySh() {
        return "SUM_MONEY_QY_SH";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TS_TRADE_USER_FOR_REBATE.TS_YEAR_MONTH
     *
     * @return the value of TS_TRADE_USER_FOR_REBATE.TS_YEAR_MONTH
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public String getTsYearMonth() {
        return tsYearMonth;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TS_TRADE_USER_FOR_REBATE.TS_YEAR_MONTH
     *
     * @param tsYearMonth the value for TS_TRADE_USER_FOR_REBATE.TS_YEAR_MONTH
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public void setTsYearMonth(String tsYearMonth) {
        this.tsYearMonth = tsYearMonth;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public static String fieldTsYearMonth() {
        return "TS_YEAR_MONTH";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TS_TRADE_USER_FOR_REBATE.CREATE_TIME
     *
     * @return the value of TS_TRADE_USER_FOR_REBATE.CREATE_TIME
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TS_TRADE_USER_FOR_REBATE.CREATE_TIME
     *
     * @param createTime the value for TS_TRADE_USER_FOR_REBATE.CREATE_TIME
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public static String fieldCreateTime() {
        return "CREATE_TIME";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TS_TRADE_USER_FOR_REBATE.TS_START_TIME
     *
     * @return the value of TS_TRADE_USER_FOR_REBATE.TS_START_TIME
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public Long getTsStartTime() {
        return tsStartTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TS_TRADE_USER_FOR_REBATE.TS_START_TIME
     *
     * @param tsStartTime the value for TS_TRADE_USER_FOR_REBATE.TS_START_TIME
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public void setTsStartTime(Long tsStartTime) {
        this.tsStartTime = tsStartTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public static String fieldTsStartTime() {
        return "TS_START_TIME";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TS_TRADE_USER_FOR_REBATE.TS_END_TIME
     *
     * @return the value of TS_TRADE_USER_FOR_REBATE.TS_END_TIME
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public Long getTsEndTime() {
        return tsEndTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TS_TRADE_USER_FOR_REBATE.TS_END_TIME
     *
     * @param tsEndTime the value for TS_TRADE_USER_FOR_REBATE.TS_END_TIME
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public void setTsEndTime(Long tsEndTime) {
        this.tsEndTime = tsEndTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public static String fieldTsEndTime() {
        return "TS_END_TIME";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public TradeUserForRebate() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public static String tableName() {
        return "TS_TRADE_USER_FOR_REBATE";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TS_TRADE_USER_FOR_REBATE
     *
     * @abatorgenerated Tue Mar 24 15:20:55 CST 2015
     */
    public static String daoInterface() {
        return "com.ctfo.yppt.baseservice.dao.bill.TradeUserForRebateDAO";
    }
}