package com.ctfo.yppt.baseservice.dao.system;

import com.ctfo.yppt.baseservice.system.beans.CardStat;
import com.ctfo.yppt.baseservice.system.beans.CardStatExample;
import com.ctfo.yppt.baseservice.system.beans.CardStatExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class CardStatDAOImpl extends SqlMapClientDaoSupport implements CardStatDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_CARD_COMSUME_STAT
	 * @abatorgenerated  Mon Feb 02 17:58:55 CST 2015
	 */
	public CardStatDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_CARD_COMSUME_STAT
	 * @abatorgenerated  Mon Feb 02 17:58:55 CST 2015
	 */
	public void insert(CardStat record) {
		getSqlMapClientTemplate().insert(
				"TS_CARD_COMSUME_STAT.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_CARD_COMSUME_STAT
	 * @abatorgenerated  Mon Feb 02 17:58:55 CST 2015
	 */
	public int updateByPrimaryKey(CardStat record) {
		int rows = getSqlMapClientTemplate().update(
				"TS_CARD_COMSUME_STAT.abatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_CARD_COMSUME_STAT
	 * @abatorgenerated  Mon Feb 02 17:58:55 CST 2015
	 */
	public int updateByPrimaryKeySelective(CardStat record) {
		int rows = getSqlMapClientTemplate()
				.update("TS_CARD_COMSUME_STAT.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_CARD_COMSUME_STAT
	 * @abatorgenerated  Mon Feb 02 17:58:55 CST 2015
	 */
	public List selectByExample(CardStatExample example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TS_CARD_COMSUME_STAT.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_CARD_COMSUME_STAT
	 * @abatorgenerated  Mon Feb 02 17:58:55 CST 2015
	 */
	public CardStat selectByPrimaryKey(String id) {
		CardStat key = new CardStat() {
		};
		key.setId(id);
		CardStat record = (CardStat) getSqlMapClientTemplate().queryForObject(
				"TS_CARD_COMSUME_STAT.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_CARD_COMSUME_STAT
	 * @abatorgenerated  Mon Feb 02 17:58:55 CST 2015
	 */
	public int deleteByExample(CardStatExample example) {
		int rows = getSqlMapClientTemplate()
				.delete("TS_CARD_COMSUME_STAT.abatorgenerated_deleteByExample",
						example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_CARD_COMSUME_STAT
	 * @abatorgenerated  Mon Feb 02 17:58:55 CST 2015
	 */
	public int deleteByPrimaryKey(String id) {
		CardStat key = new CardStat() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"TS_CARD_COMSUME_STAT.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_CARD_COMSUME_STAT
	 * @abatorgenerated  Mon Feb 02 17:58:55 CST 2015
	 */
	public int countByExample(CardStatExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TS_CARD_COMSUME_STAT.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_CARD_COMSUME_STAT
	 * @abatorgenerated  Mon Feb 02 17:58:55 CST 2015
	 */
	public int updateByExampleSelective(CardStat record, CardStatExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("TS_CARD_COMSUME_STAT.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_CARD_COMSUME_STAT
	 * @abatorgenerated  Mon Feb 02 17:58:55 CST 2015
	 */
	public int updateByExample(CardStat record, CardStatExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TS_CARD_COMSUME_STAT.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_CARD_COMSUME_STAT
	 * @abatorgenerated  Mon Feb 02 17:58:55 CST 2015
	 */
	public List selectByExampleWithPage(CardStatExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TS_CARD_COMSUME_STAT.abatorgenerated_selectByExamplePage",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_CARD_COMSUME_STAT
	 * @abatorgenerated  Mon Feb 02 17:58:55 CST 2015
	 */
	public List selectByExampleWithPage(CardStatExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TS_CARD_COMSUME_STAT.abatorgenerated_selectByExampleExtendedPage",
						exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_CARD_COMSUME_STAT
	 * @abatorgenerated  Mon Feb 02 17:58:55 CST 2015
	 */
	public List getKeyBy(CardStatExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TS_CARD_COMSUME_STAT.abatorgenerated_selectKeyBy", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_CARD_COMSUME_STAT
	 * @abatorgenerated  Mon Feb 02 17:58:55 CST 2015
	 */
	public String getNameSpace() {
		return "TS_CARD_COMSUME_STAT";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_CARD_COMSUME_STAT
	 * @abatorgenerated  Mon Feb 02 17:58:55 CST 2015
	 */
	public List getKeyBy(CardStatExampleExtended example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TS_CARD_COMSUME_STAT.abatorgenerated_selectKeyByExtended",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_CARD_COMSUME_STAT
	 * @abatorgenerated  Mon Feb 02 17:58:55 CST 2015
	 */
	public int countByExample(CardStatExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TS_CARD_COMSUME_STAT.abatorgenerated_countByExampleExtended",
				example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table TS_CARD_COMSUME_STAT
	 * @abatorgenerated  Mon Feb 02 17:58:55 CST 2015
	 */
	private static class UpdateByExampleParms extends CardStatExample {
		private Object record;

		public UpdateByExampleParms(Object record, CardStatExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}