package com.ctfo.yppt.baseservice.dao.system;

import com.ctfo.yppt.baseservice.system.beans.ICCardAccountConfig;
import com.ctfo.yppt.baseservice.system.beans.ICCardAccountConfigExample;
import com.ctfo.yppt.baseservice.system.beans.ICCardAccountConfigExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ICCardAccountConfigDAOImpl extends SqlMapClientDaoSupport implements ICCardAccountConfigDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_ACCOUNT_CONFIG
	 * @abatorgenerated  Sat Jan 31 18:49:20 CST 2015
	 */
	public ICCardAccountConfigDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_ACCOUNT_CONFIG
	 * @abatorgenerated  Sat Jan 31 18:49:20 CST 2015
	 */
	public void insert(ICCardAccountConfig record) {
		getSqlMapClientTemplate().insert(
				"TB_IC_CARD_ACCOUNT_CONFIG.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_ACCOUNT_CONFIG
	 * @abatorgenerated  Sat Jan 31 18:49:20 CST 2015
	 */
	public int updateByPrimaryKey(ICCardAccountConfig record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_IC_CARD_ACCOUNT_CONFIG.abatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_ACCOUNT_CONFIG
	 * @abatorgenerated  Sat Jan 31 18:49:20 CST 2015
	 */
	public int updateByPrimaryKeySelective(ICCardAccountConfig record) {
		int rows = getSqlMapClientTemplate()
				.update("TB_IC_CARD_ACCOUNT_CONFIG.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_ACCOUNT_CONFIG
	 * @abatorgenerated  Sat Jan 31 18:49:20 CST 2015
	 */
	public List selectByExample(ICCardAccountConfigExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_CARD_ACCOUNT_CONFIG.abatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_ACCOUNT_CONFIG
	 * @abatorgenerated  Sat Jan 31 18:49:20 CST 2015
	 */
	public ICCardAccountConfig selectByPrimaryKey(String id) {
		ICCardAccountConfig key = new ICCardAccountConfig() {
		};
		key.setId(id);
		ICCardAccountConfig record = (ICCardAccountConfig) getSqlMapClientTemplate()
				.queryForObject(
						"TB_IC_CARD_ACCOUNT_CONFIG.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_ACCOUNT_CONFIG
	 * @abatorgenerated  Sat Jan 31 18:49:20 CST 2015
	 */
	public int deleteByExample(ICCardAccountConfigExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_IC_CARD_ACCOUNT_CONFIG.abatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_ACCOUNT_CONFIG
	 * @abatorgenerated  Sat Jan 31 18:49:20 CST 2015
	 */
	public int deleteByPrimaryKey(String id) {
		ICCardAccountConfig key = new ICCardAccountConfig() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"TB_IC_CARD_ACCOUNT_CONFIG.abatorgenerated_deleteByPrimaryKey",
				key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_ACCOUNT_CONFIG
	 * @abatorgenerated  Sat Jan 31 18:49:20 CST 2015
	 */
	public int countByExample(ICCardAccountConfigExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_IC_CARD_ACCOUNT_CONFIG.abatorgenerated_countByExample",
				example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_ACCOUNT_CONFIG
	 * @abatorgenerated  Sat Jan 31 18:49:20 CST 2015
	 */
	public int updateByExampleSelective(ICCardAccountConfig record,
			ICCardAccountConfigExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("TB_IC_CARD_ACCOUNT_CONFIG.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_ACCOUNT_CONFIG
	 * @abatorgenerated  Sat Jan 31 18:49:20 CST 2015
	 */
	public int updateByExample(ICCardAccountConfig record,
			ICCardAccountConfigExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_IC_CARD_ACCOUNT_CONFIG.abatorgenerated_updateByExample",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_ACCOUNT_CONFIG
	 * @abatorgenerated  Sat Jan 31 18:49:20 CST 2015
	 */
	public List selectByExampleWithPage(ICCardAccountConfigExample example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_IC_CARD_ACCOUNT_CONFIG.abatorgenerated_selectByExamplePage",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_ACCOUNT_CONFIG
	 * @abatorgenerated  Sat Jan 31 18:49:20 CST 2015
	 */
	public List selectByExampleWithPage(
			ICCardAccountConfigExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_IC_CARD_ACCOUNT_CONFIG.abatorgenerated_selectByExampleExtendedPage",
						exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_ACCOUNT_CONFIG
	 * @abatorgenerated  Sat Jan 31 18:49:20 CST 2015
	 */
	public List getKeyBy(ICCardAccountConfigExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_CARD_ACCOUNT_CONFIG.abatorgenerated_selectKeyBy",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_ACCOUNT_CONFIG
	 * @abatorgenerated  Sat Jan 31 18:49:20 CST 2015
	 */
	public String getNameSpace() {
		return "TB_IC_CARD_ACCOUNT_CONFIG";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_ACCOUNT_CONFIG
	 * @abatorgenerated  Sat Jan 31 18:49:20 CST 2015
	 */
	public List getKeyBy(ICCardAccountConfigExampleExtended example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_IC_CARD_ACCOUNT_CONFIG.abatorgenerated_selectKeyByExtended",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_ACCOUNT_CONFIG
	 * @abatorgenerated  Sat Jan 31 18:49:20 CST 2015
	 */
	public int countByExample(ICCardAccountConfigExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject(
						"TB_IC_CARD_ACCOUNT_CONFIG.abatorgenerated_countByExampleExtended",
						example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table TB_IC_CARD_ACCOUNT_CONFIG
	 * @abatorgenerated  Sat Jan 31 18:49:20 CST 2015
	 */
	private static class UpdateByExampleParms extends
			ICCardAccountConfigExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				ICCardAccountConfigExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}