package com.ctfo.yppt.baseservice.dao.system;

import com.ctfo.yppt.baseservice.system.beans.ICCardAccountConfig;
import com.ctfo.yppt.baseservice.system.beans.ICCardAccountConfigExample;
import com.ctfo.yppt.baseservice.system.beans.ICCardAccountConfigExampleExtended;
import java.util.List;

public interface ICCardAccountConfigDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_ACCOUNT_CONFIG
	 * @abatorgenerated  Sat Jan 31 18:49:20 CST 2015
	 */
	void insert(ICCardAccountConfig record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_ACCOUNT_CONFIG
	 * @abatorgenerated  Sat Jan 31 18:49:20 CST 2015
	 */
	int updateByPrimaryKey(ICCardAccountConfig record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_ACCOUNT_CONFIG
	 * @abatorgenerated  Sat Jan 31 18:49:20 CST 2015
	 */
	int updateByPrimaryKeySelective(ICCardAccountConfig record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_ACCOUNT_CONFIG
	 * @abatorgenerated  Sat Jan 31 18:49:20 CST 2015
	 */
	List selectByExample(ICCardAccountConfigExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_ACCOUNT_CONFIG
	 * @abatorgenerated  Sat Jan 31 18:49:20 CST 2015
	 */
	ICCardAccountConfig selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_ACCOUNT_CONFIG
	 * @abatorgenerated  Sat Jan 31 18:49:20 CST 2015
	 */
	int deleteByExample(ICCardAccountConfigExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_ACCOUNT_CONFIG
	 * @abatorgenerated  Sat Jan 31 18:49:20 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_ACCOUNT_CONFIG
	 * @abatorgenerated  Sat Jan 31 18:49:20 CST 2015
	 */
	int countByExample(ICCardAccountConfigExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_ACCOUNT_CONFIG
	 * @abatorgenerated  Sat Jan 31 18:49:20 CST 2015
	 */
	int updateByExampleSelective(ICCardAccountConfig record,
			ICCardAccountConfigExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_ACCOUNT_CONFIG
	 * @abatorgenerated  Sat Jan 31 18:49:20 CST 2015
	 */
	int updateByExample(ICCardAccountConfig record,
			ICCardAccountConfigExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_ACCOUNT_CONFIG
	 * @abatorgenerated  Sat Jan 31 18:49:20 CST 2015
	 */
	List selectByExampleWithPage(ICCardAccountConfigExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_ACCOUNT_CONFIG
	 * @abatorgenerated  Sat Jan 31 18:49:20 CST 2015
	 */
	List selectByExampleWithPage(
			ICCardAccountConfigExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_ACCOUNT_CONFIG
	 * @abatorgenerated  Sat Jan 31 18:49:20 CST 2015
	 */
	List getKeyBy(ICCardAccountConfigExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_ACCOUNT_CONFIG
	 * @abatorgenerated  Sat Jan 31 18:49:20 CST 2015
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_ACCOUNT_CONFIG
	 * @abatorgenerated  Sat Jan 31 18:49:20 CST 2015
	 */
	List getKeyBy(ICCardAccountConfigExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_ACCOUNT_CONFIG
	 * @abatorgenerated  Sat Jan 31 18:49:20 CST 2015
	 */
	int countByExample(ICCardAccountConfigExampleExtended example);
}