package com.ctfo.yppt.baseservice.dao.system;

import com.ctfo.yppt.baseservice.system.beans.UserStat;
import com.ctfo.yppt.baseservice.system.beans.UserStatExample;
import com.ctfo.yppt.baseservice.system.beans.UserStatExampleExtended;
import java.util.List;

public interface UserStatDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	void insert(UserStat record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	int updateByPrimaryKey(UserStat record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	int updateByPrimaryKeySelective(UserStat record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	List selectByExample(UserStatExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	UserStat selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	int deleteByExample(UserStatExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	int countByExample(UserStatExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	int updateByExampleSelective(UserStat record, UserStatExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	int updateByExample(UserStat record, UserStatExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	List selectByExampleWithPage(UserStatExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	List selectByExampleWithPage(UserStatExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	List getKeyBy(UserStatExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	List getKeyBy(UserStatExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	int countByExample(UserStatExampleExtended example);
}