package com.ctfo.yppt.baseservice.dao.system;

import com.ctfo.yppt.baseservice.system.beans.UserStat;
import com.ctfo.yppt.baseservice.system.beans.UserStatExample;
import com.ctfo.yppt.baseservice.system.beans.UserStatExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class UserStatDAOImpl extends SqlMapClientDaoSupport implements UserStatDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public UserStatDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public void insert(UserStat record) {
		getSqlMapClientTemplate().insert("TS_USER_STAT.abatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public int updateByPrimaryKey(UserStat record) {
		int rows = getSqlMapClientTemplate().update(
				"TS_USER_STAT.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public int updateByPrimaryKeySelective(UserStat record) {
		int rows = getSqlMapClientTemplate().update(
				"TS_USER_STAT.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public List selectByExample(UserStatExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TS_USER_STAT.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public UserStat selectByPrimaryKey(String id) {
		UserStat key = new UserStat() {
		};
		key.setId(id);
		UserStat record = (UserStat) getSqlMapClientTemplate().queryForObject(
				"TS_USER_STAT.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public int deleteByExample(UserStatExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TS_USER_STAT.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public int deleteByPrimaryKey(String id) {
		UserStat key = new UserStat() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"TS_USER_STAT.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public int countByExample(UserStatExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TS_USER_STAT.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public int updateByExampleSelective(UserStat record, UserStatExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TS_USER_STAT.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public int updateByExample(UserStat record, UserStatExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TS_USER_STAT.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public List selectByExampleWithPage(UserStatExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TS_USER_STAT.abatorgenerated_selectByExamplePage", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public List selectByExampleWithPage(UserStatExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate().queryForList(
				"TS_USER_STAT.abatorgenerated_selectByExampleExtendedPage",
				exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public List getKeyBy(UserStatExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TS_USER_STAT.abatorgenerated_selectKeyBy", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public String getNameSpace() {
		return "TS_USER_STAT";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public List getKeyBy(UserStatExampleExtended example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TS_USER_STAT.abatorgenerated_selectKeyByExtended", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public int countByExample(UserStatExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TS_USER_STAT.abatorgenerated_countByExampleExtended", example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	private static class UpdateByExampleParms extends UserStatExample {
		private Object record;

		public UpdateByExampleParms(Object record, UserStatExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}