package com.ctfo.yppt.baseservice.card.beans;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ICCardMainExample implements Serializable {

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    protected String orderByClause;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    protected List oredCriteria;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    protected int skipNum;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    protected int endNum;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    protected int limitNum;

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    public ICCardMainExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    protected ICCardMainExample(ICCardMainExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    public static String tableName() {
        return "TB_IC_CARD_MAIN";
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    public static String daoInterface() {
        return "com.ctfo.yppt.baseservice.dao.card.ICCardMainDAO";
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    public void setSkipNum(int skipNum) {
        this.skipNum = skipNum;
        this.endNum = this.skipNum + this.limitNum + 1;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    public int getSkipNum() {
        return this.skipNum;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    public void setEndNum(int endNum) {
        this.endNum = endNum;
        this.limitNum = this.endNum - this.skipNum - 1;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    public int getEndNum() {
        return this.endNum;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    public void setLimitNum(int limitNum) {
        this.limitNum = limitNum;
        this.endNum = this.skipNum + this.limitNum + 1;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    public int getLimitNum() {
        return this.limitNum;
    }

    /**
     * This class was generated by Abator for iBATIS. This class corresponds to the database table TB_IC_CARD_MAIN
     * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
     */
    public static class Criteria implements Serializable {
        /**
         * This field was generated by Abator for iBATIS. This field corresponds to the database table TB_IC_CARD_MAIN
         * @abatorgenerated  Sun Jan 25 16:48:52 CST 2015
         */
        private static final long serialVersionUID = 1L;
        protected List criteriaWithoutValue;
        protected List criteriaWithSingleValue;
        protected List criteriaWithListValue;
        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                    || criteriaWithSingleValue.size() > 0
                    || criteriaWithListValue.size() > 0
                    || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value,
                String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property
                        + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values,
                String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property
                        + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1,
                Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property
                        + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("ID in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("ID not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return this;
        }

        public Criteria andCardNumberIsNull() {
            addCriterion("CARD_NUMBER is null");
            return this;
        }

        public Criteria andCardNumberIsNotNull() {
            addCriterion("CARD_NUMBER is not null");
            return this;
        }

        public Criteria andCardNumberEqualTo(String value) {
            addCriterion("CARD_NUMBER =", value, "cardNumber");
            return this;
        }

        public Criteria andCardNumberNotEqualTo(String value) {
            addCriterion("CARD_NUMBER <>", value, "cardNumber");
            return this;
        }

        public Criteria andCardNumberGreaterThan(String value) {
            addCriterion("CARD_NUMBER >", value, "cardNumber");
            return this;
        }

        public Criteria andCardNumberGreaterThanOrEqualTo(String value) {
            addCriterion("CARD_NUMBER >=", value, "cardNumber");
            return this;
        }

        public Criteria andCardNumberLessThan(String value) {
            addCriterion("CARD_NUMBER <", value, "cardNumber");
            return this;
        }

        public Criteria andCardNumberLessThanOrEqualTo(String value) {
            addCriterion("CARD_NUMBER <=", value, "cardNumber");
            return this;
        }

        public Criteria andCardNumberLike(String value) {
            addCriterion("CARD_NUMBER like", value, "cardNumber");
            return this;
        }

        public Criteria andCardNumberNotLike(String value) {
            addCriterion("CARD_NUMBER not like", value, "cardNumber");
            return this;
        }

        public Criteria andCardNumberIn(List values) {
            addCriterion("CARD_NUMBER in", values, "cardNumber");
            return this;
        }

        public Criteria andCardNumberNotIn(List values) {
            addCriterion("CARD_NUMBER not in", values, "cardNumber");
            return this;
        }

        public Criteria andCardNumberBetween(String value1, String value2) {
            addCriterion("CARD_NUMBER between", value1, value2, "cardNumber");
            return this;
        }

        public Criteria andCardNumberNotBetween(String value1, String value2) {
            addCriterion("CARD_NUMBER not between", value1, value2,
                    "cardNumber");
            return this;
        }

        public Criteria andBalanceIsNull() {
            addCriterion("BALANCE is null");
            return this;
        }

        public Criteria andBalanceIsNotNull() {
            addCriterion("BALANCE is not null");
            return this;
        }

        public Criteria andBalanceEqualTo(BigDecimal value) {
            addCriterion("BALANCE =", value, "balance");
            return this;
        }

        public Criteria andBalanceNotEqualTo(BigDecimal value) {
            addCriterion("BALANCE <>", value, "balance");
            return this;
        }

        public Criteria andBalanceGreaterThan(BigDecimal value) {
            addCriterion("BALANCE >", value, "balance");
            return this;
        }

        public Criteria andBalanceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BALANCE >=", value, "balance");
            return this;
        }

        public Criteria andBalanceLessThan(BigDecimal value) {
            addCriterion("BALANCE <", value, "balance");
            return this;
        }

        public Criteria andBalanceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BALANCE <=", value, "balance");
            return this;
        }

        public Criteria andBalanceIn(List values) {
            addCriterion("BALANCE in", values, "balance");
            return this;
        }

        public Criteria andBalanceNotIn(List values) {
            addCriterion("BALANCE not in", values, "balance");
            return this;
        }

        public Criteria andBalanceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BALANCE between", value1, value2, "balance");
            return this;
        }

        public Criteria andBalanceNotBetween(BigDecimal value1,
                BigDecimal value2) {
            addCriterion("BALANCE not between", value1, value2, "balance");
            return this;
        }

        public Criteria andOpencardofficecodeIsNull() {
            addCriterion("OPENCARDOFFICECODE is null");
            return this;
        }

        public Criteria andOpencardofficecodeIsNotNull() {
            addCriterion("OPENCARDOFFICECODE is not null");
            return this;
        }

        public Criteria andOpencardofficecodeEqualTo(String value) {
            addCriterion("OPENCARDOFFICECODE =", value, "opencardofficecode");
            return this;
        }

        public Criteria andOpencardofficecodeNotEqualTo(String value) {
            addCriterion("OPENCARDOFFICECODE <>", value, "opencardofficecode");
            return this;
        }

        public Criteria andOpencardofficecodeGreaterThan(String value) {
            addCriterion("OPENCARDOFFICECODE >", value, "opencardofficecode");
            return this;
        }

        public Criteria andOpencardofficecodeGreaterThanOrEqualTo(String value) {
            addCriterion("OPENCARDOFFICECODE >=", value, "opencardofficecode");
            return this;
        }

        public Criteria andOpencardofficecodeLessThan(String value) {
            addCriterion("OPENCARDOFFICECODE <", value, "opencardofficecode");
            return this;
        }

        public Criteria andOpencardofficecodeLessThanOrEqualTo(String value) {
            addCriterion("OPENCARDOFFICECODE <=", value, "opencardofficecode");
            return this;
        }

        public Criteria andOpencardofficecodeLike(String value) {
            addCriterion("OPENCARDOFFICECODE like", value, "opencardofficecode");
            return this;
        }

        public Criteria andOpencardofficecodeNotLike(String value) {
            addCriterion("OPENCARDOFFICECODE not like", value,
                    "opencardofficecode");
            return this;
        }

        public Criteria andOpencardofficecodeIn(List values) {
            addCriterion("OPENCARDOFFICECODE in", values, "opencardofficecode");
            return this;
        }

        public Criteria andOpencardofficecodeNotIn(List values) {
            addCriterion("OPENCARDOFFICECODE not in", values,
                    "opencardofficecode");
            return this;
        }

        public Criteria andOpencardofficecodeBetween(String value1,
                String value2) {
            addCriterion("OPENCARDOFFICECODE between", value1, value2,
                    "opencardofficecode");
            return this;
        }

        public Criteria andOpencardofficecodeNotBetween(String value1,
                String value2) {
            addCriterion("OPENCARDOFFICECODE not between", value1, value2,
                    "opencardofficecode");
            return this;
        }

        public Criteria andOpencardofficenameIsNull() {
            addCriterion("OPENCARDOFFICENAME is null");
            return this;
        }

        public Criteria andOpencardofficenameIsNotNull() {
            addCriterion("OPENCARDOFFICENAME is not null");
            return this;
        }

        public Criteria andOpencardofficenameEqualTo(String value) {
            addCriterion("OPENCARDOFFICENAME =", value, "opencardofficename");
            return this;
        }

        public Criteria andOpencardofficenameNotEqualTo(String value) {
            addCriterion("OPENCARDOFFICENAME <>", value, "opencardofficename");
            return this;
        }

        public Criteria andOpencardofficenameGreaterThan(String value) {
            addCriterion("OPENCARDOFFICENAME >", value, "opencardofficename");
            return this;
        }

        public Criteria andOpencardofficenameGreaterThanOrEqualTo(String value) {
            addCriterion("OPENCARDOFFICENAME >=", value, "opencardofficename");
            return this;
        }

        public Criteria andOpencardofficenameLessThan(String value) {
            addCriterion("OPENCARDOFFICENAME <", value, "opencardofficename");
            return this;
        }

        public Criteria andOpencardofficenameLessThanOrEqualTo(String value) {
            addCriterion("OPENCARDOFFICENAME <=", value, "opencardofficename");
            return this;
        }

        public Criteria andOpencardofficenameLike(String value) {
            addCriterion("OPENCARDOFFICENAME like", value, "opencardofficename");
            return this;
        }

        public Criteria andOpencardofficenameNotLike(String value) {
            addCriterion("OPENCARDOFFICENAME not like", value,
                    "opencardofficename");
            return this;
        }

        public Criteria andOpencardofficenameIn(List values) {
            addCriterion("OPENCARDOFFICENAME in", values, "opencardofficename");
            return this;
        }

        public Criteria andOpencardofficenameNotIn(List values) {
            addCriterion("OPENCARDOFFICENAME not in", values,
                    "opencardofficename");
            return this;
        }

        public Criteria andOpencardofficenameBetween(String value1,
                String value2) {
            addCriterion("OPENCARDOFFICENAME between", value1, value2,
                    "opencardofficename");
            return this;
        }

        public Criteria andOpencardofficenameNotBetween(String value1,
                String value2) {
            addCriterion("OPENCARDOFFICENAME not between", value1, value2,
                    "opencardofficename");
            return this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("CREATED_TIME is null");
            return this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("CREATED_TIME is not null");
            return this;
        }

        public Criteria andCreatedTimeEqualTo(Long value) {
            addCriterion("CREATED_TIME =", value, "createdTime");
            return this;
        }

        public Criteria andCreatedTimeNotEqualTo(Long value) {
            addCriterion("CREATED_TIME <>", value, "createdTime");
            return this;
        }

        public Criteria andCreatedTimeGreaterThan(Long value) {
            addCriterion("CREATED_TIME >", value, "createdTime");
            return this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("CREATED_TIME >=", value, "createdTime");
            return this;
        }

        public Criteria andCreatedTimeLessThan(Long value) {
            addCriterion("CREATED_TIME <", value, "createdTime");
            return this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Long value) {
            addCriterion("CREATED_TIME <=", value, "createdTime");
            return this;
        }

        public Criteria andCreatedTimeIn(List values) {
            addCriterion("CREATED_TIME in", values, "createdTime");
            return this;
        }

        public Criteria andCreatedTimeNotIn(List values) {
            addCriterion("CREATED_TIME not in", values, "createdTime");
            return this;
        }

        public Criteria andCreatedTimeBetween(Long value1, Long value2) {
            addCriterion("CREATED_TIME between", value1, value2, "createdTime");
            return this;
        }

        public Criteria andCreatedTimeNotBetween(Long value1, Long value2) {
            addCriterion("CREATED_TIME not between", value1, value2,
                    "createdTime");
            return this;
        }

        public Criteria andModifiedTimeIsNull() {
            addCriterion("MODIFIED_TIME is null");
            return this;
        }

        public Criteria andModifiedTimeIsNotNull() {
            addCriterion("MODIFIED_TIME is not null");
            return this;
        }

        public Criteria andModifiedTimeEqualTo(Long value) {
            addCriterion("MODIFIED_TIME =", value, "modifiedTime");
            return this;
        }

        public Criteria andModifiedTimeNotEqualTo(Long value) {
            addCriterion("MODIFIED_TIME <>", value, "modifiedTime");
            return this;
        }

        public Criteria andModifiedTimeGreaterThan(Long value) {
            addCriterion("MODIFIED_TIME >", value, "modifiedTime");
            return this;
        }

        public Criteria andModifiedTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("MODIFIED_TIME >=", value, "modifiedTime");
            return this;
        }

        public Criteria andModifiedTimeLessThan(Long value) {
            addCriterion("MODIFIED_TIME <", value, "modifiedTime");
            return this;
        }

        public Criteria andModifiedTimeLessThanOrEqualTo(Long value) {
            addCriterion("MODIFIED_TIME <=", value, "modifiedTime");
            return this;
        }

        public Criteria andModifiedTimeIn(List values) {
            addCriterion("MODIFIED_TIME in", values, "modifiedTime");
            return this;
        }

        public Criteria andModifiedTimeNotIn(List values) {
            addCriterion("MODIFIED_TIME not in", values, "modifiedTime");
            return this;
        }

        public Criteria andModifiedTimeBetween(Long value1, Long value2) {
            addCriterion("MODIFIED_TIME between", value1, value2,
                    "modifiedTime");
            return this;
        }

        public Criteria andModifiedTimeNotBetween(Long value1, Long value2) {
            addCriterion("MODIFIED_TIME not between", value1, value2,
                    "modifiedTime");
            return this;
        }

        public Criteria andCtrdituserIsNull() {
            addCriterion("CTRDITUSER is null");
            return this;
        }

        public Criteria andCtrdituserIsNotNull() {
            addCriterion("CTRDITUSER is not null");
            return this;
        }

        public Criteria andCtrdituserEqualTo(String value) {
            addCriterion("CTRDITUSER =", value, "ctrdituser");
            return this;
        }

        public Criteria andCtrdituserNotEqualTo(String value) {
            addCriterion("CTRDITUSER <>", value, "ctrdituser");
            return this;
        }

        public Criteria andCtrdituserGreaterThan(String value) {
            addCriterion("CTRDITUSER >", value, "ctrdituser");
            return this;
        }

        public Criteria andCtrdituserGreaterThanOrEqualTo(String value) {
            addCriterion("CTRDITUSER >=", value, "ctrdituser");
            return this;
        }

        public Criteria andCtrdituserLessThan(String value) {
            addCriterion("CTRDITUSER <", value, "ctrdituser");
            return this;
        }

        public Criteria andCtrdituserLessThanOrEqualTo(String value) {
            addCriterion("CTRDITUSER <=", value, "ctrdituser");
            return this;
        }

        public Criteria andCtrdituserLike(String value) {
            addCriterion("CTRDITUSER like", value, "ctrdituser");
            return this;
        }

        public Criteria andCtrdituserNotLike(String value) {
            addCriterion("CTRDITUSER not like", value, "ctrdituser");
            return this;
        }

        public Criteria andCtrdituserIn(List values) {
            addCriterion("CTRDITUSER in", values, "ctrdituser");
            return this;
        }

        public Criteria andCtrdituserNotIn(List values) {
            addCriterion("CTRDITUSER not in", values, "ctrdituser");
            return this;
        }

        public Criteria andCtrdituserBetween(String value1, String value2) {
            addCriterion("CTRDITUSER between", value1, value2, "ctrdituser");
            return this;
        }

        public Criteria andCtrdituserNotBetween(String value1, String value2) {
            addCriterion("CTRDITUSER not between", value1, value2, "ctrdituser");
            return this;
        }

        public Criteria andModifinguserIsNull() {
            addCriterion("MODIFINGUSER is null");
            return this;
        }

        public Criteria andModifinguserIsNotNull() {
            addCriterion("MODIFINGUSER is not null");
            return this;
        }

        public Criteria andModifinguserEqualTo(String value) {
            addCriterion("MODIFINGUSER =", value, "modifinguser");
            return this;
        }

        public Criteria andModifinguserNotEqualTo(String value) {
            addCriterion("MODIFINGUSER <>", value, "modifinguser");
            return this;
        }

        public Criteria andModifinguserGreaterThan(String value) {
            addCriterion("MODIFINGUSER >", value, "modifinguser");
            return this;
        }

        public Criteria andModifinguserGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFINGUSER >=", value, "modifinguser");
            return this;
        }

        public Criteria andModifinguserLessThan(String value) {
            addCriterion("MODIFINGUSER <", value, "modifinguser");
            return this;
        }

        public Criteria andModifinguserLessThanOrEqualTo(String value) {
            addCriterion("MODIFINGUSER <=", value, "modifinguser");
            return this;
        }

        public Criteria andModifinguserLike(String value) {
            addCriterion("MODIFINGUSER like", value, "modifinguser");
            return this;
        }

        public Criteria andModifinguserNotLike(String value) {
            addCriterion("MODIFINGUSER not like", value, "modifinguser");
            return this;
        }

        public Criteria andModifinguserIn(List values) {
            addCriterion("MODIFINGUSER in", values, "modifinguser");
            return this;
        }

        public Criteria andModifinguserNotIn(List values) {
            addCriterion("MODIFINGUSER not in", values, "modifinguser");
            return this;
        }

        public Criteria andModifinguserBetween(String value1, String value2) {
            addCriterion("MODIFINGUSER between", value1, value2, "modifinguser");
            return this;
        }

        public Criteria andModifinguserNotBetween(String value1, String value2) {
            addCriterion("MODIFINGUSER not between", value1, value2,
                    "modifinguser");
            return this;
        }

        public Criteria andStateIsNull() {
            addCriterion("STATE is null");
            return this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("STATE is not null");
            return this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("STATE =", value, "state");
            return this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("STATE <>", value, "state");
            return this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("STATE >", value, "state");
            return this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("STATE >=", value, "state");
            return this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("STATE <", value, "state");
            return this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("STATE <=", value, "state");
            return this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("STATE like", value, "state");
            return this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("STATE not like", value, "state");
            return this;
        }

        public Criteria andStateIn(List values) {
            addCriterion("STATE in", values, "state");
            return this;
        }

        public Criteria andStateNotIn(List values) {
            addCriterion("STATE not in", values, "state");
            return this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("STATE between", value1, value2, "state");
            return this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("STATE not between", value1, value2, "state");
            return this;
        }

        public Criteria andCardTypeIsNull() {
            addCriterion("CARD_TYPE is null");
            return this;
        }

        public Criteria andCardTypeIsNotNull() {
            addCriterion("CARD_TYPE is not null");
            return this;
        }

        public Criteria andCardTypeEqualTo(String value) {
            addCriterion("CARD_TYPE =", value, "cardType");
            return this;
        }

        public Criteria andCardTypeNotEqualTo(String value) {
            addCriterion("CARD_TYPE <>", value, "cardType");
            return this;
        }

        public Criteria andCardTypeGreaterThan(String value) {
            addCriterion("CARD_TYPE >", value, "cardType");
            return this;
        }

        public Criteria andCardTypeGreaterThanOrEqualTo(String value) {
            addCriterion("CARD_TYPE >=", value, "cardType");
            return this;
        }

        public Criteria andCardTypeLessThan(String value) {
            addCriterion("CARD_TYPE <", value, "cardType");
            return this;
        }

        public Criteria andCardTypeLessThanOrEqualTo(String value) {
            addCriterion("CARD_TYPE <=", value, "cardType");
            return this;
        }

        public Criteria andCardTypeLike(String value) {
            addCriterion("CARD_TYPE like", value, "cardType");
            return this;
        }

        public Criteria andCardTypeNotLike(String value) {
            addCriterion("CARD_TYPE not like", value, "cardType");
            return this;
        }

        public Criteria andCardTypeIn(List values) {
            addCriterion("CARD_TYPE in", values, "cardType");
            return this;
        }

        public Criteria andCardTypeNotIn(List values) {
            addCriterion("CARD_TYPE not in", values, "cardType");
            return this;
        }

        public Criteria andCardTypeBetween(String value1, String value2) {
            addCriterion("CARD_TYPE between", value1, value2, "cardType");
            return this;
        }

        public Criteria andCardTypeNotBetween(String value1, String value2) {
            addCriterion("CARD_TYPE not between", value1, value2, "cardType");
            return this;
        }

        public Criteria andOwnOrgIsNull() {
            addCriterion("OWN_ORG is null");
            return this;
        }

        public Criteria andOwnOrgIsNotNull() {
            addCriterion("OWN_ORG is not null");
            return this;
        }

        public Criteria andOwnOrgEqualTo(String value) {
            addCriterion("OWN_ORG =", value, "ownOrg");
            return this;
        }

        public Criteria andOwnOrgNotEqualTo(String value) {
            addCriterion("OWN_ORG <>", value, "ownOrg");
            return this;
        }

        public Criteria andOwnOrgGreaterThan(String value) {
            addCriterion("OWN_ORG >", value, "ownOrg");
            return this;
        }

        public Criteria andOwnOrgGreaterThanOrEqualTo(String value) {
            addCriterion("OWN_ORG >=", value, "ownOrg");
            return this;
        }

        public Criteria andOwnOrgLessThan(String value) {
            addCriterion("OWN_ORG <", value, "ownOrg");
            return this;
        }

        public Criteria andOwnOrgLessThanOrEqualTo(String value) {
            addCriterion("OWN_ORG <=", value, "ownOrg");
            return this;
        }

        public Criteria andOwnOrgLike(String value) {
            addCriterion("OWN_ORG like", value, "ownOrg");
            return this;
        }

        public Criteria andOwnOrgNotLike(String value) {
            addCriterion("OWN_ORG not like", value, "ownOrg");
            return this;
        }

        public Criteria andOwnOrgIn(List values) {
            addCriterion("OWN_ORG in", values, "ownOrg");
            return this;
        }

        public Criteria andOwnOrgNotIn(List values) {
            addCriterion("OWN_ORG not in", values, "ownOrg");
            return this;
        }

        public Criteria andOwnOrgBetween(String value1, String value2) {
            addCriterion("OWN_ORG between", value1, value2, "ownOrg");
            return this;
        }

        public Criteria andOwnOrgNotBetween(String value1, String value2) {
            addCriterion("OWN_ORG not between", value1, value2, "ownOrg");
            return this;
        }

        public Criteria andAccountIdIsNull() {
            addCriterion("ACCOUNT_ID is null");
            return this;
        }

        public Criteria andAccountIdIsNotNull() {
            addCriterion("ACCOUNT_ID is not null");
            return this;
        }

        public Criteria andAccountIdEqualTo(String value) {
            addCriterion("ACCOUNT_ID =", value, "accountId");
            return this;
        }

        public Criteria andAccountIdNotEqualTo(String value) {
            addCriterion("ACCOUNT_ID <>", value, "accountId");
            return this;
        }

        public Criteria andAccountIdGreaterThan(String value) {
            addCriterion("ACCOUNT_ID >", value, "accountId");
            return this;
        }

        public Criteria andAccountIdGreaterThanOrEqualTo(String value) {
            addCriterion("ACCOUNT_ID >=", value, "accountId");
            return this;
        }

        public Criteria andAccountIdLessThan(String value) {
            addCriterion("ACCOUNT_ID <", value, "accountId");
            return this;
        }

        public Criteria andAccountIdLessThanOrEqualTo(String value) {
            addCriterion("ACCOUNT_ID <=", value, "accountId");
            return this;
        }

        public Criteria andAccountIdLike(String value) {
            addCriterion("ACCOUNT_ID like", value, "accountId");
            return this;
        }

        public Criteria andAccountIdNotLike(String value) {
            addCriterion("ACCOUNT_ID not like", value, "accountId");
            return this;
        }

        public Criteria andAccountIdIn(List values) {
            addCriterion("ACCOUNT_ID in", values, "accountId");
            return this;
        }

        public Criteria andAccountIdNotIn(List values) {
            addCriterion("ACCOUNT_ID not in", values, "accountId");
            return this;
        }

        public Criteria andAccountIdBetween(String value1, String value2) {
            addCriterion("ACCOUNT_ID between", value1, value2, "accountId");
            return this;
        }

        public Criteria andAccountIdNotBetween(String value1, String value2) {
            addCriterion("ACCOUNT_ID not between", value1, value2, "accountId");
            return this;
        }

        public Criteria andBalanceModifiedTimeIsNull() {
            addCriterion("BALANCE_MODIFIED_TIME is null");
            return this;
        }

        public Criteria andBalanceModifiedTimeIsNotNull() {
            addCriterion("BALANCE_MODIFIED_TIME is not null");
            return this;
        }

        public Criteria andBalanceModifiedTimeEqualTo(Long value) {
            addCriterion("BALANCE_MODIFIED_TIME =", value,
                    "balanceModifiedTime");
            return this;
        }

        public Criteria andBalanceModifiedTimeNotEqualTo(Long value) {
            addCriterion("BALANCE_MODIFIED_TIME <>", value,
                    "balanceModifiedTime");
            return this;
        }

        public Criteria andBalanceModifiedTimeGreaterThan(Long value) {
            addCriterion("BALANCE_MODIFIED_TIME >", value,
                    "balanceModifiedTime");
            return this;
        }

        public Criteria andBalanceModifiedTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("BALANCE_MODIFIED_TIME >=", value,
                    "balanceModifiedTime");
            return this;
        }

        public Criteria andBalanceModifiedTimeLessThan(Long value) {
            addCriterion("BALANCE_MODIFIED_TIME <", value,
                    "balanceModifiedTime");
            return this;
        }

        public Criteria andBalanceModifiedTimeLessThanOrEqualTo(Long value) {
            addCriterion("BALANCE_MODIFIED_TIME <=", value,
                    "balanceModifiedTime");
            return this;
        }

        public Criteria andBalanceModifiedTimeIn(List values) {
            addCriterion("BALANCE_MODIFIED_TIME in", values,
                    "balanceModifiedTime");
            return this;
        }

        public Criteria andBalanceModifiedTimeNotIn(List values) {
            addCriterion("BALANCE_MODIFIED_TIME not in", values,
                    "balanceModifiedTime");
            return this;
        }

        public Criteria andBalanceModifiedTimeBetween(Long value1, Long value2) {
            addCriterion("BALANCE_MODIFIED_TIME between", value1, value2,
                    "balanceModifiedTime");
            return this;
        }

        public Criteria andBalanceModifiedTimeNotBetween(Long value1,
                Long value2) {
            addCriterion("BALANCE_MODIFIED_TIME not between", value1, value2,
                    "balanceModifiedTime");
            return this;
        }

        public Criteria andCardAreaCodeIsNull() {
            addCriterion("CARD_AREA_CODE is null");
            return this;
        }

        public Criteria andCardAreaCodeIsNotNull() {
            addCriterion("CARD_AREA_CODE is not null");
            return this;
        }

        public Criteria andCardAreaCodeEqualTo(String value) {
            addCriterion("CARD_AREA_CODE =", value, "cardAreaCode");
            return this;
        }

        public Criteria andCardAreaCodeNotEqualTo(String value) {
            addCriterion("CARD_AREA_CODE <>", value, "cardAreaCode");
            return this;
        }

        public Criteria andCardAreaCodeGreaterThan(String value) {
            addCriterion("CARD_AREA_CODE >", value, "cardAreaCode");
            return this;
        }

        public Criteria andCardAreaCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CARD_AREA_CODE >=", value, "cardAreaCode");
            return this;
        }

        public Criteria andCardAreaCodeLessThan(String value) {
            addCriterion("CARD_AREA_CODE <", value, "cardAreaCode");
            return this;
        }

        public Criteria andCardAreaCodeLessThanOrEqualTo(String value) {
            addCriterion("CARD_AREA_CODE <=", value, "cardAreaCode");
            return this;
        }

        public Criteria andCardAreaCodeLike(String value) {
            addCriterion("CARD_AREA_CODE like", value, "cardAreaCode");
            return this;
        }

        public Criteria andCardAreaCodeNotLike(String value) {
            addCriterion("CARD_AREA_CODE not like", value, "cardAreaCode");
            return this;
        }

        public Criteria andCardAreaCodeIn(List values) {
            addCriterion("CARD_AREA_CODE in", values, "cardAreaCode");
            return this;
        }

        public Criteria andCardAreaCodeNotIn(List values) {
            addCriterion("CARD_AREA_CODE not in", values, "cardAreaCode");
            return this;
        }

        public Criteria andCardAreaCodeBetween(String value1, String value2) {
            addCriterion("CARD_AREA_CODE between", value1, value2,
                    "cardAreaCode");
            return this;
        }

        public Criteria andCardAreaCodeNotBetween(String value1, String value2) {
            addCriterion("CARD_AREA_CODE not between", value1, value2,
                    "cardAreaCode");
            return this;
        }

        public Criteria andCardAreaNameIsNull() {
            addCriterion("CARD_AREA_NAME is null");
            return this;
        }

        public Criteria andCardAreaNameIsNotNull() {
            addCriterion("CARD_AREA_NAME is not null");
            return this;
        }

        public Criteria andCardAreaNameEqualTo(String value) {
            addCriterion("CARD_AREA_NAME =", value, "cardAreaName");
            return this;
        }

        public Criteria andCardAreaNameNotEqualTo(String value) {
            addCriterion("CARD_AREA_NAME <>", value, "cardAreaName");
            return this;
        }

        public Criteria andCardAreaNameGreaterThan(String value) {
            addCriterion("CARD_AREA_NAME >", value, "cardAreaName");
            return this;
        }

        public Criteria andCardAreaNameGreaterThanOrEqualTo(String value) {
            addCriterion("CARD_AREA_NAME >=", value, "cardAreaName");
            return this;
        }

        public Criteria andCardAreaNameLessThan(String value) {
            addCriterion("CARD_AREA_NAME <", value, "cardAreaName");
            return this;
        }

        public Criteria andCardAreaNameLessThanOrEqualTo(String value) {
            addCriterion("CARD_AREA_NAME <=", value, "cardAreaName");
            return this;
        }

        public Criteria andCardAreaNameLike(String value) {
            addCriterion("CARD_AREA_NAME like", value, "cardAreaName");
            return this;
        }

        public Criteria andCardAreaNameNotLike(String value) {
            addCriterion("CARD_AREA_NAME not like", value, "cardAreaName");
            return this;
        }

        public Criteria andCardAreaNameIn(List values) {
            addCriterion("CARD_AREA_NAME in", values, "cardAreaName");
            return this;
        }

        public Criteria andCardAreaNameNotIn(List values) {
            addCriterion("CARD_AREA_NAME not in", values, "cardAreaName");
            return this;
        }

        public Criteria andCardAreaNameBetween(String value1, String value2) {
            addCriterion("CARD_AREA_NAME between", value1, value2,
                    "cardAreaName");
            return this;
        }

        public Criteria andCardAreaNameNotBetween(String value1, String value2) {
            addCriterion("CARD_AREA_NAME not between", value1, value2,
                    "cardAreaName");
            return this;
        }
    }
}