package com.ctfo.yppt.baseservice.card.beans;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ICCardApplyExampleExtended implements Serializable {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	protected List oredCriteria;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	protected String selectedField;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	protected int skipNum;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	protected int endNum;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	protected int limitNum;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	public ICCardApplyExampleExtended() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	protected ICCardApplyExampleExtended(ICCardApplyExampleExtended example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	public void setSelectedField(String selectedField) {
		this.selectedField = selectedField;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	public String getSelectedField() {
		return selectedField;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	public static String tableName() {
		return "TB_IC_CARD_APPLY";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	public static String daoInterface() {
		return "com.ctfo.yppt.baseservice.dao.card.ICCardApplyDAO";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	public void setSkipNum(int skipNum) {
		this.skipNum = skipNum;
		this.endNum = this.skipNum + this.limitNum + 1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	public int getSkipNum() {
		return this.skipNum;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	public void setEndNum(int endNum) {
		this.endNum = endNum;
		this.limitNum = this.endNum - this.skipNum - 1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	public int getEndNum() {
		return this.endNum;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	public void setLimitNum(int limitNum) {
		this.limitNum = limitNum;
		this.endNum = this.skipNum + this.limitNum + 1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	public int getLimitNum() {
		return this.limitNum;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table TB_IC_CARD_APPLY
	 * @abatorgenerated  Thu Feb 05 17:22:25 CST 2015
	 */
	public static class Criteria implements Serializable {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("ID =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("ID <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("ID >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("ID >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("ID <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("ID <=", value, "id");
			return this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("ID like", value, "id");
			return this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("ID not like", value, "id");
			return this;
		}

		public Criteria andIdIn(List values) {
			addCriterion("ID in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List values) {
			addCriterion("ID not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("ID between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("ID not between", value1, value2, "id");
			return this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("USER_ID is null");
			return this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("USER_ID is not null");
			return this;
		}

		public Criteria andUserIdEqualTo(String value) {
			addCriterion("USER_ID =", value, "userId");
			return this;
		}

		public Criteria andUserIdNotEqualTo(String value) {
			addCriterion("USER_ID <>", value, "userId");
			return this;
		}

		public Criteria andUserIdGreaterThan(String value) {
			addCriterion("USER_ID >", value, "userId");
			return this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("USER_ID >=", value, "userId");
			return this;
		}

		public Criteria andUserIdLessThan(String value) {
			addCriterion("USER_ID <", value, "userId");
			return this;
		}

		public Criteria andUserIdLessThanOrEqualTo(String value) {
			addCriterion("USER_ID <=", value, "userId");
			return this;
		}

		public Criteria andUserIdLike(String value) {
			addCriterion("USER_ID like", value, "userId");
			return this;
		}

		public Criteria andUserIdNotLike(String value) {
			addCriterion("USER_ID not like", value, "userId");
			return this;
		}

		public Criteria andUserIdIn(List values) {
			addCriterion("USER_ID in", values, "userId");
			return this;
		}

		public Criteria andUserIdNotIn(List values) {
			addCriterion("USER_ID not in", values, "userId");
			return this;
		}

		public Criteria andUserIdBetween(String value1, String value2) {
			addCriterion("USER_ID between", value1, value2, "userId");
			return this;
		}

		public Criteria andUserIdNotBetween(String value1, String value2) {
			addCriterion("USER_ID not between", value1, value2, "userId");
			return this;
		}

		public Criteria andOpenCardOrgCodeIsNull() {
			addCriterion("OPEN_CARD_ORG_CODE is null");
			return this;
		}

		public Criteria andOpenCardOrgCodeIsNotNull() {
			addCriterion("OPEN_CARD_ORG_CODE is not null");
			return this;
		}

		public Criteria andOpenCardOrgCodeEqualTo(String value) {
			addCriterion("OPEN_CARD_ORG_CODE =", value, "openCardOrgCode");
			return this;
		}

		public Criteria andOpenCardOrgCodeNotEqualTo(String value) {
			addCriterion("OPEN_CARD_ORG_CODE <>", value, "openCardOrgCode");
			return this;
		}

		public Criteria andOpenCardOrgCodeGreaterThan(String value) {
			addCriterion("OPEN_CARD_ORG_CODE >", value, "openCardOrgCode");
			return this;
		}

		public Criteria andOpenCardOrgCodeGreaterThanOrEqualTo(String value) {
			addCriterion("OPEN_CARD_ORG_CODE >=", value, "openCardOrgCode");
			return this;
		}

		public Criteria andOpenCardOrgCodeLessThan(String value) {
			addCriterion("OPEN_CARD_ORG_CODE <", value, "openCardOrgCode");
			return this;
		}

		public Criteria andOpenCardOrgCodeLessThanOrEqualTo(String value) {
			addCriterion("OPEN_CARD_ORG_CODE <=", value, "openCardOrgCode");
			return this;
		}

		public Criteria andOpenCardOrgCodeLike(String value) {
			addCriterion("OPEN_CARD_ORG_CODE like", value, "openCardOrgCode");
			return this;
		}

		public Criteria andOpenCardOrgCodeNotLike(String value) {
			addCriterion("OPEN_CARD_ORG_CODE not like", value,
					"openCardOrgCode");
			return this;
		}

		public Criteria andOpenCardOrgCodeIn(List values) {
			addCriterion("OPEN_CARD_ORG_CODE in", values, "openCardOrgCode");
			return this;
		}

		public Criteria andOpenCardOrgCodeNotIn(List values) {
			addCriterion("OPEN_CARD_ORG_CODE not in", values, "openCardOrgCode");
			return this;
		}

		public Criteria andOpenCardOrgCodeBetween(String value1, String value2) {
			addCriterion("OPEN_CARD_ORG_CODE between", value1, value2,
					"openCardOrgCode");
			return this;
		}

		public Criteria andOpenCardOrgCodeNotBetween(String value1,
				String value2) {
			addCriterion("OPEN_CARD_ORG_CODE not between", value1, value2,
					"openCardOrgCode");
			return this;
		}

		public Criteria andOpenCardProvinceIsNull() {
			addCriterion("OPEN_CARD_PROVINCE is null");
			return this;
		}

		public Criteria andOpenCardProvinceIsNotNull() {
			addCriterion("OPEN_CARD_PROVINCE is not null");
			return this;
		}

		public Criteria andOpenCardProvinceEqualTo(String value) {
			addCriterion("OPEN_CARD_PROVINCE =", value, "openCardProvince");
			return this;
		}

		public Criteria andOpenCardProvinceNotEqualTo(String value) {
			addCriterion("OPEN_CARD_PROVINCE <>", value, "openCardProvince");
			return this;
		}

		public Criteria andOpenCardProvinceGreaterThan(String value) {
			addCriterion("OPEN_CARD_PROVINCE >", value, "openCardProvince");
			return this;
		}

		public Criteria andOpenCardProvinceGreaterThanOrEqualTo(String value) {
			addCriterion("OPEN_CARD_PROVINCE >=", value, "openCardProvince");
			return this;
		}

		public Criteria andOpenCardProvinceLessThan(String value) {
			addCriterion("OPEN_CARD_PROVINCE <", value, "openCardProvince");
			return this;
		}

		public Criteria andOpenCardProvinceLessThanOrEqualTo(String value) {
			addCriterion("OPEN_CARD_PROVINCE <=", value, "openCardProvince");
			return this;
		}

		public Criteria andOpenCardProvinceLike(String value) {
			addCriterion("OPEN_CARD_PROVINCE like", value, "openCardProvince");
			return this;
		}

		public Criteria andOpenCardProvinceNotLike(String value) {
			addCriterion("OPEN_CARD_PROVINCE not like", value,
					"openCardProvince");
			return this;
		}

		public Criteria andOpenCardProvinceIn(List values) {
			addCriterion("OPEN_CARD_PROVINCE in", values, "openCardProvince");
			return this;
		}

		public Criteria andOpenCardProvinceNotIn(List values) {
			addCriterion("OPEN_CARD_PROVINCE not in", values,
					"openCardProvince");
			return this;
		}

		public Criteria andOpenCardProvinceBetween(String value1, String value2) {
			addCriterion("OPEN_CARD_PROVINCE between", value1, value2,
					"openCardProvince");
			return this;
		}

		public Criteria andOpenCardProvinceNotBetween(String value1,
				String value2) {
			addCriterion("OPEN_CARD_PROVINCE not between", value1, value2,
					"openCardProvince");
			return this;
		}

		public Criteria andOpenCardCityIsNull() {
			addCriterion("OPEN_CARD_CITY is null");
			return this;
		}

		public Criteria andOpenCardCityIsNotNull() {
			addCriterion("OPEN_CARD_CITY is not null");
			return this;
		}

		public Criteria andOpenCardCityEqualTo(String value) {
			addCriterion("OPEN_CARD_CITY =", value, "openCardCity");
			return this;
		}

		public Criteria andOpenCardCityNotEqualTo(String value) {
			addCriterion("OPEN_CARD_CITY <>", value, "openCardCity");
			return this;
		}

		public Criteria andOpenCardCityGreaterThan(String value) {
			addCriterion("OPEN_CARD_CITY >", value, "openCardCity");
			return this;
		}

		public Criteria andOpenCardCityGreaterThanOrEqualTo(String value) {
			addCriterion("OPEN_CARD_CITY >=", value, "openCardCity");
			return this;
		}

		public Criteria andOpenCardCityLessThan(String value) {
			addCriterion("OPEN_CARD_CITY <", value, "openCardCity");
			return this;
		}

		public Criteria andOpenCardCityLessThanOrEqualTo(String value) {
			addCriterion("OPEN_CARD_CITY <=", value, "openCardCity");
			return this;
		}

		public Criteria andOpenCardCityLike(String value) {
			addCriterion("OPEN_CARD_CITY like", value, "openCardCity");
			return this;
		}

		public Criteria andOpenCardCityNotLike(String value) {
			addCriterion("OPEN_CARD_CITY not like", value, "openCardCity");
			return this;
		}

		public Criteria andOpenCardCityIn(List values) {
			addCriterion("OPEN_CARD_CITY in", values, "openCardCity");
			return this;
		}

		public Criteria andOpenCardCityNotIn(List values) {
			addCriterion("OPEN_CARD_CITY not in", values, "openCardCity");
			return this;
		}

		public Criteria andOpenCardCityBetween(String value1, String value2) {
			addCriterion("OPEN_CARD_CITY between", value1, value2,
					"openCardCity");
			return this;
		}

		public Criteria andOpenCardCityNotBetween(String value1, String value2) {
			addCriterion("OPEN_CARD_CITY not between", value1, value2,
					"openCardCity");
			return this;
		}

		public Criteria andVehicleIdIsNull() {
			addCriterion("VEHICLE_ID is null");
			return this;
		}

		public Criteria andVehicleIdIsNotNull() {
			addCriterion("VEHICLE_ID is not null");
			return this;
		}

		public Criteria andVehicleIdEqualTo(String value) {
			addCriterion("VEHICLE_ID =", value, "vehicleId");
			return this;
		}

		public Criteria andVehicleIdNotEqualTo(String value) {
			addCriterion("VEHICLE_ID <>", value, "vehicleId");
			return this;
		}

		public Criteria andVehicleIdGreaterThan(String value) {
			addCriterion("VEHICLE_ID >", value, "vehicleId");
			return this;
		}

		public Criteria andVehicleIdGreaterThanOrEqualTo(String value) {
			addCriterion("VEHICLE_ID >=", value, "vehicleId");
			return this;
		}

		public Criteria andVehicleIdLessThan(String value) {
			addCriterion("VEHICLE_ID <", value, "vehicleId");
			return this;
		}

		public Criteria andVehicleIdLessThanOrEqualTo(String value) {
			addCriterion("VEHICLE_ID <=", value, "vehicleId");
			return this;
		}

		public Criteria andVehicleIdLike(String value) {
			addCriterion("VEHICLE_ID like", value, "vehicleId");
			return this;
		}

		public Criteria andVehicleIdNotLike(String value) {
			addCriterion("VEHICLE_ID not like", value, "vehicleId");
			return this;
		}

		public Criteria andVehicleIdIn(List values) {
			addCriterion("VEHICLE_ID in", values, "vehicleId");
			return this;
		}

		public Criteria andVehicleIdNotIn(List values) {
			addCriterion("VEHICLE_ID not in", values, "vehicleId");
			return this;
		}

		public Criteria andVehicleIdBetween(String value1, String value2) {
			addCriterion("VEHICLE_ID between", value1, value2, "vehicleId");
			return this;
		}

		public Criteria andVehicleIdNotBetween(String value1, String value2) {
			addCriterion("VEHICLE_ID not between", value1, value2, "vehicleId");
			return this;
		}

		public Criteria andReceiverAreaIdIsNull() {
			addCriterion("RECEIVER_AREA_ID is null");
			return this;
		}

		public Criteria andReceiverAreaIdIsNotNull() {
			addCriterion("RECEIVER_AREA_ID is not null");
			return this;
		}

		public Criteria andReceiverAreaIdEqualTo(String value) {
			addCriterion("RECEIVER_AREA_ID =", value, "receiverAreaId");
			return this;
		}

		public Criteria andReceiverAreaIdNotEqualTo(String value) {
			addCriterion("RECEIVER_AREA_ID <>", value, "receiverAreaId");
			return this;
		}

		public Criteria andReceiverAreaIdGreaterThan(String value) {
			addCriterion("RECEIVER_AREA_ID >", value, "receiverAreaId");
			return this;
		}

		public Criteria andReceiverAreaIdGreaterThanOrEqualTo(String value) {
			addCriterion("RECEIVER_AREA_ID >=", value, "receiverAreaId");
			return this;
		}

		public Criteria andReceiverAreaIdLessThan(String value) {
			addCriterion("RECEIVER_AREA_ID <", value, "receiverAreaId");
			return this;
		}

		public Criteria andReceiverAreaIdLessThanOrEqualTo(String value) {
			addCriterion("RECEIVER_AREA_ID <=", value, "receiverAreaId");
			return this;
		}

		public Criteria andReceiverAreaIdLike(String value) {
			addCriterion("RECEIVER_AREA_ID like", value, "receiverAreaId");
			return this;
		}

		public Criteria andReceiverAreaIdNotLike(String value) {
			addCriterion("RECEIVER_AREA_ID not like", value, "receiverAreaId");
			return this;
		}

		public Criteria andReceiverAreaIdIn(List values) {
			addCriterion("RECEIVER_AREA_ID in", values, "receiverAreaId");
			return this;
		}

		public Criteria andReceiverAreaIdNotIn(List values) {
			addCriterion("RECEIVER_AREA_ID not in", values, "receiverAreaId");
			return this;
		}

		public Criteria andReceiverAreaIdBetween(String value1, String value2) {
			addCriterion("RECEIVER_AREA_ID between", value1, value2,
					"receiverAreaId");
			return this;
		}

		public Criteria andReceiverAreaIdNotBetween(String value1, String value2) {
			addCriterion("RECEIVER_AREA_ID not between", value1, value2,
					"receiverAreaId");
			return this;
		}

		public Criteria andReceiverPhoneNumIsNull() {
			addCriterion("RECEIVER_PHONE_NUM is null");
			return this;
		}

		public Criteria andReceiverPhoneNumIsNotNull() {
			addCriterion("RECEIVER_PHONE_NUM is not null");
			return this;
		}

		public Criteria andReceiverPhoneNumEqualTo(String value) {
			addCriterion("RECEIVER_PHONE_NUM =", value, "receiverPhoneNum");
			return this;
		}

		public Criteria andReceiverPhoneNumNotEqualTo(String value) {
			addCriterion("RECEIVER_PHONE_NUM <>", value, "receiverPhoneNum");
			return this;
		}

		public Criteria andReceiverPhoneNumGreaterThan(String value) {
			addCriterion("RECEIVER_PHONE_NUM >", value, "receiverPhoneNum");
			return this;
		}

		public Criteria andReceiverPhoneNumGreaterThanOrEqualTo(String value) {
			addCriterion("RECEIVER_PHONE_NUM >=", value, "receiverPhoneNum");
			return this;
		}

		public Criteria andReceiverPhoneNumLessThan(String value) {
			addCriterion("RECEIVER_PHONE_NUM <", value, "receiverPhoneNum");
			return this;
		}

		public Criteria andReceiverPhoneNumLessThanOrEqualTo(String value) {
			addCriterion("RECEIVER_PHONE_NUM <=", value, "receiverPhoneNum");
			return this;
		}

		public Criteria andReceiverPhoneNumLike(String value) {
			addCriterion("RECEIVER_PHONE_NUM like", value, "receiverPhoneNum");
			return this;
		}

		public Criteria andReceiverPhoneNumNotLike(String value) {
			addCriterion("RECEIVER_PHONE_NUM not like", value,
					"receiverPhoneNum");
			return this;
		}

		public Criteria andReceiverPhoneNumIn(List values) {
			addCriterion("RECEIVER_PHONE_NUM in", values, "receiverPhoneNum");
			return this;
		}

		public Criteria andReceiverPhoneNumNotIn(List values) {
			addCriterion("RECEIVER_PHONE_NUM not in", values,
					"receiverPhoneNum");
			return this;
		}

		public Criteria andReceiverPhoneNumBetween(String value1, String value2) {
			addCriterion("RECEIVER_PHONE_NUM between", value1, value2,
					"receiverPhoneNum");
			return this;
		}

		public Criteria andReceiverPhoneNumNotBetween(String value1,
				String value2) {
			addCriterion("RECEIVER_PHONE_NUM not between", value1, value2,
					"receiverPhoneNum");
			return this;
		}

		public Criteria andReceiverNameIsNull() {
			addCriterion("RECEIVER_NAME is null");
			return this;
		}

		public Criteria andReceiverNameIsNotNull() {
			addCriterion("RECEIVER_NAME is not null");
			return this;
		}

		public Criteria andReceiverNameEqualTo(String value) {
			addCriterion("RECEIVER_NAME =", value, "receiverName");
			return this;
		}

		public Criteria andReceiverNameNotEqualTo(String value) {
			addCriterion("RECEIVER_NAME <>", value, "receiverName");
			return this;
		}

		public Criteria andReceiverNameGreaterThan(String value) {
			addCriterion("RECEIVER_NAME >", value, "receiverName");
			return this;
		}

		public Criteria andReceiverNameGreaterThanOrEqualTo(String value) {
			addCriterion("RECEIVER_NAME >=", value, "receiverName");
			return this;
		}

		public Criteria andReceiverNameLessThan(String value) {
			addCriterion("RECEIVER_NAME <", value, "receiverName");
			return this;
		}

		public Criteria andReceiverNameLessThanOrEqualTo(String value) {
			addCriterion("RECEIVER_NAME <=", value, "receiverName");
			return this;
		}

		public Criteria andReceiverNameLike(String value) {
			addCriterion("RECEIVER_NAME like", value, "receiverName");
			return this;
		}

		public Criteria andReceiverNameNotLike(String value) {
			addCriterion("RECEIVER_NAME not like", value, "receiverName");
			return this;
		}

		public Criteria andReceiverNameIn(List values) {
			addCriterion("RECEIVER_NAME in", values, "receiverName");
			return this;
		}

		public Criteria andReceiverNameNotIn(List values) {
			addCriterion("RECEIVER_NAME not in", values, "receiverName");
			return this;
		}

		public Criteria andReceiverNameBetween(String value1, String value2) {
			addCriterion("RECEIVER_NAME between", value1, value2,
					"receiverName");
			return this;
		}

		public Criteria andReceiverNameNotBetween(String value1, String value2) {
			addCriterion("RECEIVER_NAME not between", value1, value2,
					"receiverName");
			return this;
		}

		public Criteria andProvinceIsNull() {
			addCriterion("PROVINCE is null");
			return this;
		}

		public Criteria andProvinceIsNotNull() {
			addCriterion("PROVINCE is not null");
			return this;
		}

		public Criteria andProvinceEqualTo(String value) {
			addCriterion("PROVINCE =", value, "province");
			return this;
		}

		public Criteria andProvinceNotEqualTo(String value) {
			addCriterion("PROVINCE <>", value, "province");
			return this;
		}

		public Criteria andProvinceGreaterThan(String value) {
			addCriterion("PROVINCE >", value, "province");
			return this;
		}

		public Criteria andProvinceGreaterThanOrEqualTo(String value) {
			addCriterion("PROVINCE >=", value, "province");
			return this;
		}

		public Criteria andProvinceLessThan(String value) {
			addCriterion("PROVINCE <", value, "province");
			return this;
		}

		public Criteria andProvinceLessThanOrEqualTo(String value) {
			addCriterion("PROVINCE <=", value, "province");
			return this;
		}

		public Criteria andProvinceLike(String value) {
			addCriterion("PROVINCE like", value, "province");
			return this;
		}

		public Criteria andProvinceNotLike(String value) {
			addCriterion("PROVINCE not like", value, "province");
			return this;
		}

		public Criteria andProvinceIn(List values) {
			addCriterion("PROVINCE in", values, "province");
			return this;
		}

		public Criteria andProvinceNotIn(List values) {
			addCriterion("PROVINCE not in", values, "province");
			return this;
		}

		public Criteria andProvinceBetween(String value1, String value2) {
			addCriterion("PROVINCE between", value1, value2, "province");
			return this;
		}

		public Criteria andProvinceNotBetween(String value1, String value2) {
			addCriterion("PROVINCE not between", value1, value2, "province");
			return this;
		}

		public Criteria andCityIsNull() {
			addCriterion("CITY is null");
			return this;
		}

		public Criteria andCityIsNotNull() {
			addCriterion("CITY is not null");
			return this;
		}

		public Criteria andCityEqualTo(String value) {
			addCriterion("CITY =", value, "city");
			return this;
		}

		public Criteria andCityNotEqualTo(String value) {
			addCriterion("CITY <>", value, "city");
			return this;
		}

		public Criteria andCityGreaterThan(String value) {
			addCriterion("CITY >", value, "city");
			return this;
		}

		public Criteria andCityGreaterThanOrEqualTo(String value) {
			addCriterion("CITY >=", value, "city");
			return this;
		}

		public Criteria andCityLessThan(String value) {
			addCriterion("CITY <", value, "city");
			return this;
		}

		public Criteria andCityLessThanOrEqualTo(String value) {
			addCriterion("CITY <=", value, "city");
			return this;
		}

		public Criteria andCityLike(String value) {
			addCriterion("CITY like", value, "city");
			return this;
		}

		public Criteria andCityNotLike(String value) {
			addCriterion("CITY not like", value, "city");
			return this;
		}

		public Criteria andCityIn(List values) {
			addCriterion("CITY in", values, "city");
			return this;
		}

		public Criteria andCityNotIn(List values) {
			addCriterion("CITY not in", values, "city");
			return this;
		}

		public Criteria andCityBetween(String value1, String value2) {
			addCriterion("CITY between", value1, value2, "city");
			return this;
		}

		public Criteria andCityNotBetween(String value1, String value2) {
			addCriterion("CITY not between", value1, value2, "city");
			return this;
		}

		public Criteria andDistrictIsNull() {
			addCriterion("DISTRICT is null");
			return this;
		}

		public Criteria andDistrictIsNotNull() {
			addCriterion("DISTRICT is not null");
			return this;
		}

		public Criteria andDistrictEqualTo(String value) {
			addCriterion("DISTRICT =", value, "district");
			return this;
		}

		public Criteria andDistrictNotEqualTo(String value) {
			addCriterion("DISTRICT <>", value, "district");
			return this;
		}

		public Criteria andDistrictGreaterThan(String value) {
			addCriterion("DISTRICT >", value, "district");
			return this;
		}

		public Criteria andDistrictGreaterThanOrEqualTo(String value) {
			addCriterion("DISTRICT >=", value, "district");
			return this;
		}

		public Criteria andDistrictLessThan(String value) {
			addCriterion("DISTRICT <", value, "district");
			return this;
		}

		public Criteria andDistrictLessThanOrEqualTo(String value) {
			addCriterion("DISTRICT <=", value, "district");
			return this;
		}

		public Criteria andDistrictLike(String value) {
			addCriterion("DISTRICT like", value, "district");
			return this;
		}

		public Criteria andDistrictNotLike(String value) {
			addCriterion("DISTRICT not like", value, "district");
			return this;
		}

		public Criteria andDistrictIn(List values) {
			addCriterion("DISTRICT in", values, "district");
			return this;
		}

		public Criteria andDistrictNotIn(List values) {
			addCriterion("DISTRICT not in", values, "district");
			return this;
		}

		public Criteria andDistrictBetween(String value1, String value2) {
			addCriterion("DISTRICT between", value1, value2, "district");
			return this;
		}

		public Criteria andDistrictNotBetween(String value1, String value2) {
			addCriterion("DISTRICT not between", value1, value2, "district");
			return this;
		}

		public Criteria andAddressIsNull() {
			addCriterion("ADDRESS is null");
			return this;
		}

		public Criteria andAddressIsNotNull() {
			addCriterion("ADDRESS is not null");
			return this;
		}

		public Criteria andAddressEqualTo(String value) {
			addCriterion("ADDRESS =", value, "address");
			return this;
		}

		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("ADDRESS <>", value, "address");
			return this;
		}

		public Criteria andAddressGreaterThan(String value) {
			addCriterion("ADDRESS >", value, "address");
			return this;
		}

		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("ADDRESS >=", value, "address");
			return this;
		}

		public Criteria andAddressLessThan(String value) {
			addCriterion("ADDRESS <", value, "address");
			return this;
		}

		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("ADDRESS <=", value, "address");
			return this;
		}

		public Criteria andAddressLike(String value) {
			addCriterion("ADDRESS like", value, "address");
			return this;
		}

		public Criteria andAddressNotLike(String value) {
			addCriterion("ADDRESS not like", value, "address");
			return this;
		}

		public Criteria andAddressIn(List values) {
			addCriterion("ADDRESS in", values, "address");
			return this;
		}

		public Criteria andAddressNotIn(List values) {
			addCriterion("ADDRESS not in", values, "address");
			return this;
		}

		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("ADDRESS between", value1, value2, "address");
			return this;
		}

		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("ADDRESS not between", value1, value2, "address");
			return this;
		}

		public Criteria andZipCodeIsNull() {
			addCriterion("ZIP_CODE is null");
			return this;
		}

		public Criteria andZipCodeIsNotNull() {
			addCriterion("ZIP_CODE is not null");
			return this;
		}

		public Criteria andZipCodeEqualTo(String value) {
			addCriterion("ZIP_CODE =", value, "zipCode");
			return this;
		}

		public Criteria andZipCodeNotEqualTo(String value) {
			addCriterion("ZIP_CODE <>", value, "zipCode");
			return this;
		}

		public Criteria andZipCodeGreaterThan(String value) {
			addCriterion("ZIP_CODE >", value, "zipCode");
			return this;
		}

		public Criteria andZipCodeGreaterThanOrEqualTo(String value) {
			addCriterion("ZIP_CODE >=", value, "zipCode");
			return this;
		}

		public Criteria andZipCodeLessThan(String value) {
			addCriterion("ZIP_CODE <", value, "zipCode");
			return this;
		}

		public Criteria andZipCodeLessThanOrEqualTo(String value) {
			addCriterion("ZIP_CODE <=", value, "zipCode");
			return this;
		}

		public Criteria andZipCodeLike(String value) {
			addCriterion("ZIP_CODE like", value, "zipCode");
			return this;
		}

		public Criteria andZipCodeNotLike(String value) {
			addCriterion("ZIP_CODE not like", value, "zipCode");
			return this;
		}

		public Criteria andZipCodeIn(List values) {
			addCriterion("ZIP_CODE in", values, "zipCode");
			return this;
		}

		public Criteria andZipCodeNotIn(List values) {
			addCriterion("ZIP_CODE not in", values, "zipCode");
			return this;
		}

		public Criteria andZipCodeBetween(String value1, String value2) {
			addCriterion("ZIP_CODE between", value1, value2, "zipCode");
			return this;
		}

		public Criteria andZipCodeNotBetween(String value1, String value2) {
			addCriterion("ZIP_CODE not between", value1, value2, "zipCode");
			return this;
		}

		public Criteria andDataSourceIsNull() {
			addCriterion("DATA_SOURCE is null");
			return this;
		}

		public Criteria andDataSourceIsNotNull() {
			addCriterion("DATA_SOURCE is not null");
			return this;
		}

		public Criteria andDataSourceEqualTo(String value) {
			addCriterion("DATA_SOURCE =", value, "dataSource");
			return this;
		}

		public Criteria andDataSourceNotEqualTo(String value) {
			addCriterion("DATA_SOURCE <>", value, "dataSource");
			return this;
		}

		public Criteria andDataSourceGreaterThan(String value) {
			addCriterion("DATA_SOURCE >", value, "dataSource");
			return this;
		}

		public Criteria andDataSourceGreaterThanOrEqualTo(String value) {
			addCriterion("DATA_SOURCE >=", value, "dataSource");
			return this;
		}

		public Criteria andDataSourceLessThan(String value) {
			addCriterion("DATA_SOURCE <", value, "dataSource");
			return this;
		}

		public Criteria andDataSourceLessThanOrEqualTo(String value) {
			addCriterion("DATA_SOURCE <=", value, "dataSource");
			return this;
		}

		public Criteria andDataSourceLike(String value) {
			addCriterion("DATA_SOURCE like", value, "dataSource");
			return this;
		}

		public Criteria andDataSourceNotLike(String value) {
			addCriterion("DATA_SOURCE not like", value, "dataSource");
			return this;
		}

		public Criteria andDataSourceIn(List values) {
			addCriterion("DATA_SOURCE in", values, "dataSource");
			return this;
		}

		public Criteria andDataSourceNotIn(List values) {
			addCriterion("DATA_SOURCE not in", values, "dataSource");
			return this;
		}

		public Criteria andDataSourceBetween(String value1, String value2) {
			addCriterion("DATA_SOURCE between", value1, value2, "dataSource");
			return this;
		}

		public Criteria andDataSourceNotBetween(String value1, String value2) {
			addCriterion("DATA_SOURCE not between", value1, value2,
					"dataSource");
			return this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("STATUS =", value, "status");
			return this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("STATUS <>", value, "status");
			return this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("STATUS >", value, "status");
			return this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("STATUS >=", value, "status");
			return this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("STATUS <", value, "status");
			return this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("STATUS <=", value, "status");
			return this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("STATUS like", value, "status");
			return this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("STATUS not like", value, "status");
			return this;
		}

		public Criteria andStatusIn(List values) {
			addCriterion("STATUS in", values, "status");
			return this;
		}

		public Criteria andStatusNotIn(List values) {
			addCriterion("STATUS not in", values, "status");
			return this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("CREATE_TIME is null");
			return this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("CREATE_TIME is not null");
			return this;
		}

		public Criteria andCreateTimeEqualTo(Long value) {
			addCriterion("CREATE_TIME =", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotEqualTo(Long value) {
			addCriterion("CREATE_TIME <>", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeGreaterThan(Long value) {
			addCriterion("CREATE_TIME >", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Long value) {
			addCriterion("CREATE_TIME >=", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeLessThan(Long value) {
			addCriterion("CREATE_TIME <", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Long value) {
			addCriterion("CREATE_TIME <=", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeIn(List values) {
			addCriterion("CREATE_TIME in", values, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotIn(List values) {
			addCriterion("CREATE_TIME not in", values, "createTime");
			return this;
		}

		public Criteria andCreateTimeBetween(Long value1, Long value2) {
			addCriterion("CREATE_TIME between", value1, value2, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotBetween(Long value1, Long value2) {
			addCriterion("CREATE_TIME not between", value1, value2,
					"createTime");
			return this;
		}

		public Criteria andModifyTimeIsNull() {
			addCriterion("MODIFY_TIME is null");
			return this;
		}

		public Criteria andModifyTimeIsNotNull() {
			addCriterion("MODIFY_TIME is not null");
			return this;
		}

		public Criteria andModifyTimeEqualTo(Long value) {
			addCriterion("MODIFY_TIME =", value, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeNotEqualTo(Long value) {
			addCriterion("MODIFY_TIME <>", value, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeGreaterThan(Long value) {
			addCriterion("MODIFY_TIME >", value, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeGreaterThanOrEqualTo(Long value) {
			addCriterion("MODIFY_TIME >=", value, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeLessThan(Long value) {
			addCriterion("MODIFY_TIME <", value, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeLessThanOrEqualTo(Long value) {
			addCriterion("MODIFY_TIME <=", value, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeIn(List values) {
			addCriterion("MODIFY_TIME in", values, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeNotIn(List values) {
			addCriterion("MODIFY_TIME not in", values, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeBetween(Long value1, Long value2) {
			addCriterion("MODIFY_TIME between", value1, value2, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeNotBetween(Long value1, Long value2) {
			addCriterion("MODIFY_TIME not between", value1, value2,
					"modifyTime");
			return this;
		}

		public Criteria andCreatorIsNull() {
			addCriterion("CREATOR is null");
			return this;
		}

		public Criteria andCreatorIsNotNull() {
			addCriterion("CREATOR is not null");
			return this;
		}

		public Criteria andCreatorEqualTo(String value) {
			addCriterion("CREATOR =", value, "creator");
			return this;
		}

		public Criteria andCreatorNotEqualTo(String value) {
			addCriterion("CREATOR <>", value, "creator");
			return this;
		}

		public Criteria andCreatorGreaterThan(String value) {
			addCriterion("CREATOR >", value, "creator");
			return this;
		}

		public Criteria andCreatorGreaterThanOrEqualTo(String value) {
			addCriterion("CREATOR >=", value, "creator");
			return this;
		}

		public Criteria andCreatorLessThan(String value) {
			addCriterion("CREATOR <", value, "creator");
			return this;
		}

		public Criteria andCreatorLessThanOrEqualTo(String value) {
			addCriterion("CREATOR <=", value, "creator");
			return this;
		}

		public Criteria andCreatorLike(String value) {
			addCriterion("CREATOR like", value, "creator");
			return this;
		}

		public Criteria andCreatorNotLike(String value) {
			addCriterion("CREATOR not like", value, "creator");
			return this;
		}

		public Criteria andCreatorIn(List values) {
			addCriterion("CREATOR in", values, "creator");
			return this;
		}

		public Criteria andCreatorNotIn(List values) {
			addCriterion("CREATOR not in", values, "creator");
			return this;
		}

		public Criteria andCreatorBetween(String value1, String value2) {
			addCriterion("CREATOR between", value1, value2, "creator");
			return this;
		}

		public Criteria andCreatorNotBetween(String value1, String value2) {
			addCriterion("CREATOR not between", value1, value2, "creator");
			return this;
		}

		public Criteria andModifierIsNull() {
			addCriterion("MODIFIER is null");
			return this;
		}

		public Criteria andModifierIsNotNull() {
			addCriterion("MODIFIER is not null");
			return this;
		}

		public Criteria andModifierEqualTo(String value) {
			addCriterion("MODIFIER =", value, "modifier");
			return this;
		}

		public Criteria andModifierNotEqualTo(String value) {
			addCriterion("MODIFIER <>", value, "modifier");
			return this;
		}

		public Criteria andModifierGreaterThan(String value) {
			addCriterion("MODIFIER >", value, "modifier");
			return this;
		}

		public Criteria andModifierGreaterThanOrEqualTo(String value) {
			addCriterion("MODIFIER >=", value, "modifier");
			return this;
		}

		public Criteria andModifierLessThan(String value) {
			addCriterion("MODIFIER <", value, "modifier");
			return this;
		}

		public Criteria andModifierLessThanOrEqualTo(String value) {
			addCriterion("MODIFIER <=", value, "modifier");
			return this;
		}

		public Criteria andModifierLike(String value) {
			addCriterion("MODIFIER like", value, "modifier");
			return this;
		}

		public Criteria andModifierNotLike(String value) {
			addCriterion("MODIFIER not like", value, "modifier");
			return this;
		}

		public Criteria andModifierIn(List values) {
			addCriterion("MODIFIER in", values, "modifier");
			return this;
		}

		public Criteria andModifierNotIn(List values) {
			addCriterion("MODIFIER not in", values, "modifier");
			return this;
		}

		public Criteria andModifierBetween(String value1, String value2) {
			addCriterion("MODIFIER between", value1, value2, "modifier");
			return this;
		}

		public Criteria andModifierNotBetween(String value1, String value2) {
			addCriterion("MODIFIER not between", value1, value2, "modifier");
			return this;
		}

		public Criteria andModifierNameIsNull() {
			addCriterion("MODIFIER_NAME is null");
			return this;
		}

		public Criteria andModifierNameIsNotNull() {
			addCriterion("MODIFIER_NAME is not null");
			return this;
		}

		public Criteria andModifierNameEqualTo(String value) {
			addCriterion("MODIFIER_NAME =", value, "modifierName");
			return this;
		}

		public Criteria andModifierNameNotEqualTo(String value) {
			addCriterion("MODIFIER_NAME <>", value, "modifierName");
			return this;
		}

		public Criteria andModifierNameGreaterThan(String value) {
			addCriterion("MODIFIER_NAME >", value, "modifierName");
			return this;
		}

		public Criteria andModifierNameGreaterThanOrEqualTo(String value) {
			addCriterion("MODIFIER_NAME >=", value, "modifierName");
			return this;
		}

		public Criteria andModifierNameLessThan(String value) {
			addCriterion("MODIFIER_NAME <", value, "modifierName");
			return this;
		}

		public Criteria andModifierNameLessThanOrEqualTo(String value) {
			addCriterion("MODIFIER_NAME <=", value, "modifierName");
			return this;
		}

		public Criteria andModifierNameLike(String value) {
			addCriterion("MODIFIER_NAME like", value, "modifierName");
			return this;
		}

		public Criteria andModifierNameNotLike(String value) {
			addCriterion("MODIFIER_NAME not like", value, "modifierName");
			return this;
		}

		public Criteria andModifierNameIn(List values) {
			addCriterion("MODIFIER_NAME in", values, "modifierName");
			return this;
		}

		public Criteria andModifierNameNotIn(List values) {
			addCriterion("MODIFIER_NAME not in", values, "modifierName");
			return this;
		}

		public Criteria andModifierNameBetween(String value1, String value2) {
			addCriterion("MODIFIER_NAME between", value1, value2,
					"modifierName");
			return this;
		}

		public Criteria andModifierNameNotBetween(String value1, String value2) {
			addCriterion("MODIFIER_NAME not between", value1, value2,
					"modifierName");
			return this;
		}

		public Criteria andMarkIsNull() {
			addCriterion("MARK is null");
			return this;
		}

		public Criteria andMarkIsNotNull() {
			addCriterion("MARK is not null");
			return this;
		}

		public Criteria andMarkEqualTo(String value) {
			addCriterion("MARK =", value, "mark");
			return this;
		}

		public Criteria andMarkNotEqualTo(String value) {
			addCriterion("MARK <>", value, "mark");
			return this;
		}

		public Criteria andMarkGreaterThan(String value) {
			addCriterion("MARK >", value, "mark");
			return this;
		}

		public Criteria andMarkGreaterThanOrEqualTo(String value) {
			addCriterion("MARK >=", value, "mark");
			return this;
		}

		public Criteria andMarkLessThan(String value) {
			addCriterion("MARK <", value, "mark");
			return this;
		}

		public Criteria andMarkLessThanOrEqualTo(String value) {
			addCriterion("MARK <=", value, "mark");
			return this;
		}

		public Criteria andMarkLike(String value) {
			addCriterion("MARK like", value, "mark");
			return this;
		}

		public Criteria andMarkNotLike(String value) {
			addCriterion("MARK not like", value, "mark");
			return this;
		}

		public Criteria andMarkIn(List values) {
			addCriterion("MARK in", values, "mark");
			return this;
		}

		public Criteria andMarkNotIn(List values) {
			addCriterion("MARK not in", values, "mark");
			return this;
		}

		public Criteria andMarkBetween(String value1, String value2) {
			addCriterion("MARK between", value1, value2, "mark");
			return this;
		}

		public Criteria andMarkNotBetween(String value1, String value2) {
			addCriterion("MARK not between", value1, value2, "mark");
			return this;
		}

		public Criteria andUserTypeIsNull() {
			addCriterion("USER_TYPE is null");
			return this;
		}

		public Criteria andUserTypeIsNotNull() {
			addCriterion("USER_TYPE is not null");
			return this;
		}

		public Criteria andUserTypeEqualTo(String value) {
			addCriterion("USER_TYPE =", value, "userType");
			return this;
		}

		public Criteria andUserTypeNotEqualTo(String value) {
			addCriterion("USER_TYPE <>", value, "userType");
			return this;
		}

		public Criteria andUserTypeGreaterThan(String value) {
			addCriterion("USER_TYPE >", value, "userType");
			return this;
		}

		public Criteria andUserTypeGreaterThanOrEqualTo(String value) {
			addCriterion("USER_TYPE >=", value, "userType");
			return this;
		}

		public Criteria andUserTypeLessThan(String value) {
			addCriterion("USER_TYPE <", value, "userType");
			return this;
		}

		public Criteria andUserTypeLessThanOrEqualTo(String value) {
			addCriterion("USER_TYPE <=", value, "userType");
			return this;
		}

		public Criteria andUserTypeLike(String value) {
			addCriterion("USER_TYPE like", value, "userType");
			return this;
		}

		public Criteria andUserTypeNotLike(String value) {
			addCriterion("USER_TYPE not like", value, "userType");
			return this;
		}

		public Criteria andUserTypeIn(List values) {
			addCriterion("USER_TYPE in", values, "userType");
			return this;
		}

		public Criteria andUserTypeNotIn(List values) {
			addCriterion("USER_TYPE not in", values, "userType");
			return this;
		}

		public Criteria andUserTypeBetween(String value1, String value2) {
			addCriterion("USER_TYPE between", value1, value2, "userType");
			return this;
		}

		public Criteria andUserTypeNotBetween(String value1, String value2) {
			addCriterion("USER_TYPE not between", value1, value2, "userType");
			return this;
		}

		public Criteria andUserNameIsNull() {
			addCriterion("USER_NAME is null");
			return this;
		}

		public Criteria andUserNameIsNotNull() {
			addCriterion("USER_NAME is not null");
			return this;
		}

		public Criteria andUserNameEqualTo(String value) {
			addCriterion("USER_NAME =", value, "userName");
			return this;
		}

		public Criteria andUserNameNotEqualTo(String value) {
			addCriterion("USER_NAME <>", value, "userName");
			return this;
		}

		public Criteria andUserNameGreaterThan(String value) {
			addCriterion("USER_NAME >", value, "userName");
			return this;
		}

		public Criteria andUserNameGreaterThanOrEqualTo(String value) {
			addCriterion("USER_NAME >=", value, "userName");
			return this;
		}

		public Criteria andUserNameLessThan(String value) {
			addCriterion("USER_NAME <", value, "userName");
			return this;
		}

		public Criteria andUserNameLessThanOrEqualTo(String value) {
			addCriterion("USER_NAME <=", value, "userName");
			return this;
		}

		public Criteria andUserNameLike(String value) {
			addCriterion("USER_NAME like", value, "userName");
			return this;
		}

		public Criteria andUserNameNotLike(String value) {
			addCriterion("USER_NAME not like", value, "userName");
			return this;
		}

		public Criteria andUserNameIn(List values) {
			addCriterion("USER_NAME in", values, "userName");
			return this;
		}

		public Criteria andUserNameNotIn(List values) {
			addCriterion("USER_NAME not in", values, "userName");
			return this;
		}

		public Criteria andUserNameBetween(String value1, String value2) {
			addCriterion("USER_NAME between", value1, value2, "userName");
			return this;
		}

		public Criteria andUserNameNotBetween(String value1, String value2) {
			addCriterion("USER_NAME not between", value1, value2, "userName");
			return this;
		}

		public Criteria andExpressCompanyIsNull() {
			addCriterion("EXPRESS_COMPANY is null");
			return this;
		}

		public Criteria andExpressCompanyIsNotNull() {
			addCriterion("EXPRESS_COMPANY is not null");
			return this;
		}

		public Criteria andExpressCompanyEqualTo(String value) {
			addCriterion("EXPRESS_COMPANY =", value, "expressCompany");
			return this;
		}

		public Criteria andExpressCompanyNotEqualTo(String value) {
			addCriterion("EXPRESS_COMPANY <>", value, "expressCompany");
			return this;
		}

		public Criteria andExpressCompanyGreaterThan(String value) {
			addCriterion("EXPRESS_COMPANY >", value, "expressCompany");
			return this;
		}

		public Criteria andExpressCompanyGreaterThanOrEqualTo(String value) {
			addCriterion("EXPRESS_COMPANY >=", value, "expressCompany");
			return this;
		}

		public Criteria andExpressCompanyLessThan(String value) {
			addCriterion("EXPRESS_COMPANY <", value, "expressCompany");
			return this;
		}

		public Criteria andExpressCompanyLessThanOrEqualTo(String value) {
			addCriterion("EXPRESS_COMPANY <=", value, "expressCompany");
			return this;
		}

		public Criteria andExpressCompanyLike(String value) {
			addCriterion("EXPRESS_COMPANY like", value, "expressCompany");
			return this;
		}

		public Criteria andExpressCompanyNotLike(String value) {
			addCriterion("EXPRESS_COMPANY not like", value, "expressCompany");
			return this;
		}

		public Criteria andExpressCompanyIn(List values) {
			addCriterion("EXPRESS_COMPANY in", values, "expressCompany");
			return this;
		}

		public Criteria andExpressCompanyNotIn(List values) {
			addCriterion("EXPRESS_COMPANY not in", values, "expressCompany");
			return this;
		}

		public Criteria andExpressCompanyBetween(String value1, String value2) {
			addCriterion("EXPRESS_COMPANY between", value1, value2,
					"expressCompany");
			return this;
		}

		public Criteria andExpressCompanyNotBetween(String value1, String value2) {
			addCriterion("EXPRESS_COMPANY not between", value1, value2,
					"expressCompany");
			return this;
		}

		public Criteria andExpressInfoIsNull() {
			addCriterion("EXPRESS_INFO is null");
			return this;
		}

		public Criteria andExpressInfoIsNotNull() {
			addCriterion("EXPRESS_INFO is not null");
			return this;
		}

		public Criteria andExpressInfoEqualTo(String value) {
			addCriterion("EXPRESS_INFO =", value, "expressInfo");
			return this;
		}

		public Criteria andExpressInfoNotEqualTo(String value) {
			addCriterion("EXPRESS_INFO <>", value, "expressInfo");
			return this;
		}

		public Criteria andExpressInfoGreaterThan(String value) {
			addCriterion("EXPRESS_INFO >", value, "expressInfo");
			return this;
		}

		public Criteria andExpressInfoGreaterThanOrEqualTo(String value) {
			addCriterion("EXPRESS_INFO >=", value, "expressInfo");
			return this;
		}

		public Criteria andExpressInfoLessThan(String value) {
			addCriterion("EXPRESS_INFO <", value, "expressInfo");
			return this;
		}

		public Criteria andExpressInfoLessThanOrEqualTo(String value) {
			addCriterion("EXPRESS_INFO <=", value, "expressInfo");
			return this;
		}

		public Criteria andExpressInfoLike(String value) {
			addCriterion("EXPRESS_INFO like", value, "expressInfo");
			return this;
		}

		public Criteria andExpressInfoNotLike(String value) {
			addCriterion("EXPRESS_INFO not like", value, "expressInfo");
			return this;
		}

		public Criteria andExpressInfoIn(List values) {
			addCriterion("EXPRESS_INFO in", values, "expressInfo");
			return this;
		}

		public Criteria andExpressInfoNotIn(List values) {
			addCriterion("EXPRESS_INFO not in", values, "expressInfo");
			return this;
		}

		public Criteria andExpressInfoBetween(String value1, String value2) {
			addCriterion("EXPRESS_INFO between", value1, value2, "expressInfo");
			return this;
		}

		public Criteria andExpressInfoNotBetween(String value1, String value2) {
			addCriterion("EXPRESS_INFO not between", value1, value2,
					"expressInfo");
			return this;
		}

		public Criteria andCardNumIsNull() {
			addCriterion("CARD_NUM is null");
			return this;
		}

		public Criteria andCardNumIsNotNull() {
			addCriterion("CARD_NUM is not null");
			return this;
		}

		public Criteria andCardNumEqualTo(Integer value) {
			addCriterion("CARD_NUM =", value, "cardNum");
			return this;
		}

		public Criteria andCardNumNotEqualTo(Integer value) {
			addCriterion("CARD_NUM <>", value, "cardNum");
			return this;
		}

		public Criteria andCardNumGreaterThan(Integer value) {
			addCriterion("CARD_NUM >", value, "cardNum");
			return this;
		}

		public Criteria andCardNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("CARD_NUM >=", value, "cardNum");
			return this;
		}

		public Criteria andCardNumLessThan(Integer value) {
			addCriterion("CARD_NUM <", value, "cardNum");
			return this;
		}

		public Criteria andCardNumLessThanOrEqualTo(Integer value) {
			addCriterion("CARD_NUM <=", value, "cardNum");
			return this;
		}

		public Criteria andCardNumIn(List values) {
			addCriterion("CARD_NUM in", values, "cardNum");
			return this;
		}

		public Criteria andCardNumNotIn(List values) {
			addCriterion("CARD_NUM not in", values, "cardNum");
			return this;
		}

		public Criteria andCardNumBetween(Integer value1, Integer value2) {
			addCriterion("CARD_NUM between", value1, value2, "cardNum");
			return this;
		}

		public Criteria andCardNumNotBetween(Integer value1, Integer value2) {
			addCriterion("CARD_NUM not between", value1, value2, "cardNum");
			return this;
		}

		public Criteria andCardTypeIsNull() {
			addCriterion("CARD_TYPE is null");
			return this;
		}

		public Criteria andCardTypeIsNotNull() {
			addCriterion("CARD_TYPE is not null");
			return this;
		}

		public Criteria andCardTypeEqualTo(String value) {
			addCriterion("CARD_TYPE =", value, "cardType");
			return this;
		}

		public Criteria andCardTypeNotEqualTo(String value) {
			addCriterion("CARD_TYPE <>", value, "cardType");
			return this;
		}

		public Criteria andCardTypeGreaterThan(String value) {
			addCriterion("CARD_TYPE >", value, "cardType");
			return this;
		}

		public Criteria andCardTypeGreaterThanOrEqualTo(String value) {
			addCriterion("CARD_TYPE >=", value, "cardType");
			return this;
		}

		public Criteria andCardTypeLessThan(String value) {
			addCriterion("CARD_TYPE <", value, "cardType");
			return this;
		}

		public Criteria andCardTypeLessThanOrEqualTo(String value) {
			addCriterion("CARD_TYPE <=", value, "cardType");
			return this;
		}

		public Criteria andCardTypeLike(String value) {
			addCriterion("CARD_TYPE like", value, "cardType");
			return this;
		}

		public Criteria andCardTypeNotLike(String value) {
			addCriterion("CARD_TYPE not like", value, "cardType");
			return this;
		}

		public Criteria andCardTypeIn(List values) {
			addCriterion("CARD_TYPE in", values, "cardType");
			return this;
		}

		public Criteria andCardTypeNotIn(List values) {
			addCriterion("CARD_TYPE not in", values, "cardType");
			return this;
		}

		public Criteria andCardTypeBetween(String value1, String value2) {
			addCriterion("CARD_TYPE between", value1, value2, "cardType");
			return this;
		}

		public Criteria andCardTypeNotBetween(String value1, String value2) {
			addCriterion("CARD_TYPE not between", value1, value2, "cardType");
			return this;
		}

		public Criteria andUserRegPhoneIsNull() {
			addCriterion("USER_REG_PHONE is null");
			return this;
		}

		public Criteria andUserRegPhoneIsNotNull() {
			addCriterion("USER_REG_PHONE is not null");
			return this;
		}

		public Criteria andUserRegPhoneEqualTo(String value) {
			addCriterion("USER_REG_PHONE =", value, "userRegPhone");
			return this;
		}

		public Criteria andUserRegPhoneNotEqualTo(String value) {
			addCriterion("USER_REG_PHONE <>", value, "userRegPhone");
			return this;
		}

		public Criteria andUserRegPhoneGreaterThan(String value) {
			addCriterion("USER_REG_PHONE >", value, "userRegPhone");
			return this;
		}

		public Criteria andUserRegPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("USER_REG_PHONE >=", value, "userRegPhone");
			return this;
		}

		public Criteria andUserRegPhoneLessThan(String value) {
			addCriterion("USER_REG_PHONE <", value, "userRegPhone");
			return this;
		}

		public Criteria andUserRegPhoneLessThanOrEqualTo(String value) {
			addCriterion("USER_REG_PHONE <=", value, "userRegPhone");
			return this;
		}

		public Criteria andUserRegPhoneLike(String value) {
			addCriterion("USER_REG_PHONE like", value, "userRegPhone");
			return this;
		}

		public Criteria andUserRegPhoneNotLike(String value) {
			addCriterion("USER_REG_PHONE not like", value, "userRegPhone");
			return this;
		}

		public Criteria andUserRegPhoneIn(List values) {
			addCriterion("USER_REG_PHONE in", values, "userRegPhone");
			return this;
		}

		public Criteria andUserRegPhoneNotIn(List values) {
			addCriterion("USER_REG_PHONE not in", values, "userRegPhone");
			return this;
		}

		public Criteria andUserRegPhoneBetween(String value1, String value2) {
			addCriterion("USER_REG_PHONE between", value1, value2,
					"userRegPhone");
			return this;
		}

		public Criteria andUserRegPhoneNotBetween(String value1, String value2) {
			addCriterion("USER_REG_PHONE not between", value1, value2,
					"userRegPhone");
			return this;
		}

		public Criteria andOftenAreaIsNull() {
			addCriterion("OFTEN_AREA is null");
			return this;
		}

		public Criteria andOftenAreaIsNotNull() {
			addCriterion("OFTEN_AREA is not null");
			return this;
		}

		public Criteria andOftenAreaEqualTo(String value) {
			addCriterion("OFTEN_AREA =", value, "oftenArea");
			return this;
		}

		public Criteria andOftenAreaNotEqualTo(String value) {
			addCriterion("OFTEN_AREA <>", value, "oftenArea");
			return this;
		}

		public Criteria andOftenAreaGreaterThan(String value) {
			addCriterion("OFTEN_AREA >", value, "oftenArea");
			return this;
		}

		public Criteria andOftenAreaGreaterThanOrEqualTo(String value) {
			addCriterion("OFTEN_AREA >=", value, "oftenArea");
			return this;
		}

		public Criteria andOftenAreaLessThan(String value) {
			addCriterion("OFTEN_AREA <", value, "oftenArea");
			return this;
		}

		public Criteria andOftenAreaLessThanOrEqualTo(String value) {
			addCriterion("OFTEN_AREA <=", value, "oftenArea");
			return this;
		}

		public Criteria andOftenAreaLike(String value) {
			addCriterion("OFTEN_AREA like", value, "oftenArea");
			return this;
		}

		public Criteria andOftenAreaNotLike(String value) {
			addCriterion("OFTEN_AREA not like", value, "oftenArea");
			return this;
		}

		public Criteria andOftenAreaIn(List values) {
			addCriterion("OFTEN_AREA in", values, "oftenArea");
			return this;
		}

		public Criteria andOftenAreaNotIn(List values) {
			addCriterion("OFTEN_AREA not in", values, "oftenArea");
			return this;
		}

		public Criteria andOftenAreaBetween(String value1, String value2) {
			addCriterion("OFTEN_AREA between", value1, value2, "oftenArea");
			return this;
		}

		public Criteria andOftenAreaNotBetween(String value1, String value2) {
			addCriterion("OFTEN_AREA not between", value1, value2, "oftenArea");
			return this;
		}

		public Criteria andIdNoIsNull() {
			addCriterion("ID_NO is null");
			return this;
		}

		public Criteria andIdNoIsNotNull() {
			addCriterion("ID_NO is not null");
			return this;
		}

		public Criteria andIdNoEqualTo(String value) {
			addCriterion("ID_NO =", value, "idNo");
			return this;
		}

		public Criteria andIdNoNotEqualTo(String value) {
			addCriterion("ID_NO <>", value, "idNo");
			return this;
		}

		public Criteria andIdNoGreaterThan(String value) {
			addCriterion("ID_NO >", value, "idNo");
			return this;
		}

		public Criteria andIdNoGreaterThanOrEqualTo(String value) {
			addCriterion("ID_NO >=", value, "idNo");
			return this;
		}

		public Criteria andIdNoLessThan(String value) {
			addCriterion("ID_NO <", value, "idNo");
			return this;
		}

		public Criteria andIdNoLessThanOrEqualTo(String value) {
			addCriterion("ID_NO <=", value, "idNo");
			return this;
		}

		public Criteria andIdNoLike(String value) {
			addCriterion("ID_NO like", value, "idNo");
			return this;
		}

		public Criteria andIdNoNotLike(String value) {
			addCriterion("ID_NO not like", value, "idNo");
			return this;
		}

		public Criteria andIdNoIn(List values) {
			addCriterion("ID_NO in", values, "idNo");
			return this;
		}

		public Criteria andIdNoNotIn(List values) {
			addCriterion("ID_NO not in", values, "idNo");
			return this;
		}

		public Criteria andIdNoBetween(String value1, String value2) {
			addCriterion("ID_NO between", value1, value2, "idNo");
			return this;
		}

		public Criteria andIdNoNotBetween(String value1, String value2) {
			addCriterion("ID_NO not between", value1, value2, "idNo");
			return this;
		}

		public Criteria andApplyTypeIsNull() {
			addCriterion("APPLY_TYPE is null");
			return this;
		}

		public Criteria andApplyTypeIsNotNull() {
			addCriterion("APPLY_TYPE is not null");
			return this;
		}

		public Criteria andApplyTypeEqualTo(String value) {
			addCriterion("APPLY_TYPE =", value, "applyType");
			return this;
		}

		public Criteria andApplyTypeNotEqualTo(String value) {
			addCriterion("APPLY_TYPE <>", value, "applyType");
			return this;
		}

		public Criteria andApplyTypeGreaterThan(String value) {
			addCriterion("APPLY_TYPE >", value, "applyType");
			return this;
		}

		public Criteria andApplyTypeGreaterThanOrEqualTo(String value) {
			addCriterion("APPLY_TYPE >=", value, "applyType");
			return this;
		}

		public Criteria andApplyTypeLessThan(String value) {
			addCriterion("APPLY_TYPE <", value, "applyType");
			return this;
		}

		public Criteria andApplyTypeLessThanOrEqualTo(String value) {
			addCriterion("APPLY_TYPE <=", value, "applyType");
			return this;
		}

		public Criteria andApplyTypeLike(String value) {
			addCriterion("APPLY_TYPE like", value, "applyType");
			return this;
		}

		public Criteria andApplyTypeNotLike(String value) {
			addCriterion("APPLY_TYPE not like", value, "applyType");
			return this;
		}

		public Criteria andApplyTypeIn(List values) {
			addCriterion("APPLY_TYPE in", values, "applyType");
			return this;
		}

		public Criteria andApplyTypeNotIn(List values) {
			addCriterion("APPLY_TYPE not in", values, "applyType");
			return this;
		}

		public Criteria andApplyTypeBetween(String value1, String value2) {
			addCriterion("APPLY_TYPE between", value1, value2, "applyType");
			return this;
		}

		public Criteria andApplyTypeNotBetween(String value1, String value2) {
			addCriterion("APPLY_TYPE not between", value1, value2, "applyType");
			return this;
		}

		public Criteria andApplyUserNameIsNull() {
			addCriterion("APPLY_USER_NAME is null");
			return this;
		}

		public Criteria andApplyUserNameIsNotNull() {
			addCriterion("APPLY_USER_NAME is not null");
			return this;
		}

		public Criteria andApplyUserNameEqualTo(String value) {
			addCriterion("APPLY_USER_NAME =", value, "applyUserName");
			return this;
		}

		public Criteria andApplyUserNameNotEqualTo(String value) {
			addCriterion("APPLY_USER_NAME <>", value, "applyUserName");
			return this;
		}

		public Criteria andApplyUserNameGreaterThan(String value) {
			addCriterion("APPLY_USER_NAME >", value, "applyUserName");
			return this;
		}

		public Criteria andApplyUserNameGreaterThanOrEqualTo(String value) {
			addCriterion("APPLY_USER_NAME >=", value, "applyUserName");
			return this;
		}

		public Criteria andApplyUserNameLessThan(String value) {
			addCriterion("APPLY_USER_NAME <", value, "applyUserName");
			return this;
		}

		public Criteria andApplyUserNameLessThanOrEqualTo(String value) {
			addCriterion("APPLY_USER_NAME <=", value, "applyUserName");
			return this;
		}

		public Criteria andApplyUserNameLike(String value) {
			addCriterion("APPLY_USER_NAME like", value, "applyUserName");
			return this;
		}

		public Criteria andApplyUserNameNotLike(String value) {
			addCriterion("APPLY_USER_NAME not like", value, "applyUserName");
			return this;
		}

		public Criteria andApplyUserNameIn(List values) {
			addCriterion("APPLY_USER_NAME in", values, "applyUserName");
			return this;
		}

		public Criteria andApplyUserNameNotIn(List values) {
			addCriterion("APPLY_USER_NAME not in", values, "applyUserName");
			return this;
		}

		public Criteria andApplyUserNameBetween(String value1, String value2) {
			addCriterion("APPLY_USER_NAME between", value1, value2,
					"applyUserName");
			return this;
		}

		public Criteria andApplyUserNameNotBetween(String value1, String value2) {
			addCriterion("APPLY_USER_NAME not between", value1, value2,
					"applyUserName");
			return this;
		}
	}
}