package com.ctfo.yppt.baseservice.dao.rebate;

import com.ctfo.yppt.baseservice.rebate.beans.ICCardRebateProcessLog;
import com.ctfo.yppt.baseservice.rebate.beans.ICCardRebateProcessLogExample;
import com.ctfo.yppt.baseservice.rebate.beans.ICCardRebateProcessLogExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ICCardRebateProcessLogDAOImpl extends SqlMapClientDaoSupport implements ICCardRebateProcessLogDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_REBATE_PROCESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	public ICCardRebateProcessLogDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_REBATE_PROCESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	public void insert(ICCardRebateProcessLog record) {
		getSqlMapClientTemplate().insert(
				"TB_IC_CARD_REBATE_PROCESS.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_REBATE_PROCESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	public int updateByPrimaryKey(ICCardRebateProcessLog record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_IC_CARD_REBATE_PROCESS.abatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_REBATE_PROCESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	public int updateByPrimaryKeySelective(ICCardRebateProcessLog record) {
		int rows = getSqlMapClientTemplate()
				.update("TB_IC_CARD_REBATE_PROCESS.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_REBATE_PROCESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	public List selectByExample(ICCardRebateProcessLogExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_CARD_REBATE_PROCESS.abatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_REBATE_PROCESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	public ICCardRebateProcessLog selectByPrimaryKey(String id) {
		ICCardRebateProcessLog key = new ICCardRebateProcessLog() {
		};
		key.setId(id);
		ICCardRebateProcessLog record = (ICCardRebateProcessLog) getSqlMapClientTemplate()
				.queryForObject(
						"TB_IC_CARD_REBATE_PROCESS.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_REBATE_PROCESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	public int deleteByExample(ICCardRebateProcessLogExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_IC_CARD_REBATE_PROCESS.abatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_REBATE_PROCESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	public int deleteByPrimaryKey(String id) {
		ICCardRebateProcessLog key = new ICCardRebateProcessLog() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"TB_IC_CARD_REBATE_PROCESS.abatorgenerated_deleteByPrimaryKey",
				key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_REBATE_PROCESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	public int countByExample(ICCardRebateProcessLogExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_IC_CARD_REBATE_PROCESS.abatorgenerated_countByExample",
				example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_REBATE_PROCESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	public int updateByExampleSelective(ICCardRebateProcessLog record,
			ICCardRebateProcessLogExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("TB_IC_CARD_REBATE_PROCESS.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_REBATE_PROCESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	public int updateByExample(ICCardRebateProcessLog record,
			ICCardRebateProcessLogExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_IC_CARD_REBATE_PROCESS.abatorgenerated_updateByExample",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_REBATE_PROCESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	public List selectByExampleWithPage(ICCardRebateProcessLogExample example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_IC_CARD_REBATE_PROCESS.abatorgenerated_selectByExamplePage",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_REBATE_PROCESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	public List selectByExampleWithPage(
			ICCardRebateProcessLogExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_IC_CARD_REBATE_PROCESS.abatorgenerated_selectByExampleExtendedPage",
						exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_REBATE_PROCESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	public List getKeyBy(ICCardRebateProcessLogExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_CARD_REBATE_PROCESS.abatorgenerated_selectKeyBy",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_REBATE_PROCESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	public String getNameSpace() {
		return "TB_IC_CARD_REBATE_PROCESS";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_REBATE_PROCESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	public List getKeyBy(ICCardRebateProcessLogExampleExtended example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_IC_CARD_REBATE_PROCESS.abatorgenerated_selectKeyByExtended",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_REBATE_PROCESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	public int countByExample(ICCardRebateProcessLogExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject(
						"TB_IC_CARD_REBATE_PROCESS.abatorgenerated_countByExampleExtended",
						example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table TB_IC_CARD_REBATE_PROCESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	private static class UpdateByExampleParms extends
			ICCardRebateProcessLogExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				ICCardRebateProcessLogExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}