package com.ctfo.yppt.baseservice.dao.rebate;

import com.ctfo.yppt.baseservice.rebate.beans.ICCardRebateProcessLog;
import com.ctfo.yppt.baseservice.rebate.beans.ICCardRebateProcessLogExample;
import com.ctfo.yppt.baseservice.rebate.beans.ICCardRebateProcessLogExampleExtended;
import java.util.List;

public interface ICCardRebateProcessLogDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_REBATE_PROCESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	void insert(ICCardRebateProcessLog record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_REBATE_PROCESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	int updateByPrimaryKey(ICCardRebateProcessLog record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_REBATE_PROCESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	int updateByPrimaryKeySelective(ICCardRebateProcessLog record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_REBATE_PROCESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	List selectByExample(ICCardRebateProcessLogExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_REBATE_PROCESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	ICCardRebateProcessLog selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_REBATE_PROCESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	int deleteByExample(ICCardRebateProcessLogExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_REBATE_PROCESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_REBATE_PROCESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	int countByExample(ICCardRebateProcessLogExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_REBATE_PROCESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	int updateByExampleSelective(ICCardRebateProcessLog record,
			ICCardRebateProcessLogExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_REBATE_PROCESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	int updateByExample(ICCardRebateProcessLog record,
			ICCardRebateProcessLogExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_REBATE_PROCESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	List selectByExampleWithPage(ICCardRebateProcessLogExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_REBATE_PROCESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	List selectByExampleWithPage(
			ICCardRebateProcessLogExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_REBATE_PROCESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	List getKeyBy(ICCardRebateProcessLogExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_REBATE_PROCESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_REBATE_PROCESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	List getKeyBy(ICCardRebateProcessLogExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_REBATE_PROCESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	int countByExample(ICCardRebateProcessLogExampleExtended example);
}