package com.ctfo.yppt.baseservice.dao.rebate;

import com.ctfo.yppt.baseservice.rebate.beans.ICRebateMessMember;
import com.ctfo.yppt.baseservice.rebate.beans.ICRebateMessMemberExample;
import com.ctfo.yppt.baseservice.rebate.beans.ICRebateMessMemberExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ICRebateMessMemberDAOImpl extends SqlMapClientDaoSupport implements ICRebateMessMemberDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_USER
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	public ICRebateMessMemberDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_USER
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	public void insert(ICRebateMessMember record) {
		getSqlMapClientTemplate().insert(
				"TB_IC_REBATE_MESS_USER.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_USER
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	public int updateByPrimaryKey(ICRebateMessMember record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_IC_REBATE_MESS_USER.abatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_USER
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	public int updateByPrimaryKeySelective(ICRebateMessMember record) {
		int rows = getSqlMapClientTemplate()
				.update("TB_IC_REBATE_MESS_USER.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_USER
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	public List selectByExample(ICRebateMessMemberExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_REBATE_MESS_USER.abatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_USER
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	public ICRebateMessMember selectByPrimaryKey(String id) {
		ICRebateMessMember key = new ICRebateMessMember() {
		};
		key.setId(id);
		ICRebateMessMember record = (ICRebateMessMember) getSqlMapClientTemplate()
				.queryForObject(
						"TB_IC_REBATE_MESS_USER.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_USER
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	public int deleteByExample(ICRebateMessMemberExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_IC_REBATE_MESS_USER.abatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_USER
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	public int deleteByPrimaryKey(String id) {
		ICRebateMessMember key = new ICRebateMessMember() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"TB_IC_REBATE_MESS_USER.abatorgenerated_deleteByPrimaryKey",
				key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_USER
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	public int countByExample(ICRebateMessMemberExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_IC_REBATE_MESS_USER.abatorgenerated_countByExample",
				example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_USER
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	public int updateByExampleSelective(ICRebateMessMember record,
			ICRebateMessMemberExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("TB_IC_REBATE_MESS_USER.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_USER
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	public int updateByExample(ICRebateMessMember record,
			ICRebateMessMemberExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("TB_IC_REBATE_MESS_USER.abatorgenerated_updateByExample",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_USER
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	public List selectByExampleWithPage(ICRebateMessMemberExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_REBATE_MESS_USER.abatorgenerated_selectByExamplePage",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_USER
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	public List selectByExampleWithPage(
			ICRebateMessMemberExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_IC_REBATE_MESS_USER.abatorgenerated_selectByExampleExtendedPage",
						exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_USER
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	public List getKeyBy(ICRebateMessMemberExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_REBATE_MESS_USER.abatorgenerated_selectKeyBy", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_USER
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	public String getNameSpace() {
		return "TB_IC_REBATE_MESS_USER";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_USER
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	public List getKeyBy(ICRebateMessMemberExampleExtended example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_REBATE_MESS_USER.abatorgenerated_selectKeyByExtended",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_USER
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	public int countByExample(ICRebateMessMemberExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject(
						"TB_IC_REBATE_MESS_USER.abatorgenerated_countByExampleExtended",
						example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table TB_IC_REBATE_MESS_USER
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	private static class UpdateByExampleParms extends ICRebateMessMemberExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				ICRebateMessMemberExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}