package com.ctfo.yppt.baseservice.dao.rebate;

import com.ctfo.yppt.baseservice.rebate.beans.ICRebateMessMember;
import com.ctfo.yppt.baseservice.rebate.beans.ICRebateMessMemberExample;
import com.ctfo.yppt.baseservice.rebate.beans.ICRebateMessMemberExampleExtended;
import java.util.List;

public interface ICRebateMessMemberDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_USER
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	void insert(ICRebateMessMember record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_USER
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	int updateByPrimaryKey(ICRebateMessMember record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_USER
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	int updateByPrimaryKeySelective(ICRebateMessMember record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_USER
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	List selectByExample(ICRebateMessMemberExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_USER
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	ICRebateMessMember selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_USER
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	int deleteByExample(ICRebateMessMemberExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_USER
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_USER
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	int countByExample(ICRebateMessMemberExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_USER
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	int updateByExampleSelective(ICRebateMessMember record,
			ICRebateMessMemberExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_USER
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	int updateByExample(ICRebateMessMember record,
			ICRebateMessMemberExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_USER
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	List selectByExampleWithPage(ICRebateMessMemberExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_USER
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	List selectByExampleWithPage(
			ICRebateMessMemberExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_USER
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	List getKeyBy(ICRebateMessMemberExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_USER
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_USER
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	List getKeyBy(ICRebateMessMemberExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_USER
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	int countByExample(ICRebateMessMemberExampleExtended example);
}