package com.ctfo.yppt.baseservice.dao.rebate;

import com.ctfo.yppt.baseservice.rebate.beans.ICRebateInfo;
import com.ctfo.yppt.baseservice.rebate.beans.ICRebateInfoExample;
import com.ctfo.yppt.baseservice.rebate.beans.ICRebateInfoExampleExtended;
import java.util.List;

public interface ICRebateInfoDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	void insert(ICRebateInfo record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	int updateByPrimaryKey(ICRebateInfo record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	int updateByPrimaryKeySelective(ICRebateInfo record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	List selectByExample(ICRebateInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	ICRebateInfo selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	int deleteByExample(ICRebateInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	int countByExample(ICRebateInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	int updateByExampleSelective(ICRebateInfo record,
			ICRebateInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	int updateByExample(ICRebateInfo record, ICRebateInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	List selectByExampleWithPage(ICRebateInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	List selectByExampleWithPage(ICRebateInfoExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	List getKeyBy(ICRebateInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	List getKeyBy(ICRebateInfoExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	int countByExample(ICRebateInfoExampleExtended example);
}