package com.ctfo.yppt.baseservice.dao.rebate;

import com.ctfo.yppt.baseservice.rebate.beans.ICRebateInfo;
import com.ctfo.yppt.baseservice.rebate.beans.ICRebateInfoExample;
import com.ctfo.yppt.baseservice.rebate.beans.ICRebateInfoExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ICRebateInfoDAOImpl extends SqlMapClientDaoSupport implements ICRebateInfoDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	public ICRebateInfoDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	public void insert(ICRebateInfo record) {
		getSqlMapClientTemplate().insert(
				"TB_IC_REBATE_INFO.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	public int updateByPrimaryKey(ICRebateInfo record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_IC_REBATE_INFO.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	public int updateByPrimaryKeySelective(ICRebateInfo record) {
		int rows = getSqlMapClientTemplate()
				.update("TB_IC_REBATE_INFO.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	public List selectByExample(ICRebateInfoExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_REBATE_INFO.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	public ICRebateInfo selectByPrimaryKey(String id) {
		ICRebateInfo key = new ICRebateInfo() {
		};
		key.setId(id);
		ICRebateInfo record = (ICRebateInfo) getSqlMapClientTemplate()
				.queryForObject(
						"TB_IC_REBATE_INFO.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	public int deleteByExample(ICRebateInfoExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_IC_REBATE_INFO.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	public int deleteByPrimaryKey(String id) {
		ICRebateInfo key = new ICRebateInfo() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"TB_IC_REBATE_INFO.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	public int countByExample(ICRebateInfoExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_IC_REBATE_INFO.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	public int updateByExampleSelective(ICRebateInfo record,
			ICRebateInfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_IC_REBATE_INFO.abatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	public int updateByExample(ICRebateInfo record, ICRebateInfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_IC_REBATE_INFO.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	public List selectByExampleWithPage(ICRebateInfoExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_REBATE_INFO.abatorgenerated_selectByExamplePage",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	public List selectByExampleWithPage(
			ICRebateInfoExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_IC_REBATE_INFO.abatorgenerated_selectByExampleExtendedPage",
						exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	public List getKeyBy(ICRebateInfoExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_REBATE_INFO.abatorgenerated_selectKeyBy", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	public String getNameSpace() {
		return "TB_IC_REBATE_INFO";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	public List getKeyBy(ICRebateInfoExampleExtended example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_REBATE_INFO.abatorgenerated_selectKeyByExtended",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	public int countByExample(ICRebateInfoExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_IC_REBATE_INFO.abatorgenerated_countByExampleExtended",
				example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	private static class UpdateByExampleParms extends ICRebateInfoExample {
		private Object record;

		public UpdateByExampleParms(Object record, ICRebateInfoExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}