package com.ctfo.yppt.baseservice.dao.rebate;

import com.ctfo.yppt.baseservice.rebate.beans.ICRebateMonthMess;
import com.ctfo.yppt.baseservice.rebate.beans.ICRebateMonthMessExample;
import com.ctfo.yppt.baseservice.rebate.beans.ICRebateMonthMessExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ICRebateMonthMessDAOImpl extends SqlMapClientDaoSupport implements ICRebateMonthMessDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MONTH_MESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	public ICRebateMonthMessDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MONTH_MESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	public void insert(ICRebateMonthMess record) {
		getSqlMapClientTemplate().insert(
				"TB_IC_REBATE_MONTH_MESS.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MONTH_MESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	public int updateByPrimaryKey(ICRebateMonthMess record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_IC_REBATE_MONTH_MESS.abatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MONTH_MESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	public int updateByPrimaryKeySelective(ICRebateMonthMess record) {
		int rows = getSqlMapClientTemplate()
				.update("TB_IC_REBATE_MONTH_MESS.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MONTH_MESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	public List selectByExample(ICRebateMonthMessExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_REBATE_MONTH_MESS.abatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MONTH_MESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	public ICRebateMonthMess selectByPrimaryKey(String id) {
		ICRebateMonthMess key = new ICRebateMonthMess() {
		};
		key.setId(id);
		ICRebateMonthMess record = (ICRebateMonthMess) getSqlMapClientTemplate()
				.queryForObject(
						"TB_IC_REBATE_MONTH_MESS.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MONTH_MESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	public int deleteByExample(ICRebateMonthMessExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_IC_REBATE_MONTH_MESS.abatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MONTH_MESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	public int deleteByPrimaryKey(String id) {
		ICRebateMonthMess key = new ICRebateMonthMess() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"TB_IC_REBATE_MONTH_MESS.abatorgenerated_deleteByPrimaryKey",
				key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MONTH_MESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	public int countByExample(ICRebateMonthMessExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_IC_REBATE_MONTH_MESS.abatorgenerated_countByExample",
				example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MONTH_MESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	public int updateByExampleSelective(ICRebateMonthMess record,
			ICRebateMonthMessExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("TB_IC_REBATE_MONTH_MESS.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MONTH_MESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	public int updateByExample(ICRebateMonthMess record,
			ICRebateMonthMessExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_IC_REBATE_MONTH_MESS.abatorgenerated_updateByExample",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MONTH_MESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	public List selectByExampleWithPage(ICRebateMonthMessExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_REBATE_MONTH_MESS.abatorgenerated_selectByExamplePage",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MONTH_MESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	public List selectByExampleWithPage(
			ICRebateMonthMessExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_IC_REBATE_MONTH_MESS.abatorgenerated_selectByExampleExtendedPage",
						exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MONTH_MESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	public List getKeyBy(ICRebateMonthMessExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_REBATE_MONTH_MESS.abatorgenerated_selectKeyBy", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MONTH_MESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	public String getNameSpace() {
		return "TB_IC_REBATE_MONTH_MESS";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MONTH_MESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	public List getKeyBy(ICRebateMonthMessExampleExtended example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_REBATE_MONTH_MESS.abatorgenerated_selectKeyByExtended",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MONTH_MESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	public int countByExample(ICRebateMonthMessExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject(
						"TB_IC_REBATE_MONTH_MESS.abatorgenerated_countByExampleExtended",
						example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table TB_IC_REBATE_MONTH_MESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	private static class UpdateByExampleParms extends ICRebateMonthMessExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				ICRebateMonthMessExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}