package com.ctfo.yppt.baseservice.dao.rebate;

import com.ctfo.yppt.baseservice.rebate.beans.ICRebateMessCard;
import com.ctfo.yppt.baseservice.rebate.beans.ICRebateMessCardExample;
import com.ctfo.yppt.baseservice.rebate.beans.ICRebateMessCardExampleExtended;
import java.util.List;

public interface ICRebateMessCardDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_CARD
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	void insert(ICRebateMessCard record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_CARD
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	int updateByPrimaryKey(ICRebateMessCard record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_CARD
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	int updateByPrimaryKeySelective(ICRebateMessCard record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_CARD
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	List selectByExample(ICRebateMessCardExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_CARD
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	ICRebateMessCard selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_CARD
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	int deleteByExample(ICRebateMessCardExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_CARD
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_CARD
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	int countByExample(ICRebateMessCardExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_CARD
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	int updateByExampleSelective(ICRebateMessCard record,
			ICRebateMessCardExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_CARD
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	int updateByExample(ICRebateMessCard record, ICRebateMessCardExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_CARD
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	List selectByExampleWithPage(ICRebateMessCardExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_CARD
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	List selectByExampleWithPage(ICRebateMessCardExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_CARD
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	List getKeyBy(ICRebateMessCardExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_CARD
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_CARD
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	List getKeyBy(ICRebateMessCardExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_CARD
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	int countByExample(ICRebateMessCardExampleExtended example);
}