package com.ctfo.yppt.baseservice.dao.rebate;

import com.ctfo.yppt.baseservice.rebate.beans.ICRebateMonthMess;
import com.ctfo.yppt.baseservice.rebate.beans.ICRebateMonthMessExample;
import com.ctfo.yppt.baseservice.rebate.beans.ICRebateMonthMessExampleExtended;
import java.util.List;

public interface ICRebateMonthMessDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MONTH_MESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	void insert(ICRebateMonthMess record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MONTH_MESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	int updateByPrimaryKey(ICRebateMonthMess record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MONTH_MESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	int updateByPrimaryKeySelective(ICRebateMonthMess record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MONTH_MESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	List selectByExample(ICRebateMonthMessExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MONTH_MESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	ICRebateMonthMess selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MONTH_MESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	int deleteByExample(ICRebateMonthMessExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MONTH_MESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MONTH_MESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	int countByExample(ICRebateMonthMessExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MONTH_MESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	int updateByExampleSelective(ICRebateMonthMess record,
			ICRebateMonthMessExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MONTH_MESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	int updateByExample(ICRebateMonthMess record,
			ICRebateMonthMessExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MONTH_MESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	List selectByExampleWithPage(ICRebateMonthMessExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MONTH_MESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	List selectByExampleWithPage(
			ICRebateMonthMessExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MONTH_MESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	List getKeyBy(ICRebateMonthMessExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MONTH_MESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MONTH_MESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	List getKeyBy(ICRebateMonthMessExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MONTH_MESS
	 * @abatorgenerated  Wed Jan 21 20:45:53 CST 2015
	 */
	int countByExample(ICRebateMonthMessExampleExtended example);
}