package com.ctfo.yppt.baseservice.dao.rebate;

import com.ctfo.yppt.baseservice.rebate.beans.ICRebateMessCard;
import com.ctfo.yppt.baseservice.rebate.beans.ICRebateMessCardExample;
import com.ctfo.yppt.baseservice.rebate.beans.ICRebateMessCardExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ICRebateMessCardDAOImpl extends SqlMapClientDaoSupport implements ICRebateMessCardDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_CARD
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	public ICRebateMessCardDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_CARD
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	public void insert(ICRebateMessCard record) {
		getSqlMapClientTemplate().insert(
				"TB_IC_REBATE_MESS_CARD.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_CARD
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	public int updateByPrimaryKey(ICRebateMessCard record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_IC_REBATE_MESS_CARD.abatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_CARD
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	public int updateByPrimaryKeySelective(ICRebateMessCard record) {
		int rows = getSqlMapClientTemplate()
				.update("TB_IC_REBATE_MESS_CARD.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_CARD
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	public List selectByExample(ICRebateMessCardExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_REBATE_MESS_CARD.abatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_CARD
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	public ICRebateMessCard selectByPrimaryKey(String id) {
		ICRebateMessCard key = new ICRebateMessCard() {
		};
		key.setId(id);
		ICRebateMessCard record = (ICRebateMessCard) getSqlMapClientTemplate()
				.queryForObject(
						"TB_IC_REBATE_MESS_CARD.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_CARD
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	public int deleteByExample(ICRebateMessCardExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_IC_REBATE_MESS_CARD.abatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_CARD
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	public int deleteByPrimaryKey(String id) {
		ICRebateMessCard key = new ICRebateMessCard() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"TB_IC_REBATE_MESS_CARD.abatorgenerated_deleteByPrimaryKey",
				key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_CARD
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	public int countByExample(ICRebateMessCardExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_IC_REBATE_MESS_CARD.abatorgenerated_countByExample",
				example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_CARD
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	public int updateByExampleSelective(ICRebateMessCard record,
			ICRebateMessCardExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("TB_IC_REBATE_MESS_CARD.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_CARD
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	public int updateByExample(ICRebateMessCard record,
			ICRebateMessCardExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("TB_IC_REBATE_MESS_CARD.abatorgenerated_updateByExample",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_CARD
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	public List selectByExampleWithPage(ICRebateMessCardExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_REBATE_MESS_CARD.abatorgenerated_selectByExamplePage",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_CARD
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	public List selectByExampleWithPage(
			ICRebateMessCardExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_IC_REBATE_MESS_CARD.abatorgenerated_selectByExampleExtendedPage",
						exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_CARD
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	public List getKeyBy(ICRebateMessCardExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_REBATE_MESS_CARD.abatorgenerated_selectKeyBy", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_CARD
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	public String getNameSpace() {
		return "TB_IC_REBATE_MESS_CARD";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_CARD
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	public List getKeyBy(ICRebateMessCardExampleExtended example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_REBATE_MESS_CARD.abatorgenerated_selectKeyByExtended",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_MESS_CARD
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	public int countByExample(ICRebateMessCardExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject(
						"TB_IC_REBATE_MESS_CARD.abatorgenerated_countByExampleExtended",
						example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table TB_IC_REBATE_MESS_CARD
	 * @abatorgenerated  Wed Jan 21 20:45:54 CST 2015
	 */
	private static class UpdateByExampleParms extends ICRebateMessCardExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				ICRebateMessCardExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}