package com.ctfo.yppt.baseservice.dao.recharge;

import com.ctfo.yppt.baseservice.recharge.beans.ICCardPaymentOrder;
import com.ctfo.yppt.baseservice.recharge.beans.ICCardPaymentOrderExample;
import com.ctfo.yppt.baseservice.recharge.beans.ICCardPaymentOrderExampleExtended;
import java.util.List;

public interface ICCardPaymentOrderDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_PAYMENT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	void insert(ICCardPaymentOrder record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_PAYMENT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	int updateByPrimaryKey(ICCardPaymentOrder record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_PAYMENT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	int updateByPrimaryKeySelective(ICCardPaymentOrder record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_PAYMENT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	List selectByExample(ICCardPaymentOrderExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_PAYMENT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	ICCardPaymentOrder selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_PAYMENT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	int deleteByExample(ICCardPaymentOrderExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_PAYMENT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_PAYMENT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	int countByExample(ICCardPaymentOrderExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_PAYMENT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	int updateByExampleSelective(ICCardPaymentOrder record,
			ICCardPaymentOrderExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_PAYMENT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	int updateByExample(ICCardPaymentOrder record,
			ICCardPaymentOrderExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_PAYMENT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	List selectByExampleWithPage(ICCardPaymentOrderExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_PAYMENT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	List selectByExampleWithPage(
			ICCardPaymentOrderExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_PAYMENT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	List getKeyBy(ICCardPaymentOrderExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_PAYMENT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_PAYMENT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	List getKeyBy(ICCardPaymentOrderExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_PAYMENT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	int countByExample(ICCardPaymentOrderExampleExtended example);
}