package com.ctfo.yppt.baseservice.dao.recharge;

import com.ctfo.yppt.baseservice.recharge.beans.ICCardRechangeProcessLog;
import com.ctfo.yppt.baseservice.recharge.beans.ICCardRechangeProcessLogExample;
import com.ctfo.yppt.baseservice.recharge.beans.ICCardRechangeProcessLogExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ICCardRechangeProcessLogDAOImpl extends SqlMapClientDaoSupport implements ICCardRechangeProcessLogDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_RECHANGE_PROCESS
	 * @abatorgenerated  Thu Jan 29 17:56:21 CST 2015
	 */
	public ICCardRechangeProcessLogDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_RECHANGE_PROCESS
	 * @abatorgenerated  Thu Jan 29 17:56:21 CST 2015
	 */
	public void insert(ICCardRechangeProcessLog record) {
		getSqlMapClientTemplate().insert(
				"TB_IC_CARD_RECHANGE_PROCESS.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_RECHANGE_PROCESS
	 * @abatorgenerated  Thu Jan 29 17:56:21 CST 2015
	 */
	public int updateByPrimaryKey(ICCardRechangeProcessLog record) {
		int rows = getSqlMapClientTemplate()
				.update("TB_IC_CARD_RECHANGE_PROCESS.abatorgenerated_updateByPrimaryKey",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_RECHANGE_PROCESS
	 * @abatorgenerated  Thu Jan 29 17:56:21 CST 2015
	 */
	public int updateByPrimaryKeySelective(ICCardRechangeProcessLog record) {
		int rows = getSqlMapClientTemplate()
				.update("TB_IC_CARD_RECHANGE_PROCESS.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_RECHANGE_PROCESS
	 * @abatorgenerated  Thu Jan 29 17:56:21 CST 2015
	 */
	public List selectByExample(ICCardRechangeProcessLogExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_CARD_RECHANGE_PROCESS.abatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_RECHANGE_PROCESS
	 * @abatorgenerated  Thu Jan 29 17:56:21 CST 2015
	 */
	public ICCardRechangeProcessLog selectByPrimaryKey(String id) {
		ICCardRechangeProcessLog key = new ICCardRechangeProcessLog() {
		};
		key.setId(id);
		ICCardRechangeProcessLog record = (ICCardRechangeProcessLog) getSqlMapClientTemplate()
				.queryForObject(
						"TB_IC_CARD_RECHANGE_PROCESS.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_RECHANGE_PROCESS
	 * @abatorgenerated  Thu Jan 29 17:56:21 CST 2015
	 */
	public int deleteByExample(ICCardRechangeProcessLogExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_IC_CARD_RECHANGE_PROCESS.abatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_RECHANGE_PROCESS
	 * @abatorgenerated  Thu Jan 29 17:56:21 CST 2015
	 */
	public int deleteByPrimaryKey(String id) {
		ICCardRechangeProcessLog key = new ICCardRechangeProcessLog() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate()
				.delete("TB_IC_CARD_RECHANGE_PROCESS.abatorgenerated_deleteByPrimaryKey",
						key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_RECHANGE_PROCESS
	 * @abatorgenerated  Thu Jan 29 17:56:21 CST 2015
	 */
	public int countByExample(ICCardRechangeProcessLogExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_IC_CARD_RECHANGE_PROCESS.abatorgenerated_countByExample",
				example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_RECHANGE_PROCESS
	 * @abatorgenerated  Thu Jan 29 17:56:21 CST 2015
	 */
	public int updateByExampleSelective(ICCardRechangeProcessLog record,
			ICCardRechangeProcessLogExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("TB_IC_CARD_RECHANGE_PROCESS.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_RECHANGE_PROCESS
	 * @abatorgenerated  Thu Jan 29 17:56:21 CST 2015
	 */
	public int updateByExample(ICCardRechangeProcessLog record,
			ICCardRechangeProcessLogExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_IC_CARD_RECHANGE_PROCESS.abatorgenerated_updateByExample",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_RECHANGE_PROCESS
	 * @abatorgenerated  Thu Jan 29 17:56:21 CST 2015
	 */
	public List selectByExampleWithPage(ICCardRechangeProcessLogExample example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_IC_CARD_RECHANGE_PROCESS.abatorgenerated_selectByExamplePage",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_RECHANGE_PROCESS
	 * @abatorgenerated  Thu Jan 29 17:56:21 CST 2015
	 */
	public List selectByExampleWithPage(
			ICCardRechangeProcessLogExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_IC_CARD_RECHANGE_PROCESS.abatorgenerated_selectByExampleExtendedPage",
						exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_RECHANGE_PROCESS
	 * @abatorgenerated  Thu Jan 29 17:56:21 CST 2015
	 */
	public List getKeyBy(ICCardRechangeProcessLogExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_CARD_RECHANGE_PROCESS.abatorgenerated_selectKeyBy",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_RECHANGE_PROCESS
	 * @abatorgenerated  Thu Jan 29 17:56:21 CST 2015
	 */
	public String getNameSpace() {
		return "TB_IC_CARD_RECHANGE_PROCESS";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_RECHANGE_PROCESS
	 * @abatorgenerated  Thu Jan 29 17:56:21 CST 2015
	 */
	public List getKeyBy(ICCardRechangeProcessLogExampleExtended example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_IC_CARD_RECHANGE_PROCESS.abatorgenerated_selectKeyByExtended",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_RECHANGE_PROCESS
	 * @abatorgenerated  Thu Jan 29 17:56:21 CST 2015
	 */
	public int countByExample(ICCardRechangeProcessLogExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject(
						"TB_IC_CARD_RECHANGE_PROCESS.abatorgenerated_countByExampleExtended",
						example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table TB_IC_CARD_RECHANGE_PROCESS
	 * @abatorgenerated  Thu Jan 29 17:56:21 CST 2015
	 */
	private static class UpdateByExampleParms extends
			ICCardRechangeProcessLogExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				ICCardRechangeProcessLogExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}