package com.ctfo.yppt.baseservice.dao.recharge;

import com.ctfo.yppt.baseservice.recharge.beans.ICCardCreditOrder;
import com.ctfo.yppt.baseservice.recharge.beans.ICCardCreditOrderExample;
import com.ctfo.yppt.baseservice.recharge.beans.ICCardCreditOrderExampleExtended;
import java.util.List;

public interface ICCardCreditOrderDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	void insert(ICCardCreditOrder record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	int updateByPrimaryKey(ICCardCreditOrder record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	int updateByPrimaryKeySelective(ICCardCreditOrder record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	List selectByExample(ICCardCreditOrderExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	ICCardCreditOrder selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	int deleteByExample(ICCardCreditOrderExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	int countByExample(ICCardCreditOrderExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	int updateByExampleSelective(ICCardCreditOrder record,
			ICCardCreditOrderExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	int updateByExample(ICCardCreditOrder record,
			ICCardCreditOrderExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	List selectByExampleWithPage(ICCardCreditOrderExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	List selectByExampleWithPage(
			ICCardCreditOrderExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	List getKeyBy(ICCardCreditOrderExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	List getKeyBy(ICCardCreditOrderExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	int countByExample(ICCardCreditOrderExampleExtended example);
}