package com.ctfo.yppt.baseservice.dao.recharge;

import com.ctfo.yppt.baseservice.recharge.beans.ICCardCreditOrder;
import com.ctfo.yppt.baseservice.recharge.beans.ICCardCreditOrderExample;
import com.ctfo.yppt.baseservice.recharge.beans.ICCardCreditOrderExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ICCardCreditOrderDAOImpl extends SqlMapClientDaoSupport implements ICCardCreditOrderDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public ICCardCreditOrderDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public void insert(ICCardCreditOrder record) {
		getSqlMapClientTemplate().insert(
				"TB_IC_CARD_CREDIT_ORDER.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public int updateByPrimaryKey(ICCardCreditOrder record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_IC_CARD_CREDIT_ORDER.abatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public int updateByPrimaryKeySelective(ICCardCreditOrder record) {
		int rows = getSqlMapClientTemplate()
				.update("TB_IC_CARD_CREDIT_ORDER.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public List selectByExample(ICCardCreditOrderExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_CARD_CREDIT_ORDER.abatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public ICCardCreditOrder selectByPrimaryKey(String id) {
		ICCardCreditOrder key = new ICCardCreditOrder() {
		};
		key.setId(id);
		ICCardCreditOrder record = (ICCardCreditOrder) getSqlMapClientTemplate()
				.queryForObject(
						"TB_IC_CARD_CREDIT_ORDER.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public int deleteByExample(ICCardCreditOrderExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_IC_CARD_CREDIT_ORDER.abatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public int deleteByPrimaryKey(String id) {
		ICCardCreditOrder key = new ICCardCreditOrder() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"TB_IC_CARD_CREDIT_ORDER.abatorgenerated_deleteByPrimaryKey",
				key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public int countByExample(ICCardCreditOrderExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_IC_CARD_CREDIT_ORDER.abatorgenerated_countByExample",
				example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public int updateByExampleSelective(ICCardCreditOrder record,
			ICCardCreditOrderExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("TB_IC_CARD_CREDIT_ORDER.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public int updateByExample(ICCardCreditOrder record,
			ICCardCreditOrderExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_IC_CARD_CREDIT_ORDER.abatorgenerated_updateByExample",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public List selectByExampleWithPage(ICCardCreditOrderExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_CARD_CREDIT_ORDER.abatorgenerated_selectByExamplePage",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public List selectByExampleWithPage(
			ICCardCreditOrderExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_IC_CARD_CREDIT_ORDER.abatorgenerated_selectByExampleExtendedPage",
						exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public List getKeyBy(ICCardCreditOrderExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_CARD_CREDIT_ORDER.abatorgenerated_selectKeyBy", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public String getNameSpace() {
		return "TB_IC_CARD_CREDIT_ORDER";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public List getKeyBy(ICCardCreditOrderExampleExtended example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_CARD_CREDIT_ORDER.abatorgenerated_selectKeyByExtended",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	public int countByExample(ICCardCreditOrderExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject(
						"TB_IC_CARD_CREDIT_ORDER.abatorgenerated_countByExampleExtended",
						example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table TB_IC_CARD_CREDIT_ORDER
	 * @abatorgenerated  Thu Feb 05 21:08:30 CST 2015
	 */
	private static class UpdateByExampleParms extends ICCardCreditOrderExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				ICCardCreditOrderExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}