package com.ctfo.yppt.baseservice.dao.recharge;

import com.ctfo.yppt.baseservice.recharge.beans.ICRechargeTransferDetail;
import com.ctfo.yppt.baseservice.recharge.beans.ICRechargeTransferDetailExample;
import com.ctfo.yppt.baseservice.recharge.beans.ICRechargeTransferDetailExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ICRechargeTransferDetailDAOImpl extends SqlMapClientDaoSupport implements ICRechargeTransferDetailDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_RECHARGE_TRANSFER_DETAIL
	 * @abatorgenerated  Thu Jan 29 17:56:22 CST 2015
	 */
	public ICRechargeTransferDetailDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_RECHARGE_TRANSFER_DETAIL
	 * @abatorgenerated  Thu Jan 29 17:56:22 CST 2015
	 */
	public void insert(ICRechargeTransferDetail record) {
		getSqlMapClientTemplate().insert(
				"TB_RECHARGE_TRANSFER_DETAIL.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_RECHARGE_TRANSFER_DETAIL
	 * @abatorgenerated  Thu Jan 29 17:56:22 CST 2015
	 */
	public int updateByPrimaryKey(ICRechargeTransferDetail record) {
		int rows = getSqlMapClientTemplate()
				.update("TB_RECHARGE_TRANSFER_DETAIL.abatorgenerated_updateByPrimaryKey",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_RECHARGE_TRANSFER_DETAIL
	 * @abatorgenerated  Thu Jan 29 17:56:22 CST 2015
	 */
	public int updateByPrimaryKeySelective(ICRechargeTransferDetail record) {
		int rows = getSqlMapClientTemplate()
				.update("TB_RECHARGE_TRANSFER_DETAIL.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_RECHARGE_TRANSFER_DETAIL
	 * @abatorgenerated  Thu Jan 29 17:56:22 CST 2015
	 */
	public List selectByExample(ICRechargeTransferDetailExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_RECHARGE_TRANSFER_DETAIL.abatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_RECHARGE_TRANSFER_DETAIL
	 * @abatorgenerated  Thu Jan 29 17:56:22 CST 2015
	 */
	public ICRechargeTransferDetail selectByPrimaryKey(String id) {
		ICRechargeTransferDetail key = new ICRechargeTransferDetail() {
		};
		key.setId(id);
		ICRechargeTransferDetail record = (ICRechargeTransferDetail) getSqlMapClientTemplate()
				.queryForObject(
						"TB_RECHARGE_TRANSFER_DETAIL.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_RECHARGE_TRANSFER_DETAIL
	 * @abatorgenerated  Thu Jan 29 17:56:22 CST 2015
	 */
	public int deleteByExample(ICRechargeTransferDetailExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_RECHARGE_TRANSFER_DETAIL.abatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_RECHARGE_TRANSFER_DETAIL
	 * @abatorgenerated  Thu Jan 29 17:56:22 CST 2015
	 */
	public int deleteByPrimaryKey(String id) {
		ICRechargeTransferDetail key = new ICRechargeTransferDetail() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate()
				.delete("TB_RECHARGE_TRANSFER_DETAIL.abatorgenerated_deleteByPrimaryKey",
						key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_RECHARGE_TRANSFER_DETAIL
	 * @abatorgenerated  Thu Jan 29 17:56:22 CST 2015
	 */
	public int countByExample(ICRechargeTransferDetailExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_RECHARGE_TRANSFER_DETAIL.abatorgenerated_countByExample",
				example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_RECHARGE_TRANSFER_DETAIL
	 * @abatorgenerated  Thu Jan 29 17:56:22 CST 2015
	 */
	public int updateByExampleSelective(ICRechargeTransferDetail record,
			ICRechargeTransferDetailExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("TB_RECHARGE_TRANSFER_DETAIL.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_RECHARGE_TRANSFER_DETAIL
	 * @abatorgenerated  Thu Jan 29 17:56:22 CST 2015
	 */
	public int updateByExample(ICRechargeTransferDetail record,
			ICRechargeTransferDetailExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_RECHARGE_TRANSFER_DETAIL.abatorgenerated_updateByExample",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_RECHARGE_TRANSFER_DETAIL
	 * @abatorgenerated  Thu Jan 29 17:56:22 CST 2015
	 */
	public List selectByExampleWithPage(ICRechargeTransferDetailExample example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_RECHARGE_TRANSFER_DETAIL.abatorgenerated_selectByExamplePage",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_RECHARGE_TRANSFER_DETAIL
	 * @abatorgenerated  Thu Jan 29 17:56:22 CST 2015
	 */
	public List selectByExampleWithPage(
			ICRechargeTransferDetailExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_RECHARGE_TRANSFER_DETAIL.abatorgenerated_selectByExampleExtendedPage",
						exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_RECHARGE_TRANSFER_DETAIL
	 * @abatorgenerated  Thu Jan 29 17:56:22 CST 2015
	 */
	public List getKeyBy(ICRechargeTransferDetailExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_RECHARGE_TRANSFER_DETAIL.abatorgenerated_selectKeyBy",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_RECHARGE_TRANSFER_DETAIL
	 * @abatorgenerated  Thu Jan 29 17:56:22 CST 2015
	 */
	public String getNameSpace() {
		return "TB_RECHARGE_TRANSFER_DETAIL";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_RECHARGE_TRANSFER_DETAIL
	 * @abatorgenerated  Thu Jan 29 17:56:22 CST 2015
	 */
	public List getKeyBy(ICRechargeTransferDetailExampleExtended example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_RECHARGE_TRANSFER_DETAIL.abatorgenerated_selectKeyByExtended",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_RECHARGE_TRANSFER_DETAIL
	 * @abatorgenerated  Thu Jan 29 17:56:22 CST 2015
	 */
	public int countByExample(ICRechargeTransferDetailExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject(
						"TB_RECHARGE_TRANSFER_DETAIL.abatorgenerated_countByExampleExtended",
						example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table TB_RECHARGE_TRANSFER_DETAIL
	 * @abatorgenerated  Thu Jan 29 17:56:22 CST 2015
	 */
	private static class UpdateByExampleParms extends
			ICRechargeTransferDetailExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				ICRechargeTransferDetailExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}