package com.ctfo.yppt.baseservice.dao.recharge;

import com.ctfo.yppt.baseservice.recharge.beans.ICRechargeApplyDetail;
import com.ctfo.yppt.baseservice.recharge.beans.ICRechargeApplyDetailExample;
import com.ctfo.yppt.baseservice.recharge.beans.ICRechargeApplyDetailExampleExtended;
import java.util.List;

public interface ICRechargeApplyDetailDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_RECHARGE_APPLY_DETAIL
	 * @abatorgenerated  Tue Feb 03 14:39:29 CST 2015
	 */
	void insert(ICRechargeApplyDetail record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_RECHARGE_APPLY_DETAIL
	 * @abatorgenerated  Tue Feb 03 14:39:29 CST 2015
	 */
	int updateByPrimaryKey(ICRechargeApplyDetail record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_RECHARGE_APPLY_DETAIL
	 * @abatorgenerated  Tue Feb 03 14:39:29 CST 2015
	 */
	int updateByPrimaryKeySelective(ICRechargeApplyDetail record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_RECHARGE_APPLY_DETAIL
	 * @abatorgenerated  Tue Feb 03 14:39:29 CST 2015
	 */
	List selectByExample(ICRechargeApplyDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_RECHARGE_APPLY_DETAIL
	 * @abatorgenerated  Tue Feb 03 14:39:29 CST 2015
	 */
	ICRechargeApplyDetail selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_RECHARGE_APPLY_DETAIL
	 * @abatorgenerated  Tue Feb 03 14:39:29 CST 2015
	 */
	int deleteByExample(ICRechargeApplyDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_RECHARGE_APPLY_DETAIL
	 * @abatorgenerated  Tue Feb 03 14:39:29 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_RECHARGE_APPLY_DETAIL
	 * @abatorgenerated  Tue Feb 03 14:39:29 CST 2015
	 */
	int countByExample(ICRechargeApplyDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_RECHARGE_APPLY_DETAIL
	 * @abatorgenerated  Tue Feb 03 14:39:29 CST 2015
	 */
	int updateByExampleSelective(ICRechargeApplyDetail record,
			ICRechargeApplyDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_RECHARGE_APPLY_DETAIL
	 * @abatorgenerated  Tue Feb 03 14:39:29 CST 2015
	 */
	int updateByExample(ICRechargeApplyDetail record,
			ICRechargeApplyDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_RECHARGE_APPLY_DETAIL
	 * @abatorgenerated  Tue Feb 03 14:39:29 CST 2015
	 */
	List selectByExampleWithPage(ICRechargeApplyDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_RECHARGE_APPLY_DETAIL
	 * @abatorgenerated  Tue Feb 03 14:39:29 CST 2015
	 */
	List selectByExampleWithPage(
			ICRechargeApplyDetailExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_RECHARGE_APPLY_DETAIL
	 * @abatorgenerated  Tue Feb 03 14:39:29 CST 2015
	 */
	List getKeyBy(ICRechargeApplyDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_RECHARGE_APPLY_DETAIL
	 * @abatorgenerated  Tue Feb 03 14:39:29 CST 2015
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_RECHARGE_APPLY_DETAIL
	 * @abatorgenerated  Tue Feb 03 14:39:29 CST 2015
	 */
	List getKeyBy(ICRechargeApplyDetailExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_RECHARGE_APPLY_DETAIL
	 * @abatorgenerated  Tue Feb 03 14:39:29 CST 2015
	 */
	int countByExample(ICRechargeApplyDetailExampleExtended example);
}