package com.ctfo.yppt.baseservice.dao.recharge;

import com.ctfo.yppt.baseservice.recharge.beans.ICRechargeApply;
import com.ctfo.yppt.baseservice.recharge.beans.ICRechargeApplyExample;
import com.ctfo.yppt.baseservice.recharge.beans.ICRechargeApplyExampleExtended;
import java.util.List;

public interface ICRechargeApplyDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_RECHARGE_APPLY
	 * @abatorgenerated  Sun Feb 08 20:11:47 CST 2015
	 */
	void insert(ICRechargeApply record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_RECHARGE_APPLY
	 * @abatorgenerated  Sun Feb 08 20:11:47 CST 2015
	 */
	int updateByPrimaryKey(ICRechargeApply record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_RECHARGE_APPLY
	 * @abatorgenerated  Sun Feb 08 20:11:47 CST 2015
	 */
	int updateByPrimaryKeySelective(ICRechargeApply record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_RECHARGE_APPLY
	 * @abatorgenerated  Sun Feb 08 20:11:47 CST 2015
	 */
	List selectByExample(ICRechargeApplyExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_RECHARGE_APPLY
	 * @abatorgenerated  Sun Feb 08 20:11:47 CST 2015
	 */
	ICRechargeApply selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_RECHARGE_APPLY
	 * @abatorgenerated  Sun Feb 08 20:11:47 CST 2015
	 */
	int deleteByExample(ICRechargeApplyExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_RECHARGE_APPLY
	 * @abatorgenerated  Sun Feb 08 20:11:47 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_RECHARGE_APPLY
	 * @abatorgenerated  Sun Feb 08 20:11:47 CST 2015
	 */
	int countByExample(ICRechargeApplyExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_RECHARGE_APPLY
	 * @abatorgenerated  Sun Feb 08 20:11:47 CST 2015
	 */
	int updateByExampleSelective(ICRechargeApply record,
			ICRechargeApplyExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_RECHARGE_APPLY
	 * @abatorgenerated  Sun Feb 08 20:11:47 CST 2015
	 */
	int updateByExample(ICRechargeApply record, ICRechargeApplyExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_RECHARGE_APPLY
	 * @abatorgenerated  Sun Feb 08 20:11:47 CST 2015
	 */
	List selectByExampleWithPage(ICRechargeApplyExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_RECHARGE_APPLY
	 * @abatorgenerated  Sun Feb 08 20:11:47 CST 2015
	 */
	List selectByExampleWithPage(ICRechargeApplyExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_RECHARGE_APPLY
	 * @abatorgenerated  Sun Feb 08 20:11:47 CST 2015
	 */
	List getKeyBy(ICRechargeApplyExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_RECHARGE_APPLY
	 * @abatorgenerated  Sun Feb 08 20:11:47 CST 2015
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_RECHARGE_APPLY
	 * @abatorgenerated  Sun Feb 08 20:11:47 CST 2015
	 */
	List getKeyBy(ICRechargeApplyExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_RECHARGE_APPLY
	 * @abatorgenerated  Sun Feb 08 20:11:47 CST 2015
	 */
	int countByExample(ICRechargeApplyExampleExtended example);
}