package com.ctfo.yppt.baseservice.dao.recharge;

import com.ctfo.yppt.baseservice.recharge.beans.ICRechargeTransferDetail;
import com.ctfo.yppt.baseservice.recharge.beans.ICRechargeTransferDetailExample;
import com.ctfo.yppt.baseservice.recharge.beans.ICRechargeTransferDetailExampleExtended;
import java.util.List;

public interface ICRechargeTransferDetailDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_RECHARGE_TRANSFER_DETAIL
	 * @abatorgenerated  Thu Jan 29 17:56:22 CST 2015
	 */
	void insert(ICRechargeTransferDetail record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_RECHARGE_TRANSFER_DETAIL
	 * @abatorgenerated  Thu Jan 29 17:56:22 CST 2015
	 */
	int updateByPrimaryKey(ICRechargeTransferDetail record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_RECHARGE_TRANSFER_DETAIL
	 * @abatorgenerated  Thu Jan 29 17:56:22 CST 2015
	 */
	int updateByPrimaryKeySelective(ICRechargeTransferDetail record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_RECHARGE_TRANSFER_DETAIL
	 * @abatorgenerated  Thu Jan 29 17:56:22 CST 2015
	 */
	List selectByExample(ICRechargeTransferDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_RECHARGE_TRANSFER_DETAIL
	 * @abatorgenerated  Thu Jan 29 17:56:22 CST 2015
	 */
	ICRechargeTransferDetail selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_RECHARGE_TRANSFER_DETAIL
	 * @abatorgenerated  Thu Jan 29 17:56:22 CST 2015
	 */
	int deleteByExample(ICRechargeTransferDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_RECHARGE_TRANSFER_DETAIL
	 * @abatorgenerated  Thu Jan 29 17:56:22 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_RECHARGE_TRANSFER_DETAIL
	 * @abatorgenerated  Thu Jan 29 17:56:22 CST 2015
	 */
	int countByExample(ICRechargeTransferDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_RECHARGE_TRANSFER_DETAIL
	 * @abatorgenerated  Thu Jan 29 17:56:22 CST 2015
	 */
	int updateByExampleSelective(ICRechargeTransferDetail record,
			ICRechargeTransferDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_RECHARGE_TRANSFER_DETAIL
	 * @abatorgenerated  Thu Jan 29 17:56:22 CST 2015
	 */
	int updateByExample(ICRechargeTransferDetail record,
			ICRechargeTransferDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_RECHARGE_TRANSFER_DETAIL
	 * @abatorgenerated  Thu Jan 29 17:56:22 CST 2015
	 */
	List selectByExampleWithPage(ICRechargeTransferDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_RECHARGE_TRANSFER_DETAIL
	 * @abatorgenerated  Thu Jan 29 17:56:22 CST 2015
	 */
	List selectByExampleWithPage(
			ICRechargeTransferDetailExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_RECHARGE_TRANSFER_DETAIL
	 * @abatorgenerated  Thu Jan 29 17:56:22 CST 2015
	 */
	List getKeyBy(ICRechargeTransferDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_RECHARGE_TRANSFER_DETAIL
	 * @abatorgenerated  Thu Jan 29 17:56:22 CST 2015
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_RECHARGE_TRANSFER_DETAIL
	 * @abatorgenerated  Thu Jan 29 17:56:22 CST 2015
	 */
	List getKeyBy(ICRechargeTransferDetailExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_RECHARGE_TRANSFER_DETAIL
	 * @abatorgenerated  Thu Jan 29 17:56:22 CST 2015
	 */
	int countByExample(ICRechargeTransferDetailExampleExtended example);
}