package com.ctfo.yppt.baseservice.dao.recharge;

import com.ctfo.yppt.baseservice.recharge.beans.ICRechargeApplyDetail;
import com.ctfo.yppt.baseservice.recharge.beans.ICRechargeApplyDetailExample;
import com.ctfo.yppt.baseservice.recharge.beans.ICRechargeApplyDetailExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ICRechargeApplyDetailDAOImpl extends SqlMapClientDaoSupport implements ICRechargeApplyDetailDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_RECHARGE_APPLY_DETAIL
	 * @abatorgenerated  Tue Feb 03 14:39:29 CST 2015
	 */
	public ICRechargeApplyDetailDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_RECHARGE_APPLY_DETAIL
	 * @abatorgenerated  Tue Feb 03 14:39:29 CST 2015
	 */
	public void insert(ICRechargeApplyDetail record) {
		getSqlMapClientTemplate().insert(
				"TB_IC_RECHARGE_APPLY_DETAIL.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_RECHARGE_APPLY_DETAIL
	 * @abatorgenerated  Tue Feb 03 14:39:29 CST 2015
	 */
	public int updateByPrimaryKey(ICRechargeApplyDetail record) {
		int rows = getSqlMapClientTemplate()
				.update("TB_IC_RECHARGE_APPLY_DETAIL.abatorgenerated_updateByPrimaryKey",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_RECHARGE_APPLY_DETAIL
	 * @abatorgenerated  Tue Feb 03 14:39:29 CST 2015
	 */
	public int updateByPrimaryKeySelective(ICRechargeApplyDetail record) {
		int rows = getSqlMapClientTemplate()
				.update("TB_IC_RECHARGE_APPLY_DETAIL.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_RECHARGE_APPLY_DETAIL
	 * @abatorgenerated  Tue Feb 03 14:39:29 CST 2015
	 */
	public List selectByExample(ICRechargeApplyDetailExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_RECHARGE_APPLY_DETAIL.abatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_RECHARGE_APPLY_DETAIL
	 * @abatorgenerated  Tue Feb 03 14:39:29 CST 2015
	 */
	public ICRechargeApplyDetail selectByPrimaryKey(String id) {
		ICRechargeApplyDetail key = new ICRechargeApplyDetail() {
		};
		key.setId(id);
		ICRechargeApplyDetail record = (ICRechargeApplyDetail) getSqlMapClientTemplate()
				.queryForObject(
						"TB_IC_RECHARGE_APPLY_DETAIL.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_RECHARGE_APPLY_DETAIL
	 * @abatorgenerated  Tue Feb 03 14:39:29 CST 2015
	 */
	public int deleteByExample(ICRechargeApplyDetailExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_IC_RECHARGE_APPLY_DETAIL.abatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_RECHARGE_APPLY_DETAIL
	 * @abatorgenerated  Tue Feb 03 14:39:29 CST 2015
	 */
	public int deleteByPrimaryKey(String id) {
		ICRechargeApplyDetail key = new ICRechargeApplyDetail() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate()
				.delete("TB_IC_RECHARGE_APPLY_DETAIL.abatorgenerated_deleteByPrimaryKey",
						key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_RECHARGE_APPLY_DETAIL
	 * @abatorgenerated  Tue Feb 03 14:39:29 CST 2015
	 */
	public int countByExample(ICRechargeApplyDetailExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_IC_RECHARGE_APPLY_DETAIL.abatorgenerated_countByExample",
				example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_RECHARGE_APPLY_DETAIL
	 * @abatorgenerated  Tue Feb 03 14:39:29 CST 2015
	 */
	public int updateByExampleSelective(ICRechargeApplyDetail record,
			ICRechargeApplyDetailExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("TB_IC_RECHARGE_APPLY_DETAIL.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_RECHARGE_APPLY_DETAIL
	 * @abatorgenerated  Tue Feb 03 14:39:29 CST 2015
	 */
	public int updateByExample(ICRechargeApplyDetail record,
			ICRechargeApplyDetailExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_IC_RECHARGE_APPLY_DETAIL.abatorgenerated_updateByExample",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_RECHARGE_APPLY_DETAIL
	 * @abatorgenerated  Tue Feb 03 14:39:29 CST 2015
	 */
	public List selectByExampleWithPage(ICRechargeApplyDetailExample example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_IC_RECHARGE_APPLY_DETAIL.abatorgenerated_selectByExamplePage",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_RECHARGE_APPLY_DETAIL
	 * @abatorgenerated  Tue Feb 03 14:39:29 CST 2015
	 */
	public List selectByExampleWithPage(
			ICRechargeApplyDetailExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_IC_RECHARGE_APPLY_DETAIL.abatorgenerated_selectByExampleExtendedPage",
						exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_RECHARGE_APPLY_DETAIL
	 * @abatorgenerated  Tue Feb 03 14:39:29 CST 2015
	 */
	public List getKeyBy(ICRechargeApplyDetailExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_RECHARGE_APPLY_DETAIL.abatorgenerated_selectKeyBy",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_RECHARGE_APPLY_DETAIL
	 * @abatorgenerated  Tue Feb 03 14:39:29 CST 2015
	 */
	public String getNameSpace() {
		return "TB_IC_RECHARGE_APPLY_DETAIL";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_RECHARGE_APPLY_DETAIL
	 * @abatorgenerated  Tue Feb 03 14:39:29 CST 2015
	 */
	public List getKeyBy(ICRechargeApplyDetailExampleExtended example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_IC_RECHARGE_APPLY_DETAIL.abatorgenerated_selectKeyByExtended",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_RECHARGE_APPLY_DETAIL
	 * @abatorgenerated  Tue Feb 03 14:39:29 CST 2015
	 */
	public int countByExample(ICRechargeApplyDetailExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject(
						"TB_IC_RECHARGE_APPLY_DETAIL.abatorgenerated_countByExampleExtended",
						example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table TB_IC_RECHARGE_APPLY_DETAIL
	 * @abatorgenerated  Tue Feb 03 14:39:29 CST 2015
	 */
	private static class UpdateByExampleParms extends
			ICRechargeApplyDetailExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				ICRechargeApplyDetailExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}