package com.ctfo.yppt.baseservice.system.beans;

import com.ctfo.common.models.BaseSerializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlElement;

public class UserStat extends BaseSerializable {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TS_USER_STAT.ID DB Comment: 唯一标识
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	@XmlElement(name = "唯一标识", required = false)
	private String id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TS_USER_STAT.USER_ID DB Comment: 用户Id
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	@XmlElement(name = "用户Id", required = false)
	private String userId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TS_USER_STAT.GOLD_COIN_NUM DB Comment: 历史返利旺金币总数
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	@XmlElement(name = "历史返利旺金币总数", required = false)
	private BigDecimal goldCoinNum;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TS_USER_STAT.REBATE_MONEY DB Comment: 历史返利金额(元/100)
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	@XmlElement(name = "历史返利金额(元/100)", required = false)
	private BigDecimal rebateMoney;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TS_USER_STAT.OIL_NUM DB Comment: 加油数量(升/100)
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	@XmlElement(name = "加油数量(升/100)", required = false)
	private BigDecimal oilNum;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TS_USER_STAT.CONSUME_MONEY DB Comment: 累积消费金额
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	@XmlElement(name = "累积消费金额", required = false)
	private BigDecimal consumeMoney;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TS_USER_STAT.RECHARGE_MONEY DB Comment: 累计IC卡充值金额
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	@XmlElement(name = "累计IC卡充值金额", required = false)
	private BigDecimal rechargeMoney;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TS_USER_STAT.LAST_MONTH_COMSUME_MONEY DB Comment: 上月加油金额
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	@XmlElement(name = "上月加油金额", required = false)
	private BigDecimal lastMonthComsumeMoney;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TS_USER_STAT.LAST_MONTH_OIL_NUM DB Comment: 上月加油数量(升/100)
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	@XmlElement(name = "上月加油数量(升/100)", required = false)
	private BigDecimal lastMonthOilNum;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TS_USER_STAT.LAST_MONTH_COMSUME_ALL_MONEY DB Comment: 上月加油金额(包括加油和其他消费)(元/100)
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	@XmlElement(name = "上月加油金额(包括加油和其他消费)(元/100)", required = false)
	private BigDecimal lastMonthComsumeAllMoney;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TS_USER_STAT.LAST_MONTH_REBATE_COIN_NUM DB Comment: 上月返利旺金币数量
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	@XmlElement(name = "上月返利旺金币数量", required = false)
	private Long lastMonthRebateCoinNum;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TS_USER_STAT.LAST_MONTH_REBATE_MONEY DB Comment: 上月返利旺金币金额
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	@XmlElement(name = "上月返利旺金币金额", required = false)
	private BigDecimal lastMonthRebateMoney;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TS_USER_STAT.UPDATE_TIME DB Comment: 更新时间
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	@XmlElement(name = "更新时间", required = false)
	private Long updateTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TS_USER_STAT.INVOICE_MONEY DB Comment: 累积开票金额
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	@XmlElement(name = "累积开票金额", required = false)
	private Long invoiceMoney;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TS_USER_STAT.ID
	 * @return  the value of TS_USER_STAT.ID
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TS_USER_STAT.ID
	 * @param id  the value for TS_USER_STAT.ID
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public static String fieldId() {
		return "ID";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TS_USER_STAT.USER_ID
	 * @return  the value of TS_USER_STAT.USER_ID
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TS_USER_STAT.USER_ID
	 * @param userId  the value for TS_USER_STAT.USER_ID
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public static String fieldUserId() {
		return "USER_ID";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TS_USER_STAT.GOLD_COIN_NUM
	 * @return  the value of TS_USER_STAT.GOLD_COIN_NUM
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public BigDecimal getGoldCoinNum() {
		return goldCoinNum;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TS_USER_STAT.GOLD_COIN_NUM
	 * @param goldCoinNum  the value for TS_USER_STAT.GOLD_COIN_NUM
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public void setGoldCoinNum(BigDecimal goldCoinNum) {
		this.goldCoinNum = goldCoinNum;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public static String fieldGoldCoinNum() {
		return "GOLD_COIN_NUM";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TS_USER_STAT.REBATE_MONEY
	 * @return  the value of TS_USER_STAT.REBATE_MONEY
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public BigDecimal getRebateMoney() {
		return rebateMoney;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TS_USER_STAT.REBATE_MONEY
	 * @param rebateMoney  the value for TS_USER_STAT.REBATE_MONEY
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public void setRebateMoney(BigDecimal rebateMoney) {
		this.rebateMoney = rebateMoney;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public static String fieldRebateMoney() {
		return "REBATE_MONEY";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TS_USER_STAT.OIL_NUM
	 * @return  the value of TS_USER_STAT.OIL_NUM
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public BigDecimal getOilNum() {
		return oilNum;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TS_USER_STAT.OIL_NUM
	 * @param oilNum  the value for TS_USER_STAT.OIL_NUM
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public void setOilNum(BigDecimal oilNum) {
		this.oilNum = oilNum;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public static String fieldOilNum() {
		return "OIL_NUM";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TS_USER_STAT.CONSUME_MONEY
	 * @return  the value of TS_USER_STAT.CONSUME_MONEY
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public BigDecimal getConsumeMoney() {
		return consumeMoney;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TS_USER_STAT.CONSUME_MONEY
	 * @param consumeMoney  the value for TS_USER_STAT.CONSUME_MONEY
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public void setConsumeMoney(BigDecimal consumeMoney) {
		this.consumeMoney = consumeMoney;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public static String fieldConsumeMoney() {
		return "CONSUME_MONEY";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TS_USER_STAT.RECHARGE_MONEY
	 * @return  the value of TS_USER_STAT.RECHARGE_MONEY
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public BigDecimal getRechargeMoney() {
		return rechargeMoney;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TS_USER_STAT.RECHARGE_MONEY
	 * @param rechargeMoney  the value for TS_USER_STAT.RECHARGE_MONEY
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public void setRechargeMoney(BigDecimal rechargeMoney) {
		this.rechargeMoney = rechargeMoney;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public static String fieldRechargeMoney() {
		return "RECHARGE_MONEY";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TS_USER_STAT.LAST_MONTH_COMSUME_MONEY
	 * @return  the value of TS_USER_STAT.LAST_MONTH_COMSUME_MONEY
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public BigDecimal getLastMonthComsumeMoney() {
		return lastMonthComsumeMoney;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TS_USER_STAT.LAST_MONTH_COMSUME_MONEY
	 * @param lastMonthComsumeMoney  the value for TS_USER_STAT.LAST_MONTH_COMSUME_MONEY
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public void setLastMonthComsumeMoney(BigDecimal lastMonthComsumeMoney) {
		this.lastMonthComsumeMoney = lastMonthComsumeMoney;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public static String fieldLastMonthComsumeMoney() {
		return "LAST_MONTH_COMSUME_MONEY";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TS_USER_STAT.LAST_MONTH_OIL_NUM
	 * @return  the value of TS_USER_STAT.LAST_MONTH_OIL_NUM
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public BigDecimal getLastMonthOilNum() {
		return lastMonthOilNum;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TS_USER_STAT.LAST_MONTH_OIL_NUM
	 * @param lastMonthOilNum  the value for TS_USER_STAT.LAST_MONTH_OIL_NUM
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public void setLastMonthOilNum(BigDecimal lastMonthOilNum) {
		this.lastMonthOilNum = lastMonthOilNum;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public static String fieldLastMonthOilNum() {
		return "LAST_MONTH_OIL_NUM";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TS_USER_STAT.LAST_MONTH_COMSUME_ALL_MONEY
	 * @return  the value of TS_USER_STAT.LAST_MONTH_COMSUME_ALL_MONEY
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public BigDecimal getLastMonthComsumeAllMoney() {
		return lastMonthComsumeAllMoney;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TS_USER_STAT.LAST_MONTH_COMSUME_ALL_MONEY
	 * @param lastMonthComsumeAllMoney  the value for TS_USER_STAT.LAST_MONTH_COMSUME_ALL_MONEY
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public void setLastMonthComsumeAllMoney(BigDecimal lastMonthComsumeAllMoney) {
		this.lastMonthComsumeAllMoney = lastMonthComsumeAllMoney;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public static String fieldLastMonthComsumeAllMoney() {
		return "LAST_MONTH_COMSUME_ALL_MONEY";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TS_USER_STAT.LAST_MONTH_REBATE_COIN_NUM
	 * @return  the value of TS_USER_STAT.LAST_MONTH_REBATE_COIN_NUM
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public Long getLastMonthRebateCoinNum() {
		return lastMonthRebateCoinNum;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TS_USER_STAT.LAST_MONTH_REBATE_COIN_NUM
	 * @param lastMonthRebateCoinNum  the value for TS_USER_STAT.LAST_MONTH_REBATE_COIN_NUM
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public void setLastMonthRebateCoinNum(Long lastMonthRebateCoinNum) {
		this.lastMonthRebateCoinNum = lastMonthRebateCoinNum;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public static String fieldLastMonthRebateCoinNum() {
		return "LAST_MONTH_REBATE_COIN_NUM";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TS_USER_STAT.LAST_MONTH_REBATE_MONEY
	 * @return  the value of TS_USER_STAT.LAST_MONTH_REBATE_MONEY
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public BigDecimal getLastMonthRebateMoney() {
		return lastMonthRebateMoney;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TS_USER_STAT.LAST_MONTH_REBATE_MONEY
	 * @param lastMonthRebateMoney  the value for TS_USER_STAT.LAST_MONTH_REBATE_MONEY
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public void setLastMonthRebateMoney(BigDecimal lastMonthRebateMoney) {
		this.lastMonthRebateMoney = lastMonthRebateMoney;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public static String fieldLastMonthRebateMoney() {
		return "LAST_MONTH_REBATE_MONEY";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TS_USER_STAT.UPDATE_TIME
	 * @return  the value of TS_USER_STAT.UPDATE_TIME
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public Long getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TS_USER_STAT.UPDATE_TIME
	 * @param updateTime  the value for TS_USER_STAT.UPDATE_TIME
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public void setUpdateTime(Long updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public static String fieldUpdateTime() {
		return "UPDATE_TIME";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TS_USER_STAT.INVOICE_MONEY
	 * @return  the value of TS_USER_STAT.INVOICE_MONEY
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public Long getInvoiceMoney() {
		return invoiceMoney;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TS_USER_STAT.INVOICE_MONEY
	 * @param invoiceMoney  the value for TS_USER_STAT.INVOICE_MONEY
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public void setInvoiceMoney(Long invoiceMoney) {
		this.invoiceMoney = invoiceMoney;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public static String fieldInvoiceMoney() {
		return "INVOICE_MONEY";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public UserStat() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public static String tableName() {
		return "TS_USER_STAT";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TS_USER_STAT
	 * @abatorgenerated  Fri Feb 06 18:13:44 CST 2015
	 */
	public static String daoInterface() {
		return "com.ctfo.yppt.baseservice.dao.system.UserStatDAO";
	}
}