package com.ctfo.yppt.baseservice.rebate.beans;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ICRebateInfoExample implements Serializable {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	protected List oredCriteria;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	protected int skipNum;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	protected int endNum;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	protected int limitNum;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	public ICRebateInfoExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	protected ICRebateInfoExample(ICRebateInfoExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	public static String tableName() {
		return "TB_IC_REBATE_INFO";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	public static String daoInterface() {
		return "com.ctfo.yppt.baseservice.dao.rebate.ICRebateInfoDAO";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	public void setSkipNum(int skipNum) {
		this.skipNum = skipNum;
		this.endNum = this.skipNum + this.limitNum + 1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	public int getSkipNum() {
		return this.skipNum;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	public void setEndNum(int endNum) {
		this.endNum = endNum;
		this.limitNum = this.endNum - this.skipNum - 1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	public int getEndNum() {
		return this.endNum;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	public void setLimitNum(int limitNum) {
		this.limitNum = limitNum;
		this.endNum = this.skipNum + this.limitNum + 1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	public int getLimitNum() {
		return this.limitNum;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table TB_IC_REBATE_INFO
	 * @abatorgenerated  Wed Jan 21 20:45:55 CST 2015
	 */
	public static class Criteria implements Serializable {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("ID =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("ID <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("ID >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("ID >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("ID <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("ID <=", value, "id");
			return this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("ID like", value, "id");
			return this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("ID not like", value, "id");
			return this;
		}

		public Criteria andIdIn(List values) {
			addCriterion("ID in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List values) {
			addCriterion("ID not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("ID between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("ID not between", value1, value2, "id");
			return this;
		}

		public Criteria andRebateMessMemberIdIsNull() {
			addCriterion("REBATE_MESS_MEMBER_ID is null");
			return this;
		}

		public Criteria andRebateMessMemberIdIsNotNull() {
			addCriterion("REBATE_MESS_MEMBER_ID is not null");
			return this;
		}

		public Criteria andRebateMessMemberIdEqualTo(String value) {
			addCriterion("REBATE_MESS_MEMBER_ID =", value, "rebateMessMemberId");
			return this;
		}

		public Criteria andRebateMessMemberIdNotEqualTo(String value) {
			addCriterion("REBATE_MESS_MEMBER_ID <>", value,
					"rebateMessMemberId");
			return this;
		}

		public Criteria andRebateMessMemberIdGreaterThan(String value) {
			addCriterion("REBATE_MESS_MEMBER_ID >", value, "rebateMessMemberId");
			return this;
		}

		public Criteria andRebateMessMemberIdGreaterThanOrEqualTo(String value) {
			addCriterion("REBATE_MESS_MEMBER_ID >=", value,
					"rebateMessMemberId");
			return this;
		}

		public Criteria andRebateMessMemberIdLessThan(String value) {
			addCriterion("REBATE_MESS_MEMBER_ID <", value, "rebateMessMemberId");
			return this;
		}

		public Criteria andRebateMessMemberIdLessThanOrEqualTo(String value) {
			addCriterion("REBATE_MESS_MEMBER_ID <=", value,
					"rebateMessMemberId");
			return this;
		}

		public Criteria andRebateMessMemberIdLike(String value) {
			addCriterion("REBATE_MESS_MEMBER_ID like", value,
					"rebateMessMemberId");
			return this;
		}

		public Criteria andRebateMessMemberIdNotLike(String value) {
			addCriterion("REBATE_MESS_MEMBER_ID not like", value,
					"rebateMessMemberId");
			return this;
		}

		public Criteria andRebateMessMemberIdIn(List values) {
			addCriterion("REBATE_MESS_MEMBER_ID in", values,
					"rebateMessMemberId");
			return this;
		}

		public Criteria andRebateMessMemberIdNotIn(List values) {
			addCriterion("REBATE_MESS_MEMBER_ID not in", values,
					"rebateMessMemberId");
			return this;
		}

		public Criteria andRebateMessMemberIdBetween(String value1,
				String value2) {
			addCriterion("REBATE_MESS_MEMBER_ID between", value1, value2,
					"rebateMessMemberId");
			return this;
		}

		public Criteria andRebateMessMemberIdNotBetween(String value1,
				String value2) {
			addCriterion("REBATE_MESS_MEMBER_ID not between", value1, value2,
					"rebateMessMemberId");
			return this;
		}

		public Criteria andMerchantIdIsNull() {
			addCriterion("MERCHANT_ID is null");
			return this;
		}

		public Criteria andMerchantIdIsNotNull() {
			addCriterion("MERCHANT_ID is not null");
			return this;
		}

		public Criteria andMerchantIdEqualTo(String value) {
			addCriterion("MERCHANT_ID =", value, "merchantId");
			return this;
		}

		public Criteria andMerchantIdNotEqualTo(String value) {
			addCriterion("MERCHANT_ID <>", value, "merchantId");
			return this;
		}

		public Criteria andMerchantIdGreaterThan(String value) {
			addCriterion("MERCHANT_ID >", value, "merchantId");
			return this;
		}

		public Criteria andMerchantIdGreaterThanOrEqualTo(String value) {
			addCriterion("MERCHANT_ID >=", value, "merchantId");
			return this;
		}

		public Criteria andMerchantIdLessThan(String value) {
			addCriterion("MERCHANT_ID <", value, "merchantId");
			return this;
		}

		public Criteria andMerchantIdLessThanOrEqualTo(String value) {
			addCriterion("MERCHANT_ID <=", value, "merchantId");
			return this;
		}

		public Criteria andMerchantIdLike(String value) {
			addCriterion("MERCHANT_ID like", value, "merchantId");
			return this;
		}

		public Criteria andMerchantIdNotLike(String value) {
			addCriterion("MERCHANT_ID not like", value, "merchantId");
			return this;
		}

		public Criteria andMerchantIdIn(List values) {
			addCriterion("MERCHANT_ID in", values, "merchantId");
			return this;
		}

		public Criteria andMerchantIdNotIn(List values) {
			addCriterion("MERCHANT_ID not in", values, "merchantId");
			return this;
		}

		public Criteria andMerchantIdBetween(String value1, String value2) {
			addCriterion("MERCHANT_ID between", value1, value2, "merchantId");
			return this;
		}

		public Criteria andMerchantIdNotBetween(String value1, String value2) {
			addCriterion("MERCHANT_ID not between", value1, value2,
					"merchantId");
			return this;
		}

		public Criteria andMerchantNameIsNull() {
			addCriterion("MERCHANT_NAME is null");
			return this;
		}

		public Criteria andMerchantNameIsNotNull() {
			addCriterion("MERCHANT_NAME is not null");
			return this;
		}

		public Criteria andMerchantNameEqualTo(String value) {
			addCriterion("MERCHANT_NAME =", value, "merchantName");
			return this;
		}

		public Criteria andMerchantNameNotEqualTo(String value) {
			addCriterion("MERCHANT_NAME <>", value, "merchantName");
			return this;
		}

		public Criteria andMerchantNameGreaterThan(String value) {
			addCriterion("MERCHANT_NAME >", value, "merchantName");
			return this;
		}

		public Criteria andMerchantNameGreaterThanOrEqualTo(String value) {
			addCriterion("MERCHANT_NAME >=", value, "merchantName");
			return this;
		}

		public Criteria andMerchantNameLessThan(String value) {
			addCriterion("MERCHANT_NAME <", value, "merchantName");
			return this;
		}

		public Criteria andMerchantNameLessThanOrEqualTo(String value) {
			addCriterion("MERCHANT_NAME <=", value, "merchantName");
			return this;
		}

		public Criteria andMerchantNameLike(String value) {
			addCriterion("MERCHANT_NAME like", value, "merchantName");
			return this;
		}

		public Criteria andMerchantNameNotLike(String value) {
			addCriterion("MERCHANT_NAME not like", value, "merchantName");
			return this;
		}

		public Criteria andMerchantNameIn(List values) {
			addCriterion("MERCHANT_NAME in", values, "merchantName");
			return this;
		}

		public Criteria andMerchantNameNotIn(List values) {
			addCriterion("MERCHANT_NAME not in", values, "merchantName");
			return this;
		}

		public Criteria andMerchantNameBetween(String value1, String value2) {
			addCriterion("MERCHANT_NAME between", value1, value2,
					"merchantName");
			return this;
		}

		public Criteria andMerchantNameNotBetween(String value1, String value2) {
			addCriterion("MERCHANT_NAME not between", value1, value2,
					"merchantName");
			return this;
		}

		public Criteria andMerchantCodeIsNull() {
			addCriterion("MERCHANT_CODE is null");
			return this;
		}

		public Criteria andMerchantCodeIsNotNull() {
			addCriterion("MERCHANT_CODE is not null");
			return this;
		}

		public Criteria andMerchantCodeEqualTo(String value) {
			addCriterion("MERCHANT_CODE =", value, "merchantCode");
			return this;
		}

		public Criteria andMerchantCodeNotEqualTo(String value) {
			addCriterion("MERCHANT_CODE <>", value, "merchantCode");
			return this;
		}

		public Criteria andMerchantCodeGreaterThan(String value) {
			addCriterion("MERCHANT_CODE >", value, "merchantCode");
			return this;
		}

		public Criteria andMerchantCodeGreaterThanOrEqualTo(String value) {
			addCriterion("MERCHANT_CODE >=", value, "merchantCode");
			return this;
		}

		public Criteria andMerchantCodeLessThan(String value) {
			addCriterion("MERCHANT_CODE <", value, "merchantCode");
			return this;
		}

		public Criteria andMerchantCodeLessThanOrEqualTo(String value) {
			addCriterion("MERCHANT_CODE <=", value, "merchantCode");
			return this;
		}

		public Criteria andMerchantCodeLike(String value) {
			addCriterion("MERCHANT_CODE like", value, "merchantCode");
			return this;
		}

		public Criteria andMerchantCodeNotLike(String value) {
			addCriterion("MERCHANT_CODE not like", value, "merchantCode");
			return this;
		}

		public Criteria andMerchantCodeIn(List values) {
			addCriterion("MERCHANT_CODE in", values, "merchantCode");
			return this;
		}

		public Criteria andMerchantCodeNotIn(List values) {
			addCriterion("MERCHANT_CODE not in", values, "merchantCode");
			return this;
		}

		public Criteria andMerchantCodeBetween(String value1, String value2) {
			addCriterion("MERCHANT_CODE between", value1, value2,
					"merchantCode");
			return this;
		}

		public Criteria andMerchantCodeNotBetween(String value1, String value2) {
			addCriterion("MERCHANT_CODE not between", value1, value2,
					"merchantCode");
			return this;
		}

		public Criteria andMemberIdIsNull() {
			addCriterion("MEMBER_ID is null");
			return this;
		}

		public Criteria andMemberIdIsNotNull() {
			addCriterion("MEMBER_ID is not null");
			return this;
		}

		public Criteria andMemberIdEqualTo(String value) {
			addCriterion("MEMBER_ID =", value, "memberId");
			return this;
		}

		public Criteria andMemberIdNotEqualTo(String value) {
			addCriterion("MEMBER_ID <>", value, "memberId");
			return this;
		}

		public Criteria andMemberIdGreaterThan(String value) {
			addCriterion("MEMBER_ID >", value, "memberId");
			return this;
		}

		public Criteria andMemberIdGreaterThanOrEqualTo(String value) {
			addCriterion("MEMBER_ID >=", value, "memberId");
			return this;
		}

		public Criteria andMemberIdLessThan(String value) {
			addCriterion("MEMBER_ID <", value, "memberId");
			return this;
		}

		public Criteria andMemberIdLessThanOrEqualTo(String value) {
			addCriterion("MEMBER_ID <=", value, "memberId");
			return this;
		}

		public Criteria andMemberIdLike(String value) {
			addCriterion("MEMBER_ID like", value, "memberId");
			return this;
		}

		public Criteria andMemberIdNotLike(String value) {
			addCriterion("MEMBER_ID not like", value, "memberId");
			return this;
		}

		public Criteria andMemberIdIn(List values) {
			addCriterion("MEMBER_ID in", values, "memberId");
			return this;
		}

		public Criteria andMemberIdNotIn(List values) {
			addCriterion("MEMBER_ID not in", values, "memberId");
			return this;
		}

		public Criteria andMemberIdBetween(String value1, String value2) {
			addCriterion("MEMBER_ID between", value1, value2, "memberId");
			return this;
		}

		public Criteria andMemberIdNotBetween(String value1, String value2) {
			addCriterion("MEMBER_ID not between", value1, value2, "memberId");
			return this;
		}

		public Criteria andMemberNameIsNull() {
			addCriterion("MEMBER_NAME is null");
			return this;
		}

		public Criteria andMemberNameIsNotNull() {
			addCriterion("MEMBER_NAME is not null");
			return this;
		}

		public Criteria andMemberNameEqualTo(String value) {
			addCriterion("MEMBER_NAME =", value, "memberName");
			return this;
		}

		public Criteria andMemberNameNotEqualTo(String value) {
			addCriterion("MEMBER_NAME <>", value, "memberName");
			return this;
		}

		public Criteria andMemberNameGreaterThan(String value) {
			addCriterion("MEMBER_NAME >", value, "memberName");
			return this;
		}

		public Criteria andMemberNameGreaterThanOrEqualTo(String value) {
			addCriterion("MEMBER_NAME >=", value, "memberName");
			return this;
		}

		public Criteria andMemberNameLessThan(String value) {
			addCriterion("MEMBER_NAME <", value, "memberName");
			return this;
		}

		public Criteria andMemberNameLessThanOrEqualTo(String value) {
			addCriterion("MEMBER_NAME <=", value, "memberName");
			return this;
		}

		public Criteria andMemberNameLike(String value) {
			addCriterion("MEMBER_NAME like", value, "memberName");
			return this;
		}

		public Criteria andMemberNameNotLike(String value) {
			addCriterion("MEMBER_NAME not like", value, "memberName");
			return this;
		}

		public Criteria andMemberNameIn(List values) {
			addCriterion("MEMBER_NAME in", values, "memberName");
			return this;
		}

		public Criteria andMemberNameNotIn(List values) {
			addCriterion("MEMBER_NAME not in", values, "memberName");
			return this;
		}

		public Criteria andMemberNameBetween(String value1, String value2) {
			addCriterion("MEMBER_NAME between", value1, value2, "memberName");
			return this;
		}

		public Criteria andMemberNameNotBetween(String value1, String value2) {
			addCriterion("MEMBER_NAME not between", value1, value2,
					"memberName");
			return this;
		}

		public Criteria andMemberCodeIsNull() {
			addCriterion("MEMBER_CODE is null");
			return this;
		}

		public Criteria andMemberCodeIsNotNull() {
			addCriterion("MEMBER_CODE is not null");
			return this;
		}

		public Criteria andMemberCodeEqualTo(String value) {
			addCriterion("MEMBER_CODE =", value, "memberCode");
			return this;
		}

		public Criteria andMemberCodeNotEqualTo(String value) {
			addCriterion("MEMBER_CODE <>", value, "memberCode");
			return this;
		}

		public Criteria andMemberCodeGreaterThan(String value) {
			addCriterion("MEMBER_CODE >", value, "memberCode");
			return this;
		}

		public Criteria andMemberCodeGreaterThanOrEqualTo(String value) {
			addCriterion("MEMBER_CODE >=", value, "memberCode");
			return this;
		}

		public Criteria andMemberCodeLessThan(String value) {
			addCriterion("MEMBER_CODE <", value, "memberCode");
			return this;
		}

		public Criteria andMemberCodeLessThanOrEqualTo(String value) {
			addCriterion("MEMBER_CODE <=", value, "memberCode");
			return this;
		}

		public Criteria andMemberCodeLike(String value) {
			addCriterion("MEMBER_CODE like", value, "memberCode");
			return this;
		}

		public Criteria andMemberCodeNotLike(String value) {
			addCriterion("MEMBER_CODE not like", value, "memberCode");
			return this;
		}

		public Criteria andMemberCodeIn(List values) {
			addCriterion("MEMBER_CODE in", values, "memberCode");
			return this;
		}

		public Criteria andMemberCodeNotIn(List values) {
			addCriterion("MEMBER_CODE not in", values, "memberCode");
			return this;
		}

		public Criteria andMemberCodeBetween(String value1, String value2) {
			addCriterion("MEMBER_CODE between", value1, value2, "memberCode");
			return this;
		}

		public Criteria andMemberCodeNotBetween(String value1, String value2) {
			addCriterion("MEMBER_CODE not between", value1, value2,
					"memberCode");
			return this;
		}

		public Criteria andRebatePolicyIsNull() {
			addCriterion("REBATE_POLICY is null");
			return this;
		}

		public Criteria andRebatePolicyIsNotNull() {
			addCriterion("REBATE_POLICY is not null");
			return this;
		}

		public Criteria andRebatePolicyEqualTo(String value) {
			addCriterion("REBATE_POLICY =", value, "rebatePolicy");
			return this;
		}

		public Criteria andRebatePolicyNotEqualTo(String value) {
			addCriterion("REBATE_POLICY <>", value, "rebatePolicy");
			return this;
		}

		public Criteria andRebatePolicyGreaterThan(String value) {
			addCriterion("REBATE_POLICY >", value, "rebatePolicy");
			return this;
		}

		public Criteria andRebatePolicyGreaterThanOrEqualTo(String value) {
			addCriterion("REBATE_POLICY >=", value, "rebatePolicy");
			return this;
		}

		public Criteria andRebatePolicyLessThan(String value) {
			addCriterion("REBATE_POLICY <", value, "rebatePolicy");
			return this;
		}

		public Criteria andRebatePolicyLessThanOrEqualTo(String value) {
			addCriterion("REBATE_POLICY <=", value, "rebatePolicy");
			return this;
		}

		public Criteria andRebatePolicyLike(String value) {
			addCriterion("REBATE_POLICY like", value, "rebatePolicy");
			return this;
		}

		public Criteria andRebatePolicyNotLike(String value) {
			addCriterion("REBATE_POLICY not like", value, "rebatePolicy");
			return this;
		}

		public Criteria andRebatePolicyIn(List values) {
			addCriterion("REBATE_POLICY in", values, "rebatePolicy");
			return this;
		}

		public Criteria andRebatePolicyNotIn(List values) {
			addCriterion("REBATE_POLICY not in", values, "rebatePolicy");
			return this;
		}

		public Criteria andRebatePolicyBetween(String value1, String value2) {
			addCriterion("REBATE_POLICY between", value1, value2,
					"rebatePolicy");
			return this;
		}

		public Criteria andRebatePolicyNotBetween(String value1, String value2) {
			addCriterion("REBATE_POLICY not between", value1, value2,
					"rebatePolicy");
			return this;
		}

		public Criteria andRebatePowerIsNull() {
			addCriterion("REBATE_POWER is null");
			return this;
		}

		public Criteria andRebatePowerIsNotNull() {
			addCriterion("REBATE_POWER is not null");
			return this;
		}

		public Criteria andRebatePowerEqualTo(String value) {
			addCriterion("REBATE_POWER =", value, "rebatePower");
			return this;
		}

		public Criteria andRebatePowerNotEqualTo(String value) {
			addCriterion("REBATE_POWER <>", value, "rebatePower");
			return this;
		}

		public Criteria andRebatePowerGreaterThan(String value) {
			addCriterion("REBATE_POWER >", value, "rebatePower");
			return this;
		}

		public Criteria andRebatePowerGreaterThanOrEqualTo(String value) {
			addCriterion("REBATE_POWER >=", value, "rebatePower");
			return this;
		}

		public Criteria andRebatePowerLessThan(String value) {
			addCriterion("REBATE_POWER <", value, "rebatePower");
			return this;
		}

		public Criteria andRebatePowerLessThanOrEqualTo(String value) {
			addCriterion("REBATE_POWER <=", value, "rebatePower");
			return this;
		}

		public Criteria andRebatePowerLike(String value) {
			addCriterion("REBATE_POWER like", value, "rebatePower");
			return this;
		}

		public Criteria andRebatePowerNotLike(String value) {
			addCriterion("REBATE_POWER not like", value, "rebatePower");
			return this;
		}

		public Criteria andRebatePowerIn(List values) {
			addCriterion("REBATE_POWER in", values, "rebatePower");
			return this;
		}

		public Criteria andRebatePowerNotIn(List values) {
			addCriterion("REBATE_POWER not in", values, "rebatePower");
			return this;
		}

		public Criteria andRebatePowerBetween(String value1, String value2) {
			addCriterion("REBATE_POWER between", value1, value2, "rebatePower");
			return this;
		}

		public Criteria andRebatePowerNotBetween(String value1, String value2) {
			addCriterion("REBATE_POWER not between", value1, value2,
					"rebatePower");
			return this;
		}

		public Criteria andContactIdIsNull() {
			addCriterion("CONTACT_ID is null");
			return this;
		}

		public Criteria andContactIdIsNotNull() {
			addCriterion("CONTACT_ID is not null");
			return this;
		}

		public Criteria andContactIdEqualTo(String value) {
			addCriterion("CONTACT_ID =", value, "contactId");
			return this;
		}

		public Criteria andContactIdNotEqualTo(String value) {
			addCriterion("CONTACT_ID <>", value, "contactId");
			return this;
		}

		public Criteria andContactIdGreaterThan(String value) {
			addCriterion("CONTACT_ID >", value, "contactId");
			return this;
		}

		public Criteria andContactIdGreaterThanOrEqualTo(String value) {
			addCriterion("CONTACT_ID >=", value, "contactId");
			return this;
		}

		public Criteria andContactIdLessThan(String value) {
			addCriterion("CONTACT_ID <", value, "contactId");
			return this;
		}

		public Criteria andContactIdLessThanOrEqualTo(String value) {
			addCriterion("CONTACT_ID <=", value, "contactId");
			return this;
		}

		public Criteria andContactIdLike(String value) {
			addCriterion("CONTACT_ID like", value, "contactId");
			return this;
		}

		public Criteria andContactIdNotLike(String value) {
			addCriterion("CONTACT_ID not like", value, "contactId");
			return this;
		}

		public Criteria andContactIdIn(List values) {
			addCriterion("CONTACT_ID in", values, "contactId");
			return this;
		}

		public Criteria andContactIdNotIn(List values) {
			addCriterion("CONTACT_ID not in", values, "contactId");
			return this;
		}

		public Criteria andContactIdBetween(String value1, String value2) {
			addCriterion("CONTACT_ID between", value1, value2, "contactId");
			return this;
		}

		public Criteria andContactIdNotBetween(String value1, String value2) {
			addCriterion("CONTACT_ID not between", value1, value2, "contactId");
			return this;
		}

		public Criteria andContactNoIsNull() {
			addCriterion("CONTACT_NO is null");
			return this;
		}

		public Criteria andContactNoIsNotNull() {
			addCriterion("CONTACT_NO is not null");
			return this;
		}

		public Criteria andContactNoEqualTo(String value) {
			addCriterion("CONTACT_NO =", value, "contactNo");
			return this;
		}

		public Criteria andContactNoNotEqualTo(String value) {
			addCriterion("CONTACT_NO <>", value, "contactNo");
			return this;
		}

		public Criteria andContactNoGreaterThan(String value) {
			addCriterion("CONTACT_NO >", value, "contactNo");
			return this;
		}

		public Criteria andContactNoGreaterThanOrEqualTo(String value) {
			addCriterion("CONTACT_NO >=", value, "contactNo");
			return this;
		}

		public Criteria andContactNoLessThan(String value) {
			addCriterion("CONTACT_NO <", value, "contactNo");
			return this;
		}

		public Criteria andContactNoLessThanOrEqualTo(String value) {
			addCriterion("CONTACT_NO <=", value, "contactNo");
			return this;
		}

		public Criteria andContactNoLike(String value) {
			addCriterion("CONTACT_NO like", value, "contactNo");
			return this;
		}

		public Criteria andContactNoNotLike(String value) {
			addCriterion("CONTACT_NO not like", value, "contactNo");
			return this;
		}

		public Criteria andContactNoIn(List values) {
			addCriterion("CONTACT_NO in", values, "contactNo");
			return this;
		}

		public Criteria andContactNoNotIn(List values) {
			addCriterion("CONTACT_NO not in", values, "contactNo");
			return this;
		}

		public Criteria andContactNoBetween(String value1, String value2) {
			addCriterion("CONTACT_NO between", value1, value2, "contactNo");
			return this;
		}

		public Criteria andContactNoNotBetween(String value1, String value2) {
			addCriterion("CONTACT_NO not between", value1, value2, "contactNo");
			return this;
		}

		public Criteria andBeginDateIsNull() {
			addCriterion("BEGIN_DATE is null");
			return this;
		}

		public Criteria andBeginDateIsNotNull() {
			addCriterion("BEGIN_DATE is not null");
			return this;
		}

		public Criteria andBeginDateEqualTo(Long value) {
			addCriterion("BEGIN_DATE =", value, "beginDate");
			return this;
		}

		public Criteria andBeginDateNotEqualTo(Long value) {
			addCriterion("BEGIN_DATE <>", value, "beginDate");
			return this;
		}

		public Criteria andBeginDateGreaterThan(Long value) {
			addCriterion("BEGIN_DATE >", value, "beginDate");
			return this;
		}

		public Criteria andBeginDateGreaterThanOrEqualTo(Long value) {
			addCriterion("BEGIN_DATE >=", value, "beginDate");
			return this;
		}

		public Criteria andBeginDateLessThan(Long value) {
			addCriterion("BEGIN_DATE <", value, "beginDate");
			return this;
		}

		public Criteria andBeginDateLessThanOrEqualTo(Long value) {
			addCriterion("BEGIN_DATE <=", value, "beginDate");
			return this;
		}

		public Criteria andBeginDateIn(List values) {
			addCriterion("BEGIN_DATE in", values, "beginDate");
			return this;
		}

		public Criteria andBeginDateNotIn(List values) {
			addCriterion("BEGIN_DATE not in", values, "beginDate");
			return this;
		}

		public Criteria andBeginDateBetween(Long value1, Long value2) {
			addCriterion("BEGIN_DATE between", value1, value2, "beginDate");
			return this;
		}

		public Criteria andBeginDateNotBetween(Long value1, Long value2) {
			addCriterion("BEGIN_DATE not between", value1, value2, "beginDate");
			return this;
		}

		public Criteria andEndDateIsNull() {
			addCriterion("END_DATE is null");
			return this;
		}

		public Criteria andEndDateIsNotNull() {
			addCriterion("END_DATE is not null");
			return this;
		}

		public Criteria andEndDateEqualTo(Long value) {
			addCriterion("END_DATE =", value, "endDate");
			return this;
		}

		public Criteria andEndDateNotEqualTo(Long value) {
			addCriterion("END_DATE <>", value, "endDate");
			return this;
		}

		public Criteria andEndDateGreaterThan(Long value) {
			addCriterion("END_DATE >", value, "endDate");
			return this;
		}

		public Criteria andEndDateGreaterThanOrEqualTo(Long value) {
			addCriterion("END_DATE >=", value, "endDate");
			return this;
		}

		public Criteria andEndDateLessThan(Long value) {
			addCriterion("END_DATE <", value, "endDate");
			return this;
		}

		public Criteria andEndDateLessThanOrEqualTo(Long value) {
			addCriterion("END_DATE <=", value, "endDate");
			return this;
		}

		public Criteria andEndDateIn(List values) {
			addCriterion("END_DATE in", values, "endDate");
			return this;
		}

		public Criteria andEndDateNotIn(List values) {
			addCriterion("END_DATE not in", values, "endDate");
			return this;
		}

		public Criteria andEndDateBetween(Long value1, Long value2) {
			addCriterion("END_DATE between", value1, value2, "endDate");
			return this;
		}

		public Criteria andEndDateNotBetween(Long value1, Long value2) {
			addCriterion("END_DATE not between", value1, value2, "endDate");
			return this;
		}

		public Criteria andTradeInfoIdIsNull() {
			addCriterion("TRADE_INFO_ID is null");
			return this;
		}

		public Criteria andTradeInfoIdIsNotNull() {
			addCriterion("TRADE_INFO_ID is not null");
			return this;
		}

		public Criteria andTradeInfoIdEqualTo(String value) {
			addCriterion("TRADE_INFO_ID =", value, "tradeInfoId");
			return this;
		}

		public Criteria andTradeInfoIdNotEqualTo(String value) {
			addCriterion("TRADE_INFO_ID <>", value, "tradeInfoId");
			return this;
		}

		public Criteria andTradeInfoIdGreaterThan(String value) {
			addCriterion("TRADE_INFO_ID >", value, "tradeInfoId");
			return this;
		}

		public Criteria andTradeInfoIdGreaterThanOrEqualTo(String value) {
			addCriterion("TRADE_INFO_ID >=", value, "tradeInfoId");
			return this;
		}

		public Criteria andTradeInfoIdLessThan(String value) {
			addCriterion("TRADE_INFO_ID <", value, "tradeInfoId");
			return this;
		}

		public Criteria andTradeInfoIdLessThanOrEqualTo(String value) {
			addCriterion("TRADE_INFO_ID <=", value, "tradeInfoId");
			return this;
		}

		public Criteria andTradeInfoIdLike(String value) {
			addCriterion("TRADE_INFO_ID like", value, "tradeInfoId");
			return this;
		}

		public Criteria andTradeInfoIdNotLike(String value) {
			addCriterion("TRADE_INFO_ID not like", value, "tradeInfoId");
			return this;
		}

		public Criteria andTradeInfoIdIn(List values) {
			addCriterion("TRADE_INFO_ID in", values, "tradeInfoId");
			return this;
		}

		public Criteria andTradeInfoIdNotIn(List values) {
			addCriterion("TRADE_INFO_ID not in", values, "tradeInfoId");
			return this;
		}

		public Criteria andTradeInfoIdBetween(String value1, String value2) {
			addCriterion("TRADE_INFO_ID between", value1, value2, "tradeInfoId");
			return this;
		}

		public Criteria andTradeInfoIdNotBetween(String value1, String value2) {
			addCriterion("TRADE_INFO_ID not between", value1, value2,
					"tradeInfoId");
			return this;
		}

		public Criteria andTradeCardTypeIsNull() {
			addCriterion("TRADE_CARD_TYPE is null");
			return this;
		}

		public Criteria andTradeCardTypeIsNotNull() {
			addCriterion("TRADE_CARD_TYPE is not null");
			return this;
		}

		public Criteria andTradeCardTypeEqualTo(String value) {
			addCriterion("TRADE_CARD_TYPE =", value, "tradeCardType");
			return this;
		}

		public Criteria andTradeCardTypeNotEqualTo(String value) {
			addCriterion("TRADE_CARD_TYPE <>", value, "tradeCardType");
			return this;
		}

		public Criteria andTradeCardTypeGreaterThan(String value) {
			addCriterion("TRADE_CARD_TYPE >", value, "tradeCardType");
			return this;
		}

		public Criteria andTradeCardTypeGreaterThanOrEqualTo(String value) {
			addCriterion("TRADE_CARD_TYPE >=", value, "tradeCardType");
			return this;
		}

		public Criteria andTradeCardTypeLessThan(String value) {
			addCriterion("TRADE_CARD_TYPE <", value, "tradeCardType");
			return this;
		}

		public Criteria andTradeCardTypeLessThanOrEqualTo(String value) {
			addCriterion("TRADE_CARD_TYPE <=", value, "tradeCardType");
			return this;
		}

		public Criteria andTradeCardTypeLike(String value) {
			addCriterion("TRADE_CARD_TYPE like", value, "tradeCardType");
			return this;
		}

		public Criteria andTradeCardTypeNotLike(String value) {
			addCriterion("TRADE_CARD_TYPE not like", value, "tradeCardType");
			return this;
		}

		public Criteria andTradeCardTypeIn(List values) {
			addCriterion("TRADE_CARD_TYPE in", values, "tradeCardType");
			return this;
		}

		public Criteria andTradeCardTypeNotIn(List values) {
			addCriterion("TRADE_CARD_TYPE not in", values, "tradeCardType");
			return this;
		}

		public Criteria andTradeCardTypeBetween(String value1, String value2) {
			addCriterion("TRADE_CARD_TYPE between", value1, value2,
					"tradeCardType");
			return this;
		}

		public Criteria andTradeCardTypeNotBetween(String value1, String value2) {
			addCriterion("TRADE_CARD_TYPE not between", value1, value2,
					"tradeCardType");
			return this;
		}

		public Criteria andTotalMoneyIsNull() {
			addCriterion("TOTAL_MONEY is null");
			return this;
		}

		public Criteria andTotalMoneyIsNotNull() {
			addCriterion("TOTAL_MONEY is not null");
			return this;
		}

		public Criteria andTotalMoneyEqualTo(Long value) {
			addCriterion("TOTAL_MONEY =", value, "totalMoney");
			return this;
		}

		public Criteria andTotalMoneyNotEqualTo(Long value) {
			addCriterion("TOTAL_MONEY <>", value, "totalMoney");
			return this;
		}

		public Criteria andTotalMoneyGreaterThan(Long value) {
			addCriterion("TOTAL_MONEY >", value, "totalMoney");
			return this;
		}

		public Criteria andTotalMoneyGreaterThanOrEqualTo(Long value) {
			addCriterion("TOTAL_MONEY >=", value, "totalMoney");
			return this;
		}

		public Criteria andTotalMoneyLessThan(Long value) {
			addCriterion("TOTAL_MONEY <", value, "totalMoney");
			return this;
		}

		public Criteria andTotalMoneyLessThanOrEqualTo(Long value) {
			addCriterion("TOTAL_MONEY <=", value, "totalMoney");
			return this;
		}

		public Criteria andTotalMoneyIn(List values) {
			addCriterion("TOTAL_MONEY in", values, "totalMoney");
			return this;
		}

		public Criteria andTotalMoneyNotIn(List values) {
			addCriterion("TOTAL_MONEY not in", values, "totalMoney");
			return this;
		}

		public Criteria andTotalMoneyBetween(Long value1, Long value2) {
			addCriterion("TOTAL_MONEY between", value1, value2, "totalMoney");
			return this;
		}

		public Criteria andTotalMoneyNotBetween(Long value1, Long value2) {
			addCriterion("TOTAL_MONEY not between", value1, value2,
					"totalMoney");
			return this;
		}

		public Criteria andRebateMoneyIsNull() {
			addCriterion("REBATE_MONEY is null");
			return this;
		}

		public Criteria andRebateMoneyIsNotNull() {
			addCriterion("REBATE_MONEY is not null");
			return this;
		}

		public Criteria andRebateMoneyEqualTo(Long value) {
			addCriterion("REBATE_MONEY =", value, "rebateMoney");
			return this;
		}

		public Criteria andRebateMoneyNotEqualTo(Long value) {
			addCriterion("REBATE_MONEY <>", value, "rebateMoney");
			return this;
		}

		public Criteria andRebateMoneyGreaterThan(Long value) {
			addCriterion("REBATE_MONEY >", value, "rebateMoney");
			return this;
		}

		public Criteria andRebateMoneyGreaterThanOrEqualTo(Long value) {
			addCriterion("REBATE_MONEY >=", value, "rebateMoney");
			return this;
		}

		public Criteria andRebateMoneyLessThan(Long value) {
			addCriterion("REBATE_MONEY <", value, "rebateMoney");
			return this;
		}

		public Criteria andRebateMoneyLessThanOrEqualTo(Long value) {
			addCriterion("REBATE_MONEY <=", value, "rebateMoney");
			return this;
		}

		public Criteria andRebateMoneyIn(List values) {
			addCriterion("REBATE_MONEY in", values, "rebateMoney");
			return this;
		}

		public Criteria andRebateMoneyNotIn(List values) {
			addCriterion("REBATE_MONEY not in", values, "rebateMoney");
			return this;
		}

		public Criteria andRebateMoneyBetween(Long value1, Long value2) {
			addCriterion("REBATE_MONEY between", value1, value2, "rebateMoney");
			return this;
		}

		public Criteria andRebateMoneyNotBetween(Long value1, Long value2) {
			addCriterion("REBATE_MONEY not between", value1, value2,
					"rebateMoney");
			return this;
		}

		public Criteria andRebateTypeIsNull() {
			addCriterion("REBATE_TYPE is null");
			return this;
		}

		public Criteria andRebateTypeIsNotNull() {
			addCriterion("REBATE_TYPE is not null");
			return this;
		}

		public Criteria andRebateTypeEqualTo(String value) {
			addCriterion("REBATE_TYPE =", value, "rebateType");
			return this;
		}

		public Criteria andRebateTypeNotEqualTo(String value) {
			addCriterion("REBATE_TYPE <>", value, "rebateType");
			return this;
		}

		public Criteria andRebateTypeGreaterThan(String value) {
			addCriterion("REBATE_TYPE >", value, "rebateType");
			return this;
		}

		public Criteria andRebateTypeGreaterThanOrEqualTo(String value) {
			addCriterion("REBATE_TYPE >=", value, "rebateType");
			return this;
		}

		public Criteria andRebateTypeLessThan(String value) {
			addCriterion("REBATE_TYPE <", value, "rebateType");
			return this;
		}

		public Criteria andRebateTypeLessThanOrEqualTo(String value) {
			addCriterion("REBATE_TYPE <=", value, "rebateType");
			return this;
		}

		public Criteria andRebateTypeLike(String value) {
			addCriterion("REBATE_TYPE like", value, "rebateType");
			return this;
		}

		public Criteria andRebateTypeNotLike(String value) {
			addCriterion("REBATE_TYPE not like", value, "rebateType");
			return this;
		}

		public Criteria andRebateTypeIn(List values) {
			addCriterion("REBATE_TYPE in", values, "rebateType");
			return this;
		}

		public Criteria andRebateTypeNotIn(List values) {
			addCriterion("REBATE_TYPE not in", values, "rebateType");
			return this;
		}

		public Criteria andRebateTypeBetween(String value1, String value2) {
			addCriterion("REBATE_TYPE between", value1, value2, "rebateType");
			return this;
		}

		public Criteria andRebateTypeNotBetween(String value1, String value2) {
			addCriterion("REBATE_TYPE not between", value1, value2,
					"rebateType");
			return this;
		}

		public Criteria andStateIsNull() {
			addCriterion("STATE is null");
			return this;
		}

		public Criteria andStateIsNotNull() {
			addCriterion("STATE is not null");
			return this;
		}

		public Criteria andStateEqualTo(String value) {
			addCriterion("STATE =", value, "state");
			return this;
		}

		public Criteria andStateNotEqualTo(String value) {
			addCriterion("STATE <>", value, "state");
			return this;
		}

		public Criteria andStateGreaterThan(String value) {
			addCriterion("STATE >", value, "state");
			return this;
		}

		public Criteria andStateGreaterThanOrEqualTo(String value) {
			addCriterion("STATE >=", value, "state");
			return this;
		}

		public Criteria andStateLessThan(String value) {
			addCriterion("STATE <", value, "state");
			return this;
		}

		public Criteria andStateLessThanOrEqualTo(String value) {
			addCriterion("STATE <=", value, "state");
			return this;
		}

		public Criteria andStateLike(String value) {
			addCriterion("STATE like", value, "state");
			return this;
		}

		public Criteria andStateNotLike(String value) {
			addCriterion("STATE not like", value, "state");
			return this;
		}

		public Criteria andStateIn(List values) {
			addCriterion("STATE in", values, "state");
			return this;
		}

		public Criteria andStateNotIn(List values) {
			addCriterion("STATE not in", values, "state");
			return this;
		}

		public Criteria andStateBetween(String value1, String value2) {
			addCriterion("STATE between", value1, value2, "state");
			return this;
		}

		public Criteria andStateNotBetween(String value1, String value2) {
			addCriterion("STATE not between", value1, value2, "state");
			return this;
		}

		public Criteria andApplyPersonIdIsNull() {
			addCriterion("APPLY_PERSON_ID is null");
			return this;
		}

		public Criteria andApplyPersonIdIsNotNull() {
			addCriterion("APPLY_PERSON_ID is not null");
			return this;
		}

		public Criteria andApplyPersonIdEqualTo(String value) {
			addCriterion("APPLY_PERSON_ID =", value, "applyPersonId");
			return this;
		}

		public Criteria andApplyPersonIdNotEqualTo(String value) {
			addCriterion("APPLY_PERSON_ID <>", value, "applyPersonId");
			return this;
		}

		public Criteria andApplyPersonIdGreaterThan(String value) {
			addCriterion("APPLY_PERSON_ID >", value, "applyPersonId");
			return this;
		}

		public Criteria andApplyPersonIdGreaterThanOrEqualTo(String value) {
			addCriterion("APPLY_PERSON_ID >=", value, "applyPersonId");
			return this;
		}

		public Criteria andApplyPersonIdLessThan(String value) {
			addCriterion("APPLY_PERSON_ID <", value, "applyPersonId");
			return this;
		}

		public Criteria andApplyPersonIdLessThanOrEqualTo(String value) {
			addCriterion("APPLY_PERSON_ID <=", value, "applyPersonId");
			return this;
		}

		public Criteria andApplyPersonIdLike(String value) {
			addCriterion("APPLY_PERSON_ID like", value, "applyPersonId");
			return this;
		}

		public Criteria andApplyPersonIdNotLike(String value) {
			addCriterion("APPLY_PERSON_ID not like", value, "applyPersonId");
			return this;
		}

		public Criteria andApplyPersonIdIn(List values) {
			addCriterion("APPLY_PERSON_ID in", values, "applyPersonId");
			return this;
		}

		public Criteria andApplyPersonIdNotIn(List values) {
			addCriterion("APPLY_PERSON_ID not in", values, "applyPersonId");
			return this;
		}

		public Criteria andApplyPersonIdBetween(String value1, String value2) {
			addCriterion("APPLY_PERSON_ID between", value1, value2,
					"applyPersonId");
			return this;
		}

		public Criteria andApplyPersonIdNotBetween(String value1, String value2) {
			addCriterion("APPLY_PERSON_ID not between", value1, value2,
					"applyPersonId");
			return this;
		}

		public Criteria andRebateTimeIsNull() {
			addCriterion("REBATE_TIME is null");
			return this;
		}

		public Criteria andRebateTimeIsNotNull() {
			addCriterion("REBATE_TIME is not null");
			return this;
		}

		public Criteria andRebateTimeEqualTo(Long value) {
			addCriterion("REBATE_TIME =", value, "rebateTime");
			return this;
		}

		public Criteria andRebateTimeNotEqualTo(Long value) {
			addCriterion("REBATE_TIME <>", value, "rebateTime");
			return this;
		}

		public Criteria andRebateTimeGreaterThan(Long value) {
			addCriterion("REBATE_TIME >", value, "rebateTime");
			return this;
		}

		public Criteria andRebateTimeGreaterThanOrEqualTo(Long value) {
			addCriterion("REBATE_TIME >=", value, "rebateTime");
			return this;
		}

		public Criteria andRebateTimeLessThan(Long value) {
			addCriterion("REBATE_TIME <", value, "rebateTime");
			return this;
		}

		public Criteria andRebateTimeLessThanOrEqualTo(Long value) {
			addCriterion("REBATE_TIME <=", value, "rebateTime");
			return this;
		}

		public Criteria andRebateTimeIn(List values) {
			addCriterion("REBATE_TIME in", values, "rebateTime");
			return this;
		}

		public Criteria andRebateTimeNotIn(List values) {
			addCriterion("REBATE_TIME not in", values, "rebateTime");
			return this;
		}

		public Criteria andRebateTimeBetween(Long value1, Long value2) {
			addCriterion("REBATE_TIME between", value1, value2, "rebateTime");
			return this;
		}

		public Criteria andRebateTimeNotBetween(Long value1, Long value2) {
			addCriterion("REBATE_TIME not between", value1, value2,
					"rebateTime");
			return this;
		}

		public Criteria andProductNameIsNull() {
			addCriterion("PRODUCT_NAME is null");
			return this;
		}

		public Criteria andProductNameIsNotNull() {
			addCriterion("PRODUCT_NAME is not null");
			return this;
		}

		public Criteria andProductNameEqualTo(String value) {
			addCriterion("PRODUCT_NAME =", value, "productName");
			return this;
		}

		public Criteria andProductNameNotEqualTo(String value) {
			addCriterion("PRODUCT_NAME <>", value, "productName");
			return this;
		}

		public Criteria andProductNameGreaterThan(String value) {
			addCriterion("PRODUCT_NAME >", value, "productName");
			return this;
		}

		public Criteria andProductNameGreaterThanOrEqualTo(String value) {
			addCriterion("PRODUCT_NAME >=", value, "productName");
			return this;
		}

		public Criteria andProductNameLessThan(String value) {
			addCriterion("PRODUCT_NAME <", value, "productName");
			return this;
		}

		public Criteria andProductNameLessThanOrEqualTo(String value) {
			addCriterion("PRODUCT_NAME <=", value, "productName");
			return this;
		}

		public Criteria andProductNameLike(String value) {
			addCriterion("PRODUCT_NAME like", value, "productName");
			return this;
		}

		public Criteria andProductNameNotLike(String value) {
			addCriterion("PRODUCT_NAME not like", value, "productName");
			return this;
		}

		public Criteria andProductNameIn(List values) {
			addCriterion("PRODUCT_NAME in", values, "productName");
			return this;
		}

		public Criteria andProductNameNotIn(List values) {
			addCriterion("PRODUCT_NAME not in", values, "productName");
			return this;
		}

		public Criteria andProductNameBetween(String value1, String value2) {
			addCriterion("PRODUCT_NAME between", value1, value2, "productName");
			return this;
		}

		public Criteria andProductNameNotBetween(String value1, String value2) {
			addCriterion("PRODUCT_NAME not between", value1, value2,
					"productName");
			return this;
		}

		public Criteria andProductCodeIsNull() {
			addCriterion("PRODUCT_CODE is null");
			return this;
		}

		public Criteria andProductCodeIsNotNull() {
			addCriterion("PRODUCT_CODE is not null");
			return this;
		}

		public Criteria andProductCodeEqualTo(String value) {
			addCriterion("PRODUCT_CODE =", value, "productCode");
			return this;
		}

		public Criteria andProductCodeNotEqualTo(String value) {
			addCriterion("PRODUCT_CODE <>", value, "productCode");
			return this;
		}

		public Criteria andProductCodeGreaterThan(String value) {
			addCriterion("PRODUCT_CODE >", value, "productCode");
			return this;
		}

		public Criteria andProductCodeGreaterThanOrEqualTo(String value) {
			addCriterion("PRODUCT_CODE >=", value, "productCode");
			return this;
		}

		public Criteria andProductCodeLessThan(String value) {
			addCriterion("PRODUCT_CODE <", value, "productCode");
			return this;
		}

		public Criteria andProductCodeLessThanOrEqualTo(String value) {
			addCriterion("PRODUCT_CODE <=", value, "productCode");
			return this;
		}

		public Criteria andProductCodeLike(String value) {
			addCriterion("PRODUCT_CODE like", value, "productCode");
			return this;
		}

		public Criteria andProductCodeNotLike(String value) {
			addCriterion("PRODUCT_CODE not like", value, "productCode");
			return this;
		}

		public Criteria andProductCodeIn(List values) {
			addCriterion("PRODUCT_CODE in", values, "productCode");
			return this;
		}

		public Criteria andProductCodeNotIn(List values) {
			addCriterion("PRODUCT_CODE not in", values, "productCode");
			return this;
		}

		public Criteria andProductCodeBetween(String value1, String value2) {
			addCriterion("PRODUCT_CODE between", value1, value2, "productCode");
			return this;
		}

		public Criteria andProductCodeNotBetween(String value1, String value2) {
			addCriterion("PRODUCT_CODE not between", value1, value2,
					"productCode");
			return this;
		}

		public Criteria andTradeTimeIsNull() {
			addCriterion("TRADE_TIME is null");
			return this;
		}

		public Criteria andTradeTimeIsNotNull() {
			addCriterion("TRADE_TIME is not null");
			return this;
		}

		public Criteria andTradeTimeEqualTo(Long value) {
			addCriterion("TRADE_TIME =", value, "tradeTime");
			return this;
		}

		public Criteria andTradeTimeNotEqualTo(Long value) {
			addCriterion("TRADE_TIME <>", value, "tradeTime");
			return this;
		}

		public Criteria andTradeTimeGreaterThan(Long value) {
			addCriterion("TRADE_TIME >", value, "tradeTime");
			return this;
		}

		public Criteria andTradeTimeGreaterThanOrEqualTo(Long value) {
			addCriterion("TRADE_TIME >=", value, "tradeTime");
			return this;
		}

		public Criteria andTradeTimeLessThan(Long value) {
			addCriterion("TRADE_TIME <", value, "tradeTime");
			return this;
		}

		public Criteria andTradeTimeLessThanOrEqualTo(Long value) {
			addCriterion("TRADE_TIME <=", value, "tradeTime");
			return this;
		}

		public Criteria andTradeTimeIn(List values) {
			addCriterion("TRADE_TIME in", values, "tradeTime");
			return this;
		}

		public Criteria andTradeTimeNotIn(List values) {
			addCriterion("TRADE_TIME not in", values, "tradeTime");
			return this;
		}

		public Criteria andTradeTimeBetween(Long value1, Long value2) {
			addCriterion("TRADE_TIME between", value1, value2, "tradeTime");
			return this;
		}

		public Criteria andTradeTimeNotBetween(Long value1, Long value2) {
			addCriterion("TRADE_TIME not between", value1, value2, "tradeTime");
			return this;
		}

		public Criteria andTradeTypeIsNull() {
			addCriterion("TRADE_TYPE is null");
			return this;
		}

		public Criteria andTradeTypeIsNotNull() {
			addCriterion("TRADE_TYPE is not null");
			return this;
		}

		public Criteria andTradeTypeEqualTo(String value) {
			addCriterion("TRADE_TYPE =", value, "tradeType");
			return this;
		}

		public Criteria andTradeTypeNotEqualTo(String value) {
			addCriterion("TRADE_TYPE <>", value, "tradeType");
			return this;
		}

		public Criteria andTradeTypeGreaterThan(String value) {
			addCriterion("TRADE_TYPE >", value, "tradeType");
			return this;
		}

		public Criteria andTradeTypeGreaterThanOrEqualTo(String value) {
			addCriterion("TRADE_TYPE >=", value, "tradeType");
			return this;
		}

		public Criteria andTradeTypeLessThan(String value) {
			addCriterion("TRADE_TYPE <", value, "tradeType");
			return this;
		}

		public Criteria andTradeTypeLessThanOrEqualTo(String value) {
			addCriterion("TRADE_TYPE <=", value, "tradeType");
			return this;
		}

		public Criteria andTradeTypeLike(String value) {
			addCriterion("TRADE_TYPE like", value, "tradeType");
			return this;
		}

		public Criteria andTradeTypeNotLike(String value) {
			addCriterion("TRADE_TYPE not like", value, "tradeType");
			return this;
		}

		public Criteria andTradeTypeIn(List values) {
			addCriterion("TRADE_TYPE in", values, "tradeType");
			return this;
		}

		public Criteria andTradeTypeNotIn(List values) {
			addCriterion("TRADE_TYPE not in", values, "tradeType");
			return this;
		}

		public Criteria andTradeTypeBetween(String value1, String value2) {
			addCriterion("TRADE_TYPE between", value1, value2, "tradeType");
			return this;
		}

		public Criteria andTradeTypeNotBetween(String value1, String value2) {
			addCriterion("TRADE_TYPE not between", value1, value2, "tradeType");
			return this;
		}

		public Criteria andTradeCountIsNull() {
			addCriterion("TRADE_COUNT is null");
			return this;
		}

		public Criteria andTradeCountIsNotNull() {
			addCriterion("TRADE_COUNT is not null");
			return this;
		}

		public Criteria andTradeCountEqualTo(Long value) {
			addCriterion("TRADE_COUNT =", value, "tradeCount");
			return this;
		}

		public Criteria andTradeCountNotEqualTo(Long value) {
			addCriterion("TRADE_COUNT <>", value, "tradeCount");
			return this;
		}

		public Criteria andTradeCountGreaterThan(Long value) {
			addCriterion("TRADE_COUNT >", value, "tradeCount");
			return this;
		}

		public Criteria andTradeCountGreaterThanOrEqualTo(Long value) {
			addCriterion("TRADE_COUNT >=", value, "tradeCount");
			return this;
		}

		public Criteria andTradeCountLessThan(Long value) {
			addCriterion("TRADE_COUNT <", value, "tradeCount");
			return this;
		}

		public Criteria andTradeCountLessThanOrEqualTo(Long value) {
			addCriterion("TRADE_COUNT <=", value, "tradeCount");
			return this;
		}

		public Criteria andTradeCountIn(List values) {
			addCriterion("TRADE_COUNT in", values, "tradeCount");
			return this;
		}

		public Criteria andTradeCountNotIn(List values) {
			addCriterion("TRADE_COUNT not in", values, "tradeCount");
			return this;
		}

		public Criteria andTradeCountBetween(Long value1, Long value2) {
			addCriterion("TRADE_COUNT between", value1, value2, "tradeCount");
			return this;
		}

		public Criteria andTradeCountNotBetween(Long value1, Long value2) {
			addCriterion("TRADE_COUNT not between", value1, value2,
					"tradeCount");
			return this;
		}

		public Criteria andRebatePolicyStartTimeIsNull() {
			addCriterion("REBATE_POLICY_START_TIME is null");
			return this;
		}

		public Criteria andRebatePolicyStartTimeIsNotNull() {
			addCriterion("REBATE_POLICY_START_TIME is not null");
			return this;
		}

		public Criteria andRebatePolicyStartTimeEqualTo(Long value) {
			addCriterion("REBATE_POLICY_START_TIME =", value,
					"rebatePolicyStartTime");
			return this;
		}

		public Criteria andRebatePolicyStartTimeNotEqualTo(Long value) {
			addCriterion("REBATE_POLICY_START_TIME <>", value,
					"rebatePolicyStartTime");
			return this;
		}

		public Criteria andRebatePolicyStartTimeGreaterThan(Long value) {
			addCriterion("REBATE_POLICY_START_TIME >", value,
					"rebatePolicyStartTime");
			return this;
		}

		public Criteria andRebatePolicyStartTimeGreaterThanOrEqualTo(Long value) {
			addCriterion("REBATE_POLICY_START_TIME >=", value,
					"rebatePolicyStartTime");
			return this;
		}

		public Criteria andRebatePolicyStartTimeLessThan(Long value) {
			addCriterion("REBATE_POLICY_START_TIME <", value,
					"rebatePolicyStartTime");
			return this;
		}

		public Criteria andRebatePolicyStartTimeLessThanOrEqualTo(Long value) {
			addCriterion("REBATE_POLICY_START_TIME <=", value,
					"rebatePolicyStartTime");
			return this;
		}

		public Criteria andRebatePolicyStartTimeIn(List values) {
			addCriterion("REBATE_POLICY_START_TIME in", values,
					"rebatePolicyStartTime");
			return this;
		}

		public Criteria andRebatePolicyStartTimeNotIn(List values) {
			addCriterion("REBATE_POLICY_START_TIME not in", values,
					"rebatePolicyStartTime");
			return this;
		}

		public Criteria andRebatePolicyStartTimeBetween(Long value1, Long value2) {
			addCriterion("REBATE_POLICY_START_TIME between", value1, value2,
					"rebatePolicyStartTime");
			return this;
		}

		public Criteria andRebatePolicyStartTimeNotBetween(Long value1,
				Long value2) {
			addCriterion("REBATE_POLICY_START_TIME not between", value1,
					value2, "rebatePolicyStartTime");
			return this;
		}

		public Criteria andRebatePolicyEndTimeIsNull() {
			addCriterion("REBATE_POLICY_END_TIME is null");
			return this;
		}

		public Criteria andRebatePolicyEndTimeIsNotNull() {
			addCriterion("REBATE_POLICY_END_TIME is not null");
			return this;
		}

		public Criteria andRebatePolicyEndTimeEqualTo(Long value) {
			addCriterion("REBATE_POLICY_END_TIME =", value,
					"rebatePolicyEndTime");
			return this;
		}

		public Criteria andRebatePolicyEndTimeNotEqualTo(Long value) {
			addCriterion("REBATE_POLICY_END_TIME <>", value,
					"rebatePolicyEndTime");
			return this;
		}

		public Criteria andRebatePolicyEndTimeGreaterThan(Long value) {
			addCriterion("REBATE_POLICY_END_TIME >", value,
					"rebatePolicyEndTime");
			return this;
		}

		public Criteria andRebatePolicyEndTimeGreaterThanOrEqualTo(Long value) {
			addCriterion("REBATE_POLICY_END_TIME >=", value,
					"rebatePolicyEndTime");
			return this;
		}

		public Criteria andRebatePolicyEndTimeLessThan(Long value) {
			addCriterion("REBATE_POLICY_END_TIME <", value,
					"rebatePolicyEndTime");
			return this;
		}

		public Criteria andRebatePolicyEndTimeLessThanOrEqualTo(Long value) {
			addCriterion("REBATE_POLICY_END_TIME <=", value,
					"rebatePolicyEndTime");
			return this;
		}

		public Criteria andRebatePolicyEndTimeIn(List values) {
			addCriterion("REBATE_POLICY_END_TIME in", values,
					"rebatePolicyEndTime");
			return this;
		}

		public Criteria andRebatePolicyEndTimeNotIn(List values) {
			addCriterion("REBATE_POLICY_END_TIME not in", values,
					"rebatePolicyEndTime");
			return this;
		}

		public Criteria andRebatePolicyEndTimeBetween(Long value1, Long value2) {
			addCriterion("REBATE_POLICY_END_TIME between", value1, value2,
					"rebatePolicyEndTime");
			return this;
		}

		public Criteria andRebatePolicyEndTimeNotBetween(Long value1,
				Long value2) {
			addCriterion("REBATE_POLICY_END_TIME not between", value1, value2,
					"rebatePolicyEndTime");
			return this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("REMARK is null");
			return this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("REMARK is not null");
			return this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("REMARK =", value, "remark");
			return this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("REMARK <>", value, "remark");
			return this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("REMARK >", value, "remark");
			return this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("REMARK >=", value, "remark");
			return this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("REMARK <", value, "remark");
			return this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("REMARK <=", value, "remark");
			return this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("REMARK like", value, "remark");
			return this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("REMARK not like", value, "remark");
			return this;
		}

		public Criteria andRemarkIn(List values) {
			addCriterion("REMARK in", values, "remark");
			return this;
		}

		public Criteria andRemarkNotIn(List values) {
			addCriterion("REMARK not in", values, "remark");
			return this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("REMARK between", value1, value2, "remark");
			return this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("REMARK not between", value1, value2, "remark");
			return this;
		}

		public Criteria andPolicyIdIsNull() {
			addCriterion("POLICY_ID is null");
			return this;
		}

		public Criteria andPolicyIdIsNotNull() {
			addCriterion("POLICY_ID is not null");
			return this;
		}

		public Criteria andPolicyIdEqualTo(String value) {
			addCriterion("POLICY_ID =", value, "policyId");
			return this;
		}

		public Criteria andPolicyIdNotEqualTo(String value) {
			addCriterion("POLICY_ID <>", value, "policyId");
			return this;
		}

		public Criteria andPolicyIdGreaterThan(String value) {
			addCriterion("POLICY_ID >", value, "policyId");
			return this;
		}

		public Criteria andPolicyIdGreaterThanOrEqualTo(String value) {
			addCriterion("POLICY_ID >=", value, "policyId");
			return this;
		}

		public Criteria andPolicyIdLessThan(String value) {
			addCriterion("POLICY_ID <", value, "policyId");
			return this;
		}

		public Criteria andPolicyIdLessThanOrEqualTo(String value) {
			addCriterion("POLICY_ID <=", value, "policyId");
			return this;
		}

		public Criteria andPolicyIdLike(String value) {
			addCriterion("POLICY_ID like", value, "policyId");
			return this;
		}

		public Criteria andPolicyIdNotLike(String value) {
			addCriterion("POLICY_ID not like", value, "policyId");
			return this;
		}

		public Criteria andPolicyIdIn(List values) {
			addCriterion("POLICY_ID in", values, "policyId");
			return this;
		}

		public Criteria andPolicyIdNotIn(List values) {
			addCriterion("POLICY_ID not in", values, "policyId");
			return this;
		}

		public Criteria andPolicyIdBetween(String value1, String value2) {
			addCriterion("POLICY_ID between", value1, value2, "policyId");
			return this;
		}

		public Criteria andPolicyIdNotBetween(String value1, String value2) {
			addCriterion("POLICY_ID not between", value1, value2, "policyId");
			return this;
		}

		public Criteria andCardIdIsNull() {
			addCriterion("CARD_ID is null");
			return this;
		}

		public Criteria andCardIdIsNotNull() {
			addCriterion("CARD_ID is not null");
			return this;
		}

		public Criteria andCardIdEqualTo(String value) {
			addCriterion("CARD_ID =", value, "cardId");
			return this;
		}

		public Criteria andCardIdNotEqualTo(String value) {
			addCriterion("CARD_ID <>", value, "cardId");
			return this;
		}

		public Criteria andCardIdGreaterThan(String value) {
			addCriterion("CARD_ID >", value, "cardId");
			return this;
		}

		public Criteria andCardIdGreaterThanOrEqualTo(String value) {
			addCriterion("CARD_ID >=", value, "cardId");
			return this;
		}

		public Criteria andCardIdLessThan(String value) {
			addCriterion("CARD_ID <", value, "cardId");
			return this;
		}

		public Criteria andCardIdLessThanOrEqualTo(String value) {
			addCriterion("CARD_ID <=", value, "cardId");
			return this;
		}

		public Criteria andCardIdLike(String value) {
			addCriterion("CARD_ID like", value, "cardId");
			return this;
		}

		public Criteria andCardIdNotLike(String value) {
			addCriterion("CARD_ID not like", value, "cardId");
			return this;
		}

		public Criteria andCardIdIn(List values) {
			addCriterion("CARD_ID in", values, "cardId");
			return this;
		}

		public Criteria andCardIdNotIn(List values) {
			addCriterion("CARD_ID not in", values, "cardId");
			return this;
		}

		public Criteria andCardIdBetween(String value1, String value2) {
			addCriterion("CARD_ID between", value1, value2, "cardId");
			return this;
		}

		public Criteria andCardIdNotBetween(String value1, String value2) {
			addCriterion("CARD_ID not between", value1, value2, "cardId");
			return this;
		}

		public Criteria andCardTypeIsNull() {
			addCriterion("CARD_TYPE is null");
			return this;
		}

		public Criteria andCardTypeIsNotNull() {
			addCriterion("CARD_TYPE is not null");
			return this;
		}

		public Criteria andCardTypeEqualTo(String value) {
			addCriterion("CARD_TYPE =", value, "cardType");
			return this;
		}

		public Criteria andCardTypeNotEqualTo(String value) {
			addCriterion("CARD_TYPE <>", value, "cardType");
			return this;
		}

		public Criteria andCardTypeGreaterThan(String value) {
			addCriterion("CARD_TYPE >", value, "cardType");
			return this;
		}

		public Criteria andCardTypeGreaterThanOrEqualTo(String value) {
			addCriterion("CARD_TYPE >=", value, "cardType");
			return this;
		}

		public Criteria andCardTypeLessThan(String value) {
			addCriterion("CARD_TYPE <", value, "cardType");
			return this;
		}

		public Criteria andCardTypeLessThanOrEqualTo(String value) {
			addCriterion("CARD_TYPE <=", value, "cardType");
			return this;
		}

		public Criteria andCardTypeLike(String value) {
			addCriterion("CARD_TYPE like", value, "cardType");
			return this;
		}

		public Criteria andCardTypeNotLike(String value) {
			addCriterion("CARD_TYPE not like", value, "cardType");
			return this;
		}

		public Criteria andCardTypeIn(List values) {
			addCriterion("CARD_TYPE in", values, "cardType");
			return this;
		}

		public Criteria andCardTypeNotIn(List values) {
			addCriterion("CARD_TYPE not in", values, "cardType");
			return this;
		}

		public Criteria andCardTypeBetween(String value1, String value2) {
			addCriterion("CARD_TYPE between", value1, value2, "cardType");
			return this;
		}

		public Criteria andCardTypeNotBetween(String value1, String value2) {
			addCriterion("CARD_TYPE not between", value1, value2, "cardType");
			return this;
		}

		public Criteria andCardNoIsNull() {
			addCriterion("CARD_NO is null");
			return this;
		}

		public Criteria andCardNoIsNotNull() {
			addCriterion("CARD_NO is not null");
			return this;
		}

		public Criteria andCardNoEqualTo(String value) {
			addCriterion("CARD_NO =", value, "cardNo");
			return this;
		}

		public Criteria andCardNoNotEqualTo(String value) {
			addCriterion("CARD_NO <>", value, "cardNo");
			return this;
		}

		public Criteria andCardNoGreaterThan(String value) {
			addCriterion("CARD_NO >", value, "cardNo");
			return this;
		}

		public Criteria andCardNoGreaterThanOrEqualTo(String value) {
			addCriterion("CARD_NO >=", value, "cardNo");
			return this;
		}

		public Criteria andCardNoLessThan(String value) {
			addCriterion("CARD_NO <", value, "cardNo");
			return this;
		}

		public Criteria andCardNoLessThanOrEqualTo(String value) {
			addCriterion("CARD_NO <=", value, "cardNo");
			return this;
		}

		public Criteria andCardNoLike(String value) {
			addCriterion("CARD_NO like", value, "cardNo");
			return this;
		}

		public Criteria andCardNoNotLike(String value) {
			addCriterion("CARD_NO not like", value, "cardNo");
			return this;
		}

		public Criteria andCardNoIn(List values) {
			addCriterion("CARD_NO in", values, "cardNo");
			return this;
		}

		public Criteria andCardNoNotIn(List values) {
			addCriterion("CARD_NO not in", values, "cardNo");
			return this;
		}

		public Criteria andCardNoBetween(String value1, String value2) {
			addCriterion("CARD_NO between", value1, value2, "cardNo");
			return this;
		}

		public Criteria andCardNoNotBetween(String value1, String value2) {
			addCriterion("CARD_NO not between", value1, value2, "cardNo");
			return this;
		}
	}
}