package com.ctfo.yppt.baseservice.trade.beans;

import com.ctfo.common.models.BaseSerializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlElement;

public class ICCardTradeInfoHistory extends BaseSerializable {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.ID DB Comment: uuid
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "uuid", required = false)
	private String id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.MERCHANT_TYPE DB Comment: 商户类型(中石油/中石化)
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "商户类型(中石油/中石化)", required = false)
	private String merchantType;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.USER_ID DB Comment: 用户id
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "用户id", required = false)
	private String userId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.USER_REG_PHONE DB Comment: 注册手机号
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "注册手机号", required = false)
	private String userRegPhone;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.USER_NAME DB Comment: 用户姓名
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "用户姓名", required = false)
	private String userName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.RECHARGE_APPLY_ID DB Comment: 充值申请id(如果是充值类型,则此字段必填)
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "充值申请id(如果是充值类型,则此字段必填)", required = false)
	private String rechargeApplyId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.VEHICLE_ID DB Comment: 车辆id
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "车辆id", required = false)
	private String vehicleId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.VEHICLE_NO DB Comment: 车牌号
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "车牌号", required = false)
	private String vehicleNo;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.VEHICLE_COLOR DB Comment: 车牌颜色
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "车牌颜色", required = false)
	private String vehicleColor;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_NAME DB Comment: 交易类型名称
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "交易类型名称", required = false)
	private String tradeName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_TYPE DB Comment: 交易类型(码表:1:圈存，2:加油,3:充值,4:分配)
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "交易类型(码表:1:圈存，2:加油,3:充值,4:分配)", required = false)
	private String tradeType;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_TIME DB Comment: 交易时间
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "交易时间", required = false)
	private Long tradeTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_MONEY DB Comment: 交易金额
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "交易金额", required = false)
	private BigDecimal tradeMoney;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.CARD_BALANCE DB Comment: 交易后余额
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "交易后余额", required = false)
	private BigDecimal cardBalance;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.PRODUCT_PRICE DB Comment: 商品单价
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "商品单价", required = false)
	private BigDecimal productPrice;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.PRODUCT_TOTAL_PRICE DB Comment: 商品总价
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "商品总价", required = false)
	private BigDecimal productTotalPrice;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_STATE DB Comment: 交易状态
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "交易状态", required = false)
	private String tradeState;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_ADRESS DB Comment: 交易地点
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "交易地点", required = false)
	private String tradeAdress;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.CARD_ID DB Comment: 申请发卡卡号
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "申请发卡卡号", required = false)
	private String cardId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.CARD_NO DB Comment: 卡号
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "卡号", required = false)
	private String cardNo;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.CARD_TYPE DB Comment: 卡类型
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "卡类型", required = false)
	private String cardType;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.MAIN_CARD_ID DB Comment: 主卡卡id
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "主卡卡id", required = false)
	private String mainCardId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.MAIN_CARD_NUM DB Comment: 主卡卡号
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "主卡卡号", required = false)
	private String mainCardNum;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_PROVINCE_CODE DB Comment: 交易省地点编码
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "交易省地点编码", required = false)
	private String tradeProvinceCode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.MERCHANT_ID DB Comment: 商户ID
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "商户ID", required = false)
	private String merchantId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.MERCHANT_CODE DB Comment: 商户编码
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "商户编码", required = false)
	private String merchantCode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.MERCHANT_NAME DB Comment: 商户名称
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "商户名称", required = false)
	private String merchantName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.STORE_ID DB Comment: 门店id
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "门店id", required = false)
	private String storeId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.STORE_CODE DB Comment: 门店编码
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "门店编码", required = false)
	private String storeCode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.STORE_NAME DB Comment: 门店名称
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "门店名称", required = false)
	private String storeName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.CREATE_TIME DB Comment: 创建时间
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "创建时间", required = false)
	private Long createTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.MODIFIED_TIME DB Comment: 修改时间
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "修改时间", required = false)
	private Long modifiedTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.OPEN_CARD_OFFICE_CODE DB Comment: 开卡机构ID
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "开卡机构ID", required = false)
	private String openCardOfficeCode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.SYMBOL DB Comment: 返利状态(0:已返利,1:未返利）
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "返利状态(0:已返利,1:未返利）", required = false)
	private String symbol;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.INVOICE_ID DB Comment: 开票ID
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "开票ID", required = false)
	private String invoiceId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_SEQ_NO DB Comment: 交易流水号
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "交易流水号", required = false)
	private String tradeSeqNo;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.PRODUCT_NUM DB Comment: 交易商品数量
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "交易商品数量", required = false)
	private Long productNum;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.PRODUCT_NAME DB Comment: 交易商品名称
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "交易商品名称", required = false)
	private String productName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.PRODUCT_CODE DB Comment: 商品编码
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "商品编码", required = false)
	private String productCode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.OWN_ORG DB Comment: 所属组织编码
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "所属组织编码", required = false)
	private String ownOrg;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.CARD_AREA_CODE DB Comment: 发卡地区（省份）
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "发卡地区（省份）", required = false)
	private String cardAreaCode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_IC_CARD_TRADE_INFO_HISTORY.CARD_AREA_NAME DB Comment: 发卡地区名称（省份）
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	@XmlElement(name = "发卡地区名称（省份）", required = false)
	private String cardAreaName;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.ID
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.ID
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.ID
	 * @param id  the value for TB_IC_CARD_TRADE_INFO_HISTORY.ID
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldId() {
		return "ID";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.MERCHANT_TYPE
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.MERCHANT_TYPE
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public String getMerchantType() {
		return merchantType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.MERCHANT_TYPE
	 * @param merchantType  the value for TB_IC_CARD_TRADE_INFO_HISTORY.MERCHANT_TYPE
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setMerchantType(String merchantType) {
		this.merchantType = merchantType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldMerchantType() {
		return "MERCHANT_TYPE";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.USER_ID
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.USER_ID
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.USER_ID
	 * @param userId  the value for TB_IC_CARD_TRADE_INFO_HISTORY.USER_ID
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldUserId() {
		return "USER_ID";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.USER_REG_PHONE
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.USER_REG_PHONE
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public String getUserRegPhone() {
		return userRegPhone;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.USER_REG_PHONE
	 * @param userRegPhone  the value for TB_IC_CARD_TRADE_INFO_HISTORY.USER_REG_PHONE
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setUserRegPhone(String userRegPhone) {
		this.userRegPhone = userRegPhone;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldUserRegPhone() {
		return "USER_REG_PHONE";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.USER_NAME
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.USER_NAME
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.USER_NAME
	 * @param userName  the value for TB_IC_CARD_TRADE_INFO_HISTORY.USER_NAME
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldUserName() {
		return "USER_NAME";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.RECHARGE_APPLY_ID
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.RECHARGE_APPLY_ID
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public String getRechargeApplyId() {
		return rechargeApplyId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.RECHARGE_APPLY_ID
	 * @param rechargeApplyId  the value for TB_IC_CARD_TRADE_INFO_HISTORY.RECHARGE_APPLY_ID
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setRechargeApplyId(String rechargeApplyId) {
		this.rechargeApplyId = rechargeApplyId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldRechargeApplyId() {
		return "RECHARGE_APPLY_ID";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.VEHICLE_ID
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.VEHICLE_ID
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public String getVehicleId() {
		return vehicleId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.VEHICLE_ID
	 * @param vehicleId  the value for TB_IC_CARD_TRADE_INFO_HISTORY.VEHICLE_ID
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setVehicleId(String vehicleId) {
		this.vehicleId = vehicleId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldVehicleId() {
		return "VEHICLE_ID";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.VEHICLE_NO
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.VEHICLE_NO
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public String getVehicleNo() {
		return vehicleNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.VEHICLE_NO
	 * @param vehicleNo  the value for TB_IC_CARD_TRADE_INFO_HISTORY.VEHICLE_NO
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setVehicleNo(String vehicleNo) {
		this.vehicleNo = vehicleNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldVehicleNo() {
		return "VEHICLE_NO";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.VEHICLE_COLOR
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.VEHICLE_COLOR
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public String getVehicleColor() {
		return vehicleColor;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.VEHICLE_COLOR
	 * @param vehicleColor  the value for TB_IC_CARD_TRADE_INFO_HISTORY.VEHICLE_COLOR
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setVehicleColor(String vehicleColor) {
		this.vehicleColor = vehicleColor;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldVehicleColor() {
		return "VEHICLE_COLOR";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_NAME
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_NAME
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public String getTradeName() {
		return tradeName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_NAME
	 * @param tradeName  the value for TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_NAME
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setTradeName(String tradeName) {
		this.tradeName = tradeName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldTradeName() {
		return "TRADE_NAME";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_TYPE
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_TYPE
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public String getTradeType() {
		return tradeType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_TYPE
	 * @param tradeType  the value for TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_TYPE
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setTradeType(String tradeType) {
		this.tradeType = tradeType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldTradeType() {
		return "TRADE_TYPE";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_TIME
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_TIME
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public Long getTradeTime() {
		return tradeTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_TIME
	 * @param tradeTime  the value for TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_TIME
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setTradeTime(Long tradeTime) {
		this.tradeTime = tradeTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldTradeTime() {
		return "TRADE_TIME";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_MONEY
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_MONEY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public BigDecimal getTradeMoney() {
		return tradeMoney;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_MONEY
	 * @param tradeMoney  the value for TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_MONEY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setTradeMoney(BigDecimal tradeMoney) {
		this.tradeMoney = tradeMoney;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldTradeMoney() {
		return "TRADE_MONEY";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.CARD_BALANCE
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.CARD_BALANCE
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public BigDecimal getCardBalance() {
		return cardBalance;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.CARD_BALANCE
	 * @param cardBalance  the value for TB_IC_CARD_TRADE_INFO_HISTORY.CARD_BALANCE
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setCardBalance(BigDecimal cardBalance) {
		this.cardBalance = cardBalance;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldCardBalance() {
		return "CARD_BALANCE";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.PRODUCT_PRICE
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.PRODUCT_PRICE
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public BigDecimal getProductPrice() {
		return productPrice;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.PRODUCT_PRICE
	 * @param productPrice  the value for TB_IC_CARD_TRADE_INFO_HISTORY.PRODUCT_PRICE
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setProductPrice(BigDecimal productPrice) {
		this.productPrice = productPrice;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldProductPrice() {
		return "PRODUCT_PRICE";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.PRODUCT_TOTAL_PRICE
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.PRODUCT_TOTAL_PRICE
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public BigDecimal getProductTotalPrice() {
		return productTotalPrice;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.PRODUCT_TOTAL_PRICE
	 * @param productTotalPrice  the value for TB_IC_CARD_TRADE_INFO_HISTORY.PRODUCT_TOTAL_PRICE
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setProductTotalPrice(BigDecimal productTotalPrice) {
		this.productTotalPrice = productTotalPrice;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldProductTotalPrice() {
		return "PRODUCT_TOTAL_PRICE";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_STATE
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_STATE
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public String getTradeState() {
		return tradeState;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_STATE
	 * @param tradeState  the value for TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_STATE
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setTradeState(String tradeState) {
		this.tradeState = tradeState;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldTradeState() {
		return "TRADE_STATE";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_ADRESS
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_ADRESS
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public String getTradeAdress() {
		return tradeAdress;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_ADRESS
	 * @param tradeAdress  the value for TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_ADRESS
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setTradeAdress(String tradeAdress) {
		this.tradeAdress = tradeAdress;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldTradeAdress() {
		return "TRADE_ADRESS";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.CARD_ID
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.CARD_ID
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public String getCardId() {
		return cardId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.CARD_ID
	 * @param cardId  the value for TB_IC_CARD_TRADE_INFO_HISTORY.CARD_ID
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setCardId(String cardId) {
		this.cardId = cardId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldCardId() {
		return "CARD_ID";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.CARD_NO
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.CARD_NO
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public String getCardNo() {
		return cardNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.CARD_NO
	 * @param cardNo  the value for TB_IC_CARD_TRADE_INFO_HISTORY.CARD_NO
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setCardNo(String cardNo) {
		this.cardNo = cardNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldCardNo() {
		return "CARD_NO";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.CARD_TYPE
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.CARD_TYPE
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public String getCardType() {
		return cardType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.CARD_TYPE
	 * @param cardType  the value for TB_IC_CARD_TRADE_INFO_HISTORY.CARD_TYPE
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setCardType(String cardType) {
		this.cardType = cardType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldCardType() {
		return "CARD_TYPE";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.MAIN_CARD_ID
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.MAIN_CARD_ID
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public String getMainCardId() {
		return mainCardId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.MAIN_CARD_ID
	 * @param mainCardId  the value for TB_IC_CARD_TRADE_INFO_HISTORY.MAIN_CARD_ID
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setMainCardId(String mainCardId) {
		this.mainCardId = mainCardId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldMainCardId() {
		return "MAIN_CARD_ID";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.MAIN_CARD_NUM
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.MAIN_CARD_NUM
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public String getMainCardNum() {
		return mainCardNum;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.MAIN_CARD_NUM
	 * @param mainCardNum  the value for TB_IC_CARD_TRADE_INFO_HISTORY.MAIN_CARD_NUM
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setMainCardNum(String mainCardNum) {
		this.mainCardNum = mainCardNum;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldMainCardNum() {
		return "MAIN_CARD_NUM";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_PROVINCE_CODE
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_PROVINCE_CODE
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public String getTradeProvinceCode() {
		return tradeProvinceCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_PROVINCE_CODE
	 * @param tradeProvinceCode  the value for TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_PROVINCE_CODE
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setTradeProvinceCode(String tradeProvinceCode) {
		this.tradeProvinceCode = tradeProvinceCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldTradeProvinceCode() {
		return "TRADE_PROVINCE_CODE";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.MERCHANT_ID
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.MERCHANT_ID
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public String getMerchantId() {
		return merchantId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.MERCHANT_ID
	 * @param merchantId  the value for TB_IC_CARD_TRADE_INFO_HISTORY.MERCHANT_ID
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setMerchantId(String merchantId) {
		this.merchantId = merchantId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldMerchantId() {
		return "MERCHANT_ID";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.MERCHANT_CODE
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.MERCHANT_CODE
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public String getMerchantCode() {
		return merchantCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.MERCHANT_CODE
	 * @param merchantCode  the value for TB_IC_CARD_TRADE_INFO_HISTORY.MERCHANT_CODE
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setMerchantCode(String merchantCode) {
		this.merchantCode = merchantCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldMerchantCode() {
		return "MERCHANT_CODE";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.MERCHANT_NAME
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.MERCHANT_NAME
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public String getMerchantName() {
		return merchantName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.MERCHANT_NAME
	 * @param merchantName  the value for TB_IC_CARD_TRADE_INFO_HISTORY.MERCHANT_NAME
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setMerchantName(String merchantName) {
		this.merchantName = merchantName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldMerchantName() {
		return "MERCHANT_NAME";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.STORE_ID
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.STORE_ID
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public String getStoreId() {
		return storeId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.STORE_ID
	 * @param storeId  the value for TB_IC_CARD_TRADE_INFO_HISTORY.STORE_ID
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setStoreId(String storeId) {
		this.storeId = storeId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldStoreId() {
		return "STORE_ID";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.STORE_CODE
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.STORE_CODE
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public String getStoreCode() {
		return storeCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.STORE_CODE
	 * @param storeCode  the value for TB_IC_CARD_TRADE_INFO_HISTORY.STORE_CODE
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setStoreCode(String storeCode) {
		this.storeCode = storeCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldStoreCode() {
		return "STORE_CODE";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.STORE_NAME
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.STORE_NAME
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public String getStoreName() {
		return storeName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.STORE_NAME
	 * @param storeName  the value for TB_IC_CARD_TRADE_INFO_HISTORY.STORE_NAME
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setStoreName(String storeName) {
		this.storeName = storeName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldStoreName() {
		return "STORE_NAME";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.CREATE_TIME
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.CREATE_TIME
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public Long getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.CREATE_TIME
	 * @param createTime  the value for TB_IC_CARD_TRADE_INFO_HISTORY.CREATE_TIME
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldCreateTime() {
		return "CREATE_TIME";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.MODIFIED_TIME
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.MODIFIED_TIME
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public Long getModifiedTime() {
		return modifiedTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.MODIFIED_TIME
	 * @param modifiedTime  the value for TB_IC_CARD_TRADE_INFO_HISTORY.MODIFIED_TIME
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setModifiedTime(Long modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldModifiedTime() {
		return "MODIFIED_TIME";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.OPEN_CARD_OFFICE_CODE
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.OPEN_CARD_OFFICE_CODE
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public String getOpenCardOfficeCode() {
		return openCardOfficeCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.OPEN_CARD_OFFICE_CODE
	 * @param openCardOfficeCode  the value for TB_IC_CARD_TRADE_INFO_HISTORY.OPEN_CARD_OFFICE_CODE
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setOpenCardOfficeCode(String openCardOfficeCode) {
		this.openCardOfficeCode = openCardOfficeCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldOpenCardOfficeCode() {
		return "OPEN_CARD_OFFICE_CODE";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.SYMBOL
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.SYMBOL
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public String getSymbol() {
		return symbol;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.SYMBOL
	 * @param symbol  the value for TB_IC_CARD_TRADE_INFO_HISTORY.SYMBOL
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldSymbol() {
		return "SYMBOL";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.INVOICE_ID
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.INVOICE_ID
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public String getInvoiceId() {
		return invoiceId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.INVOICE_ID
	 * @param invoiceId  the value for TB_IC_CARD_TRADE_INFO_HISTORY.INVOICE_ID
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setInvoiceId(String invoiceId) {
		this.invoiceId = invoiceId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldInvoiceId() {
		return "INVOICE_ID";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_SEQ_NO
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_SEQ_NO
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public String getTradeSeqNo() {
		return tradeSeqNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_SEQ_NO
	 * @param tradeSeqNo  the value for TB_IC_CARD_TRADE_INFO_HISTORY.TRADE_SEQ_NO
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setTradeSeqNo(String tradeSeqNo) {
		this.tradeSeqNo = tradeSeqNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldTradeSeqNo() {
		return "TRADE_SEQ_NO";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.PRODUCT_NUM
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.PRODUCT_NUM
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public Long getProductNum() {
		return productNum;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.PRODUCT_NUM
	 * @param productNum  the value for TB_IC_CARD_TRADE_INFO_HISTORY.PRODUCT_NUM
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setProductNum(Long productNum) {
		this.productNum = productNum;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldProductNum() {
		return "PRODUCT_NUM";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.PRODUCT_NAME
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.PRODUCT_NAME
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public String getProductName() {
		return productName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.PRODUCT_NAME
	 * @param productName  the value for TB_IC_CARD_TRADE_INFO_HISTORY.PRODUCT_NAME
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setProductName(String productName) {
		this.productName = productName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldProductName() {
		return "PRODUCT_NAME";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.PRODUCT_CODE
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.PRODUCT_CODE
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public String getProductCode() {
		return productCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.PRODUCT_CODE
	 * @param productCode  the value for TB_IC_CARD_TRADE_INFO_HISTORY.PRODUCT_CODE
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldProductCode() {
		return "PRODUCT_CODE";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.OWN_ORG
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.OWN_ORG
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public String getOwnOrg() {
		return ownOrg;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.OWN_ORG
	 * @param ownOrg  the value for TB_IC_CARD_TRADE_INFO_HISTORY.OWN_ORG
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setOwnOrg(String ownOrg) {
		this.ownOrg = ownOrg;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldOwnOrg() {
		return "OWN_ORG";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.CARD_AREA_CODE
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.CARD_AREA_CODE
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public String getCardAreaCode() {
		return cardAreaCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.CARD_AREA_CODE
	 * @param cardAreaCode  the value for TB_IC_CARD_TRADE_INFO_HISTORY.CARD_AREA_CODE
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setCardAreaCode(String cardAreaCode) {
		this.cardAreaCode = cardAreaCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldCardAreaCode() {
		return "CARD_AREA_CODE";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.CARD_AREA_NAME
	 * @return  the value of TB_IC_CARD_TRADE_INFO_HISTORY.CARD_AREA_NAME
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public String getCardAreaName() {
		return cardAreaName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column TB_IC_CARD_TRADE_INFO_HISTORY.CARD_AREA_NAME
	 * @param cardAreaName  the value for TB_IC_CARD_TRADE_INFO_HISTORY.CARD_AREA_NAME
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void setCardAreaName(String cardAreaName) {
		this.cardAreaName = cardAreaName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String fieldCardAreaName() {
		return "CARD_AREA_NAME";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public ICCardTradeInfoHistory() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String tableName() {
		return "TB_IC_CARD_TRADE_INFO_HISTORY";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public static String daoInterface() {
		return "com.ctfo.yppt.baseservice.dao.trade.ICCardTradeInfoHistoryDAO";
	}
}