package com.ctfo.yppt.baseservice.dao.trade;

import com.ctfo.yppt.baseservice.trade.beans.ICCardTradeInfoHistory;
import com.ctfo.yppt.baseservice.trade.beans.ICCardTradeInfoHistoryExample;
import com.ctfo.yppt.baseservice.trade.beans.ICCardTradeInfoHistoryExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ICCardTradeInfoHistoryDAOImpl extends SqlMapClientDaoSupport implements ICCardTradeInfoHistoryDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public ICCardTradeInfoHistoryDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public void insert(ICCardTradeInfoHistory record) {
		getSqlMapClientTemplate().insert(
				"TB_IC_CARD_TRADE_INFO_HISTORY.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public int updateByPrimaryKey(ICCardTradeInfoHistory record) {
		int rows = getSqlMapClientTemplate()
				.update("TB_IC_CARD_TRADE_INFO_HISTORY.abatorgenerated_updateByPrimaryKey",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public int updateByPrimaryKeySelective(ICCardTradeInfoHistory record) {
		int rows = getSqlMapClientTemplate()
				.update("TB_IC_CARD_TRADE_INFO_HISTORY.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public List selectByExample(ICCardTradeInfoHistoryExample example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_IC_CARD_TRADE_INFO_HISTORY.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public ICCardTradeInfoHistory selectByPrimaryKey(String id) {
		ICCardTradeInfoHistory key = new ICCardTradeInfoHistory() {
		};
		key.setId(id);
		ICCardTradeInfoHistory record = (ICCardTradeInfoHistory) getSqlMapClientTemplate()
				.queryForObject(
						"TB_IC_CARD_TRADE_INFO_HISTORY.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public int deleteByExample(ICCardTradeInfoHistoryExample example) {
		int rows = getSqlMapClientTemplate()
				.delete("TB_IC_CARD_TRADE_INFO_HISTORY.abatorgenerated_deleteByExample",
						example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public int deleteByPrimaryKey(String id) {
		ICCardTradeInfoHistory key = new ICCardTradeInfoHistory() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate()
				.delete("TB_IC_CARD_TRADE_INFO_HISTORY.abatorgenerated_deleteByPrimaryKey",
						key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public int countByExample(ICCardTradeInfoHistoryExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_IC_CARD_TRADE_INFO_HISTORY.abatorgenerated_countByExample",
				example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public int updateByExampleSelective(ICCardTradeInfoHistory record,
			ICCardTradeInfoHistoryExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("TB_IC_CARD_TRADE_INFO_HISTORY.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public int updateByExample(ICCardTradeInfoHistory record,
			ICCardTradeInfoHistoryExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("TB_IC_CARD_TRADE_INFO_HISTORY.abatorgenerated_updateByExample",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public List selectByExampleWithPage(ICCardTradeInfoHistoryExample example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_IC_CARD_TRADE_INFO_HISTORY.abatorgenerated_selectByExamplePage",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public List selectByExampleWithPage(
			ICCardTradeInfoHistoryExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_IC_CARD_TRADE_INFO_HISTORY.abatorgenerated_selectByExampleExtendedPage",
						exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public List getKeyBy(ICCardTradeInfoHistoryExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_CARD_TRADE_INFO_HISTORY.abatorgenerated_selectKeyBy",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public String getNameSpace() {
		return "TB_IC_CARD_TRADE_INFO_HISTORY";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public List getKeyBy(ICCardTradeInfoHistoryExampleExtended example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_IC_CARD_TRADE_INFO_HISTORY.abatorgenerated_selectKeyByExtended",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	public int countByExample(ICCardTradeInfoHistoryExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject(
						"TB_IC_CARD_TRADE_INFO_HISTORY.abatorgenerated_countByExampleExtended",
						example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	private static class UpdateByExampleParms extends
			ICCardTradeInfoHistoryExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				ICCardTradeInfoHistoryExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}