package com.ctfo.yppt.baseservice.dao.trade;

import com.ctfo.yppt.baseservice.trade.beans.ICCardTradeInfo;
import com.ctfo.yppt.baseservice.trade.beans.ICCardTradeInfoExample;
import com.ctfo.yppt.baseservice.trade.beans.ICCardTradeInfoExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ICCardTradeInfoDAOImpl extends SqlMapClientDaoSupport implements ICCardTradeInfoDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:37 CST 2015
	 */
	public ICCardTradeInfoDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:37 CST 2015
	 */
	public void insert(ICCardTradeInfo record) {
		getSqlMapClientTemplate().insert(
				"TB_IC_CARD_TRADE_INFO.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:37 CST 2015
	 */
	public int updateByPrimaryKey(ICCardTradeInfo record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_IC_CARD_TRADE_INFO.abatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:37 CST 2015
	 */
	public int updateByPrimaryKeySelective(ICCardTradeInfo record) {
		int rows = getSqlMapClientTemplate()
				.update("TB_IC_CARD_TRADE_INFO.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:37 CST 2015
	 */
	public List selectByExample(ICCardTradeInfoExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_CARD_TRADE_INFO.abatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:37 CST 2015
	 */
	public ICCardTradeInfo selectByPrimaryKey(String id) {
		ICCardTradeInfo key = new ICCardTradeInfo() {
		};
		key.setId(id);
		ICCardTradeInfo record = (ICCardTradeInfo) getSqlMapClientTemplate()
				.queryForObject(
						"TB_IC_CARD_TRADE_INFO.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:37 CST 2015
	 */
	public int deleteByExample(ICCardTradeInfoExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_IC_CARD_TRADE_INFO.abatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:37 CST 2015
	 */
	public int deleteByPrimaryKey(String id) {
		ICCardTradeInfo key = new ICCardTradeInfo() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate()
				.delete("TB_IC_CARD_TRADE_INFO.abatorgenerated_deleteByPrimaryKey",
						key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:37 CST 2015
	 */
	public int countByExample(ICCardTradeInfoExample example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject(
						"TB_IC_CARD_TRADE_INFO.abatorgenerated_countByExample",
						example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:37 CST 2015
	 */
	public int updateByExampleSelective(ICCardTradeInfo record,
			ICCardTradeInfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("TB_IC_CARD_TRADE_INFO.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:37 CST 2015
	 */
	public int updateByExample(ICCardTradeInfo record,
			ICCardTradeInfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_IC_CARD_TRADE_INFO.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:37 CST 2015
	 */
	public List selectByExampleWithPage(ICCardTradeInfoExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_CARD_TRADE_INFO.abatorgenerated_selectByExamplePage",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:37 CST 2015
	 */
	public List selectByExampleWithPage(
			ICCardTradeInfoExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_IC_CARD_TRADE_INFO.abatorgenerated_selectByExampleExtendedPage",
						exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:37 CST 2015
	 */
	public List getKeyBy(ICCardTradeInfoExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_CARD_TRADE_INFO.abatorgenerated_selectKeyBy", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:37 CST 2015
	 */
	public String getNameSpace() {
		return "TB_IC_CARD_TRADE_INFO";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:37 CST 2015
	 */
	public List getKeyBy(ICCardTradeInfoExampleExtended example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_CARD_TRADE_INFO.abatorgenerated_selectKeyByExtended",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:37 CST 2015
	 */
	public int countByExample(ICCardTradeInfoExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_IC_CARD_TRADE_INFO.abatorgenerated_countByExampleExtended",
				example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table TB_IC_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:37 CST 2015
	 */
	private static class UpdateByExampleParms extends ICCardTradeInfoExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				ICCardTradeInfoExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}