package com.ctfo.yppt.baseservice.dao.trade;

import com.ctfo.yppt.baseservice.trade.beans.ICCardTradeInfoHistory;
import com.ctfo.yppt.baseservice.trade.beans.ICCardTradeInfoHistoryExample;
import com.ctfo.yppt.baseservice.trade.beans.ICCardTradeInfoHistoryExampleExtended;
import java.util.List;

public interface ICCardTradeInfoHistoryDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	void insert(ICCardTradeInfoHistory record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	int updateByPrimaryKey(ICCardTradeInfoHistory record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	int updateByPrimaryKeySelective(ICCardTradeInfoHistory record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	List selectByExample(ICCardTradeInfoHistoryExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	ICCardTradeInfoHistory selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	int deleteByExample(ICCardTradeInfoHistoryExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	int countByExample(ICCardTradeInfoHistoryExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	int updateByExampleSelective(ICCardTradeInfoHistory record,
			ICCardTradeInfoHistoryExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	int updateByExample(ICCardTradeInfoHistory record,
			ICCardTradeInfoHistoryExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	List selectByExampleWithPage(ICCardTradeInfoHistoryExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	List selectByExampleWithPage(
			ICCardTradeInfoHistoryExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	List getKeyBy(ICCardTradeInfoHistoryExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	List getKeyBy(ICCardTradeInfoHistoryExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO_HISTORY
	 * @abatorgenerated  Tue Feb 03 15:41:38 CST 2015
	 */
	int countByExample(ICCardTradeInfoHistoryExampleExtended example);
}