package com.ctfo.yppt.baseservice.dao.trade;

import com.ctfo.yppt.baseservice.trade.beans.ICCardTradeInfo;
import com.ctfo.yppt.baseservice.trade.beans.ICCardTradeInfoExample;
import com.ctfo.yppt.baseservice.trade.beans.ICCardTradeInfoExampleExtended;
import java.util.List;

public interface ICCardTradeInfoDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:37 CST 2015
	 */
	void insert(ICCardTradeInfo record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:37 CST 2015
	 */
	int updateByPrimaryKey(ICCardTradeInfo record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:37 CST 2015
	 */
	int updateByPrimaryKeySelective(ICCardTradeInfo record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:37 CST 2015
	 */
	List selectByExample(ICCardTradeInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:37 CST 2015
	 */
	ICCardTradeInfo selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:37 CST 2015
	 */
	int deleteByExample(ICCardTradeInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:37 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:37 CST 2015
	 */
	int countByExample(ICCardTradeInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:37 CST 2015
	 */
	int updateByExampleSelective(ICCardTradeInfo record,
			ICCardTradeInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:37 CST 2015
	 */
	int updateByExample(ICCardTradeInfo record, ICCardTradeInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:37 CST 2015
	 */
	List selectByExampleWithPage(ICCardTradeInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:37 CST 2015
	 */
	List selectByExampleWithPage(ICCardTradeInfoExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:37 CST 2015
	 */
	List getKeyBy(ICCardTradeInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:37 CST 2015
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:37 CST 2015
	 */
	List getKeyBy(ICCardTradeInfoExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:37 CST 2015
	 */
	int countByExample(ICCardTradeInfoExampleExtended example);
}