package com.ctfo.yppt.baseservice.dao.trade;

import com.ctfo.yppt.baseservice.trade.beans.ICCardMainTradeInfo;
import com.ctfo.yppt.baseservice.trade.beans.ICCardMainTradeInfoExample;
import com.ctfo.yppt.baseservice.trade.beans.ICCardMainTradeInfoExampleExtended;
import java.util.List;

public interface ICCardMainTradeInfoDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_MAIN_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:39 CST 2015
	 */
	void insert(ICCardMainTradeInfo record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_MAIN_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:39 CST 2015
	 */
	int updateByPrimaryKey(ICCardMainTradeInfo record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_MAIN_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:39 CST 2015
	 */
	int updateByPrimaryKeySelective(ICCardMainTradeInfo record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_MAIN_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:39 CST 2015
	 */
	List selectByExample(ICCardMainTradeInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_MAIN_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:39 CST 2015
	 */
	ICCardMainTradeInfo selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_MAIN_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:39 CST 2015
	 */
	int deleteByExample(ICCardMainTradeInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_MAIN_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:39 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_MAIN_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:39 CST 2015
	 */
	int countByExample(ICCardMainTradeInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_MAIN_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:39 CST 2015
	 */
	int updateByExampleSelective(ICCardMainTradeInfo record,
			ICCardMainTradeInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_MAIN_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:39 CST 2015
	 */
	int updateByExample(ICCardMainTradeInfo record,
			ICCardMainTradeInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_MAIN_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:39 CST 2015
	 */
	List selectByExampleWithPage(ICCardMainTradeInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_MAIN_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:39 CST 2015
	 */
	List selectByExampleWithPage(
			ICCardMainTradeInfoExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_MAIN_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:39 CST 2015
	 */
	List getKeyBy(ICCardMainTradeInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_MAIN_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:39 CST 2015
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_MAIN_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:39 CST 2015
	 */
	List getKeyBy(ICCardMainTradeInfoExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_MAIN_CARD_TRADE_INFO
	 * @abatorgenerated  Tue Feb 03 15:41:39 CST 2015
	 */
	int countByExample(ICCardMainTradeInfoExampleExtended example);
}