package com.ctfo.base.service.dao;

import com.ctfo.base.service.beans.SimpleCode;
import com.ctfo.base.service.beans.SimpleCodeExample;
import com.ctfo.base.service.beans.SimpleCodeExampleExtended;
import java.util.List;

public interface SimpleCodeDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SIMPLE_CODE
     *
     * @abatorgenerated Thu Jan 22 15:16:12 CST 2015
     */
    void insert(SimpleCode record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SIMPLE_CODE
     *
     * @abatorgenerated Thu Jan 22 15:16:12 CST 2015
     */
    int updateByPrimaryKey(SimpleCode record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SIMPLE_CODE
     *
     * @abatorgenerated Thu Jan 22 15:16:12 CST 2015
     */
    int updateByPrimaryKeySelective(SimpleCode record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SIMPLE_CODE
     *
     * @abatorgenerated Thu Jan 22 15:16:12 CST 2015
     */
    List selectByExample(SimpleCodeExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SIMPLE_CODE
     *
     * @abatorgenerated Thu Jan 22 15:16:12 CST 2015
     */
    SimpleCode selectByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SIMPLE_CODE
     *
     * @abatorgenerated Thu Jan 22 15:16:12 CST 2015
     */
    int deleteByExample(SimpleCodeExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SIMPLE_CODE
     *
     * @abatorgenerated Thu Jan 22 15:16:12 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SIMPLE_CODE
     *
     * @abatorgenerated Thu Jan 22 15:16:12 CST 2015
     */
    int countByExample(SimpleCodeExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SIMPLE_CODE
     *
     * @abatorgenerated Thu Jan 22 15:16:12 CST 2015
     */
    int updateByExampleSelective(SimpleCode record, SimpleCodeExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SIMPLE_CODE
     *
     * @abatorgenerated Thu Jan 22 15:16:12 CST 2015
     */
    int updateByExample(SimpleCode record, SimpleCodeExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SIMPLE_CODE
     *
     * @abatorgenerated Thu Jan 22 15:16:12 CST 2015
     */
    List selectByExampleWithPage(SimpleCodeExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SIMPLE_CODE
     *
     * @abatorgenerated Thu Jan 22 15:16:12 CST 2015
     */
    List selectByExampleWithPage(SimpleCodeExampleExtended exampleExtended);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SIMPLE_CODE
     *
     * @abatorgenerated Thu Jan 22 15:16:12 CST 2015
     */
    List getKeyBy(SimpleCodeExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SIMPLE_CODE
     *
     * @abatorgenerated Thu Jan 22 15:16:12 CST 2015
     */
    String getNameSpace();

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SIMPLE_CODE
     *
     * @abatorgenerated Thu Jan 22 15:16:12 CST 2015
     */
    List getKeyBy(SimpleCodeExampleExtended example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_SIMPLE_CODE
     *
     * @abatorgenerated Thu Jan 22 15:16:12 CST 2015
     */
    int countByExample(SimpleCodeExampleExtended example);
}