package com.ctfo.base.service.dao;

import com.ctfo.base.service.beans.ZoneCode;
import com.ctfo.base.service.beans.ZoneCodeExample;
import com.ctfo.base.service.beans.ZoneCodeExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ZoneCodeDAOImpl extends SqlMapClientDaoSupport implements ZoneCodeDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_ZONE_CODE
     *
     * @abatorgenerated Thu Jan 22 15:16:13 CST 2015
     */
    public ZoneCodeDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_ZONE_CODE
     *
     * @abatorgenerated Thu Jan 22 15:16:13 CST 2015
     */
    public void insert(ZoneCode record) {
        getSqlMapClientTemplate().insert("TB_ZONE_CODE.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_ZONE_CODE
     *
     * @abatorgenerated Thu Jan 22 15:16:13 CST 2015
     */
    public int updateByPrimaryKey(ZoneCode record) {
        int rows = getSqlMapClientTemplate().update("TB_ZONE_CODE.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_ZONE_CODE
     *
     * @abatorgenerated Thu Jan 22 15:16:13 CST 2015
     */
    public int updateByPrimaryKeySelective(ZoneCode record) {
        int rows = getSqlMapClientTemplate().update("TB_ZONE_CODE.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_ZONE_CODE
     *
     * @abatorgenerated Thu Jan 22 15:16:13 CST 2015
     */
    public List selectByExample(ZoneCodeExample example) {
        List list = getSqlMapClientTemplate().queryForList("TB_ZONE_CODE.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_ZONE_CODE
     *
     * @abatorgenerated Thu Jan 22 15:16:13 CST 2015
     */
    public ZoneCode selectByPrimaryKey(String id) {
        ZoneCode key = new ZoneCode(){};
        key.setId(id);
        ZoneCode record = (ZoneCode) getSqlMapClientTemplate().queryForObject("TB_ZONE_CODE.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_ZONE_CODE
     *
     * @abatorgenerated Thu Jan 22 15:16:13 CST 2015
     */
    public int deleteByExample(ZoneCodeExample example) {
        int rows = getSqlMapClientTemplate().delete("TB_ZONE_CODE.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_ZONE_CODE
     *
     * @abatorgenerated Thu Jan 22 15:16:13 CST 2015
     */
    public int deleteByPrimaryKey(String id) {
        ZoneCode key = new ZoneCode(){};
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("TB_ZONE_CODE.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_ZONE_CODE
     *
     * @abatorgenerated Thu Jan 22 15:16:13 CST 2015
     */
    public int countByExample(ZoneCodeExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("TB_ZONE_CODE.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_ZONE_CODE
     *
     * @abatorgenerated Thu Jan 22 15:16:13 CST 2015
     */
    public int updateByExampleSelective(ZoneCode record, ZoneCodeExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TB_ZONE_CODE.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_ZONE_CODE
     *
     * @abatorgenerated Thu Jan 22 15:16:13 CST 2015
     */
    public int updateByExample(ZoneCode record, ZoneCodeExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TB_ZONE_CODE.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_ZONE_CODE
     *
     * @abatorgenerated Thu Jan 22 15:16:13 CST 2015
     */
    public List selectByExampleWithPage(ZoneCodeExample example) {
        List list = getSqlMapClientTemplate().queryForList("TB_ZONE_CODE.abatorgenerated_selectByExamplePage", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_ZONE_CODE
     *
     * @abatorgenerated Thu Jan 22 15:16:13 CST 2015
     */
    public List selectByExampleWithPage(ZoneCodeExampleExtended exampleExtended) {
        List list = getSqlMapClientTemplate().queryForList("TB_ZONE_CODE.abatorgenerated_selectByExampleExtendedPage", exampleExtended);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_ZONE_CODE
     *
     * @abatorgenerated Thu Jan 22 15:16:13 CST 2015
     */
    public List getKeyBy(ZoneCodeExample example) {
        List list = getSqlMapClientTemplate().queryForList("TB_ZONE_CODE.abatorgenerated_selectKeyBy", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_ZONE_CODE
     *
     * @abatorgenerated Thu Jan 22 15:16:13 CST 2015
     */
    public String getNameSpace() {
         return "TB_ZONE_CODE";
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_ZONE_CODE
     *
     * @abatorgenerated Thu Jan 22 15:16:13 CST 2015
     */
    public List getKeyBy(ZoneCodeExampleExtended example) {
        List list = getSqlMapClientTemplate().queryForList("TB_ZONE_CODE.abatorgenerated_selectKeyByExtended", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TB_ZONE_CODE
     *
     * @abatorgenerated Thu Jan 22 15:16:13 CST 2015
     */
    public int countByExample(ZoneCodeExampleExtended example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("TB_ZONE_CODE.abatorgenerated_countByExampleExtended", example);
        return count.intValue();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table TB_ZONE_CODE
     *
     * @abatorgenerated Thu Jan 22 15:16:13 CST 2015
     */
    private static class UpdateByExampleParms extends ZoneCodeExample {
        private Object record;

        public UpdateByExampleParms(Object record, ZoneCodeExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}