package com.ctfo.yppt.baseservice.dao.invoice;

import com.ctfo.yppt.baseservice.invoice.beans.ICCardInvoiceApply;
import com.ctfo.yppt.baseservice.invoice.beans.ICCardInvoiceApplyExample;
import com.ctfo.yppt.baseservice.invoice.beans.ICCardInvoiceApplyExampleExtended;
import java.util.List;

public interface ICCardInvoiceApplyDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_INVOICE_APPLY
	 * @abatorgenerated  Mon Feb 09 12:40:31 CST 2015
	 */
	void insert(ICCardInvoiceApply record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_INVOICE_APPLY
	 * @abatorgenerated  Mon Feb 09 12:40:31 CST 2015
	 */
	int updateByPrimaryKey(ICCardInvoiceApply record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_INVOICE_APPLY
	 * @abatorgenerated  Mon Feb 09 12:40:31 CST 2015
	 */
	int updateByPrimaryKeySelective(ICCardInvoiceApply record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_INVOICE_APPLY
	 * @abatorgenerated  Mon Feb 09 12:40:31 CST 2015
	 */
	List selectByExample(ICCardInvoiceApplyExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_INVOICE_APPLY
	 * @abatorgenerated  Mon Feb 09 12:40:31 CST 2015
	 */
	ICCardInvoiceApply selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_INVOICE_APPLY
	 * @abatorgenerated  Mon Feb 09 12:40:31 CST 2015
	 */
	int deleteByExample(ICCardInvoiceApplyExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_INVOICE_APPLY
	 * @abatorgenerated  Mon Feb 09 12:40:31 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_INVOICE_APPLY
	 * @abatorgenerated  Mon Feb 09 12:40:31 CST 2015
	 */
	int countByExample(ICCardInvoiceApplyExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_INVOICE_APPLY
	 * @abatorgenerated  Mon Feb 09 12:40:31 CST 2015
	 */
	int updateByExampleSelective(ICCardInvoiceApply record,
			ICCardInvoiceApplyExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_INVOICE_APPLY
	 * @abatorgenerated  Mon Feb 09 12:40:31 CST 2015
	 */
	int updateByExample(ICCardInvoiceApply record,
			ICCardInvoiceApplyExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_INVOICE_APPLY
	 * @abatorgenerated  Mon Feb 09 12:40:31 CST 2015
	 */
	List selectByExampleWithPage(ICCardInvoiceApplyExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_INVOICE_APPLY
	 * @abatorgenerated  Mon Feb 09 12:40:31 CST 2015
	 */
	List selectByExampleWithPage(
			ICCardInvoiceApplyExampleExtended exampleExtended);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_INVOICE_APPLY
	 * @abatorgenerated  Mon Feb 09 12:40:31 CST 2015
	 */
	List getKeyBy(ICCardInvoiceApplyExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_INVOICE_APPLY
	 * @abatorgenerated  Mon Feb 09 12:40:31 CST 2015
	 */
	String getNameSpace();

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_INVOICE_APPLY
	 * @abatorgenerated  Mon Feb 09 12:40:31 CST 2015
	 */
	List getKeyBy(ICCardInvoiceApplyExampleExtended example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_INVOICE_APPLY
	 * @abatorgenerated  Mon Feb 09 12:40:31 CST 2015
	 */
	int countByExample(ICCardInvoiceApplyExampleExtended example);
}