package com.ctfo.yppt.baseservice.dao.invoice;

import com.ctfo.yppt.baseservice.invoice.beans.ICCardInvoiceApply;
import com.ctfo.yppt.baseservice.invoice.beans.ICCardInvoiceApplyExample;
import com.ctfo.yppt.baseservice.invoice.beans.ICCardInvoiceApplyExampleExtended;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ICCardInvoiceApplyDAOImpl extends SqlMapClientDaoSupport implements ICCardInvoiceApplyDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_INVOICE_APPLY
	 * @abatorgenerated  Mon Feb 09 12:40:31 CST 2015
	 */
	public ICCardInvoiceApplyDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_INVOICE_APPLY
	 * @abatorgenerated  Mon Feb 09 12:40:31 CST 2015
	 */
	public void insert(ICCardInvoiceApply record) {
		getSqlMapClientTemplate().insert(
				"TB_IC_CARD_INVOICE_APPLY.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_INVOICE_APPLY
	 * @abatorgenerated  Mon Feb 09 12:40:31 CST 2015
	 */
	public int updateByPrimaryKey(ICCardInvoiceApply record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_IC_CARD_INVOICE_APPLY.abatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_INVOICE_APPLY
	 * @abatorgenerated  Mon Feb 09 12:40:31 CST 2015
	 */
	public int updateByPrimaryKeySelective(ICCardInvoiceApply record) {
		int rows = getSqlMapClientTemplate()
				.update("TB_IC_CARD_INVOICE_APPLY.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_INVOICE_APPLY
	 * @abatorgenerated  Mon Feb 09 12:40:31 CST 2015
	 */
	public List selectByExample(ICCardInvoiceApplyExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_CARD_INVOICE_APPLY.abatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_INVOICE_APPLY
	 * @abatorgenerated  Mon Feb 09 12:40:31 CST 2015
	 */
	public ICCardInvoiceApply selectByPrimaryKey(String id) {
		ICCardInvoiceApply key = new ICCardInvoiceApply() {
		};
		key.setId(id);
		ICCardInvoiceApply record = (ICCardInvoiceApply) getSqlMapClientTemplate()
				.queryForObject(
						"TB_IC_CARD_INVOICE_APPLY.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_INVOICE_APPLY
	 * @abatorgenerated  Mon Feb 09 12:40:31 CST 2015
	 */
	public int deleteByExample(ICCardInvoiceApplyExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_IC_CARD_INVOICE_APPLY.abatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_INVOICE_APPLY
	 * @abatorgenerated  Mon Feb 09 12:40:31 CST 2015
	 */
	public int deleteByPrimaryKey(String id) {
		ICCardInvoiceApply key = new ICCardInvoiceApply() {
		};
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"TB_IC_CARD_INVOICE_APPLY.abatorgenerated_deleteByPrimaryKey",
				key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_INVOICE_APPLY
	 * @abatorgenerated  Mon Feb 09 12:40:31 CST 2015
	 */
	public int countByExample(ICCardInvoiceApplyExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_IC_CARD_INVOICE_APPLY.abatorgenerated_countByExample",
				example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_INVOICE_APPLY
	 * @abatorgenerated  Mon Feb 09 12:40:31 CST 2015
	 */
	public int updateByExampleSelective(ICCardInvoiceApply record,
			ICCardInvoiceApplyExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("TB_IC_CARD_INVOICE_APPLY.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_INVOICE_APPLY
	 * @abatorgenerated  Mon Feb 09 12:40:31 CST 2015
	 */
	public int updateByExample(ICCardInvoiceApply record,
			ICCardInvoiceApplyExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_IC_CARD_INVOICE_APPLY.abatorgenerated_updateByExample",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_INVOICE_APPLY
	 * @abatorgenerated  Mon Feb 09 12:40:31 CST 2015
	 */
	public List selectByExampleWithPage(ICCardInvoiceApplyExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_CARD_INVOICE_APPLY.abatorgenerated_selectByExamplePage",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_INVOICE_APPLY
	 * @abatorgenerated  Mon Feb 09 12:40:31 CST 2015
	 */
	public List selectByExampleWithPage(
			ICCardInvoiceApplyExampleExtended exampleExtended) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_IC_CARD_INVOICE_APPLY.abatorgenerated_selectByExampleExtendedPage",
						exampleExtended);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_INVOICE_APPLY
	 * @abatorgenerated  Mon Feb 09 12:40:31 CST 2015
	 */
	public List getKeyBy(ICCardInvoiceApplyExample example) {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"TB_IC_CARD_INVOICE_APPLY.abatorgenerated_selectKeyBy",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_INVOICE_APPLY
	 * @abatorgenerated  Mon Feb 09 12:40:31 CST 2015
	 */
	public String getNameSpace() {
		return "TB_IC_CARD_INVOICE_APPLY";
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_INVOICE_APPLY
	 * @abatorgenerated  Mon Feb 09 12:40:31 CST 2015
	 */
	public List getKeyBy(ICCardInvoiceApplyExampleExtended example) {
		List list = getSqlMapClientTemplate().queryForList(
				"TB_IC_CARD_INVOICE_APPLY.abatorgenerated_selectKeyByExtended",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_IC_CARD_INVOICE_APPLY
	 * @abatorgenerated  Mon Feb 09 12:40:31 CST 2015
	 */
	public int countByExample(ICCardInvoiceApplyExampleExtended example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject(
						"TB_IC_CARD_INVOICE_APPLY.abatorgenerated_countByExampleExtended",
						example);
		return count.intValue();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table TB_IC_CARD_INVOICE_APPLY
	 * @abatorgenerated  Mon Feb 09 12:40:31 CST 2015
	 */
	private static class UpdateByExampleParms extends ICCardInvoiceApplyExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				ICCardInvoiceApplyExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}